### ISSUE TITLE
Version 1.6.0: PathClassLoader throws java.io.Exception for non-zip files ("Archive is not a ZIP archive")

### ISSUE THREAD

**Issue by peterphan** [JetBrains/gradle-intellij-plugin#1009]
Hello,

I am trying to bump my `gradle-intellij-version` to 1.6.0 and ran into the exception below when running tests for SDK 221
```
Caused by: java.io.UncheckedIOException: java.io.IOException: /Users/pphan/.gradle/caches/modules-2/files-2.1/com.<redacted>.container/container-<redacted>-factory/37.2.13/4691969d0269a3fd903f6f19ed7bda86153b3db/container-<redacted>-factory-cmpt-def-37.2.13.xml
        at com.intellij.util.lang.ZipResourceFile.<init>(ZipResourceFile.java:38)
        at com.intellij.util.lang.PathClassLoader.lambda$static$1(PathClassLoader.java:31)
        at com.intellij.util.lang.ClassPath.createLoader(ClassPath.java:412)
        at com.intellij.util.lang.ClassPath.getLoaderSlowPath(ClassPath.java:363)
        at com.intellij.util.lang.ClassPath.getLoader(ClassPath.java:344)
        at com.intellij.util.lang.ClassPath.access$400(ClassPath.java:29)
        at com.intellij.util.lang.ClassPath$UncachedResourceEnumeration.next(ClassPath.java:528)
        at com.intellij.util.lang.ClassPath$UncachedResourceEnumeration.hasMoreElements(ClassPath.java:547)
        at java.base/java.lang.CompoundEnumeration.next(ClassLoader.java:3032)
        at java.base/java.lang.CompoundEnumeration.hasMoreElements(ClassLoader.java:3041)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1203)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
        at java.base/jdk.internal.logger.BootstrapLogger$DetectBackend$1.run(BootstrapLogger.java:890)
        at java.base/jdk.internal.logger.BootstrapLogger$DetectBackend$1.run(BootstrapLogger.java:884)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/jdk.internal.logger.BootstrapLogger$DetectBackend.<clinit>(BootstrapLogger.java:884)
        ... 30 more
Caused by: java.io.IOException: /Users/pphan/.gradle/caches/modules-2/files-2.1/com.<redacted>.container/container-<redacted>-factory/37.2.13/4691969d0269a3fd903f6f19ed7bda86153b3db/container-<redacted>-factory-cmpt-def-37.2.13.xml
        at com.intellij.util.lang.ImmutableZipFile.load(ImmutableZipFile.java:84)
        at com.intellij.util.lang.ImmutableZipFile.load(ImmutableZipFile.java:54)
        at com.intellij.util.lang.ZipResourceFile.<init>(ZipResourceFile.java:30)
        ... 48 more
Caused by: java.util.zip.ZipException: Archive is not a ZIP archive
        at com.intellij.util.lang.ImmutableZipFile.populateFromCentralDirectory(ImmutableZipFile.java:234)
        at com.intellij.util.lang.ImmutableZipFile.load(ImmutableZipFile.java:81)
        ... 50 more
```

I have XML files in my `.gradle/caches` directory. Is it possible to configure the class loader to exclude these files or fix the class loader to ignore non-jar files similar to something like https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/commit/9dcc6e22bcec9264cb5f06d5299e9df5fd8446fc

Thanks!

**Comment by vicky17d** [comment]
@hsz  This is blocking our upgrade to 2022.1.2. Could you please look into it? Thanks

**Comment by peterphan** [comment]
@hsz I found that this simple patch fixes out issue https://github.com/JetBrains/intellij-community/pull/2044

**Comment by hsz** [comment]
I'll try to investigate it next week.
