### ISSUE TITLE
Cause: key can't be empty

### ISSUE THREAD

**Issue by Bhala1987** [JetBrains/gradle-intellij-plugin#1073]
**Describe the bug**
**Getting "Cause: key can't be empty" when loading the Gradle project in the IntelliJ IDEA. This works fine on other QA machines.**

Add the full stack trace if available.
If possible, run the failing task with `--stacktrace` flag.
`
2022-07-28 23:36:05,136 [  30738]   INFO - #o.j.p.s.f.c.c.SbtCompilationSupervisor - Listening to incoming sbt compilation events on port 0.
2022-07-28 23:36:05,212 [  30814]   INFO - #c.a.t.i.i.GMavenIndexRepository - Refreshed disk cache successfully with a new ETag header: "ed3bfa".
2022-07-28 23:36:06,152 [  31754]   INFO - #c.i.o.u.i.UpdateCheckerService - scheduling old directories scan after 04/08/2022 23:36
2022-07-28 23:36:06,156 [  31758]   INFO - #c.i.i.s.IdeStartupScripts - 0 startup script(s) found
2022-07-28 23:36:06,184 [  31786]   INFO - #o.j.p.g.GradleManager - Instructing gradle to use java from C:\Program Files (x86)\Java\jdk1.8.0_231
2022-07-28 23:36:06,192 [  31794]   INFO - #o.j.p.g.GradleManager - Instructing gradle to use java from C:\Program Files (x86)\Java\jdk1.8.0_231
2022-07-28 23:36:06,196 [  31798]   INFO - #o.j.k.i.script - [KOTLIN_SCRIPTING] Loading script definitions [org.gradle.kotlin.dsl.KotlinInitScript] using classpath: C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-core-5.2.1.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-core-api-5.2.1.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-kotlin-dsl-1.1.3.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-kotlin-dsl-provider-plugins-1.1.3.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-kotlin-dsl-tooling-builders-1.1.3.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-kotlin-dsl-tooling-models-1.1.3.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\kotlin-stdlib-1.3.20.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\kotlin-compiler-embeddable-1.3.20.jar
2022-07-28 23:36:06,240 [  31842]   INFO - #o.j.p.g.GradleManager - Instructing gradle to use java from C:\Program Files (x86)\Java\jdk1.8.0_231
2022-07-28 23:36:06,244 [  31846]   INFO - #o.j.k.i.script - [KOTLIN_SCRIPTING] Loading script definitions [org.gradle.kotlin.dsl.KotlinSettingsScript] using classpath: C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-core-5.2.1.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-core-api-5.2.1.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-kotlin-dsl-1.1.3.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-kotlin-dsl-provider-plugins-1.1.3.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-kotlin-dsl-tooling-builders-1.1.3.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-kotlin-dsl-tooling-models-1.1.3.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\kotlin-stdlib-1.3.20.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\kotlin-compiler-embeddable-1.3.20.jar
2022-07-28 23:36:06,264 [  31866]   INFO - #o.j.p.g.GradleManager - Instructing gradle to use java from C:\Program Files (x86)\Java\jdk1.8.0_231
2022-07-28 23:36:06,264 [  31866]   INFO - #o.j.k.i.script - [KOTLIN_SCRIPTING] Loading script definitions [org.gradle.kotlin.dsl.KotlinBuildScript] using classpath: C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-core-5.2.1.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-core-api-5.2.1.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-kotlin-dsl-1.1.3.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-kotlin-dsl-provider-plugins-1.1.3.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-kotlin-dsl-tooling-builders-1.1.3.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\gradle-kotlin-dsl-tooling-models-1.1.3.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\kotlin-stdlib-1.3.20.jar;C:\Users\b.rajalakshmi\.gradle\wrapper\dists\gradle-5.2.1-all\bviwmvmbexq6idcscbicws5me\gradle-5.2.1\lib\kotlin-compiler-embeddable-1.3.20.jar
2022-07-28 23:36:09,027 [  34629]   INFO - #c.i.o.f.i.FileEditorManagerImpl - Project opening took 25028 ms
2022-07-28 23:36:09,091 [  34693]   INFO - #c.i.d.PerformanceWatcherImpl - Post-startup activities under progress took 14893ms; general responsiveness: ok; EDT responsiveness: 2/15 sluggish, 1/15 very slow
2022-07-28 23:36:09,104 [  34706]   INFO - #c.i.i.StartupUtil - notify that start-up thread is free
2022-07-28 23:36:13,784 [  39386]   INFO - #o.j.p.g.s.p.GradleProjectResolver - Gradle project resolve error
org.gradle.tooling.GradleConnectionException: Could not run phased build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-5.2.1-all.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55)
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:43)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:69)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: key can't be empty
	at java.lang.System.checkKey(System.java:841)
	at java.lang.System.setProperty(System.java:789)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:61)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
2022-07-28 23:36:13,862 [  39464]   INFO - #c.a.t.i.g.p.s.GradleSyncState$SyncStateUpdater - onFailure(RESOLVE_PROJECT:0, com.intellij.openapi.externalSystem.model.ExternalSystemException: Cause: key can't be empty)
2022-07-28 23:36:13,862 [  39464]   INFO - #c.a.t.i.g.p.s.GradleSyncState$SyncStateUpdaterService - stopTrackingTask(RESOLVE_PROJECT:0)
2022-07-28 23:36:13,862 [  39464]   WARN - #c.a.t.i.g.p.s.GradleSyncState - Gradle sync failed in 14 s 977 ms. Cause: key can't be empty
2022-07-28 23:36:13,862 [  39464]   WARN - #c.a.t.i.g.p.s.GradleSyncState - Cause: key can't be empty
com.intellij.openapi.externalSystem.model.ExternalSystemException: Cause: key can't be empty
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionErrorHandler.createUserFriendlyError(GradleExecutionErrorHandler.java:197)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectImportErrorHandler.createUserFriendlyError(AbstractProjectImportErrorHandler.java:46)
	at org.jetbrains.plugins.gradle.service.project.BaseProjectImportErrorHandler.doGetUserFriendlyError(BaseProjectImportErrorHandler.java:167)
	at org.jetbrains.plugins.gradle.service.project.BaseProjectImportErrorHandler.getUserFriendlyError(BaseProjectImportErrorHandler.java:48)
	at org.jetbrains.plugins.gradle.service.project.BaseProjectImportErrorHandler.checkErrorsWithoutQuickFixes(BaseProjectImportErrorHandler.java:62)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$1.getUserFriendlyError(GradleProjectResolver.java:873)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:802)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:771)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.lambda$execute$0(GradleExecutionHelper.java:132)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.maybeFixSystemProperties(GradleExecutionHelper.java:158)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.lambda$execute$1(GradleExecutionHelper.java:132)
	at org.jetbrains.plugins.gradle.GradleConnectorService$Companion.withGradleConnection(GradleConnectorService.kt:181)
	at org.jetbrains.plugins.gradle.GradleConnectorService.withGradleConnection(GradleConnectorService.kt)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.execute(GradleExecutionHelper.java:128)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:151)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:71)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.lambda$resolveProjectInfo$0(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:43)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:36)
	at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:48)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:115)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:151)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:135)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.executeImpl(ExternalSystemUtil.java:491)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.lambda$execute$0(ExternalSystemUtil.java:327)
	at com.intellij.openapi.project.DumbServiceHeavyActivities.suspendIndexingAndRun(DumbServiceHeavyActivities.java:21)
	at com.intellij.openapi.project.DumbServiceImpl.suspendIndexingAndRun(DumbServiceImpl.java:187)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.execute(ExternalSystemUtil.java:327)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4.run(ExternalSystemUtil.java:614)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: key can't be empty
	at java.lang.System.checkKey(System.java:841)
	at java.lang.System.setProperty(System.java:789)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:61)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
`

**To Reproduce**
Steps to reproduce the behavior – provide your build configuration, and/or link to the failing GitHub Action job.
1. git clone https://github.com/Bhala1987/grpc.git
2. follow the README.md steps/actions

**Expected behavior**
Should be able to run the gradle build & no error or "Cause: key can't be empty"

**Environment:**
 - OS: [e.g. macOS] - Windows 10 Pro
 - Gradle IntelliJ Plugin Version [e.g. 1.6.0] - 4.72
 - Gradle Version [e.g. 7.4.2] - 5.2.1 , also tried with 7.5 latest

**Additional context**
On checking the stack trace logs, I found that it threw an error on checkKey(key); in the java rt.jar method it seems:
` 
public static String getProperty(String key) {
        checkKey(key);
        SecurityManager sm = getSecurityManager();
        if (sm != null) {
            sm.checkPropertyAccess(key);
        }

        return props.getProperty(key);
    }
`

![image](https://user-images.githubusercontent.com/29075298/181805959-0dcfd98f-fcd2-4b54-8b05-1b46ed37d497.png)

**Comment by YannCebron** [comment]
Your problem is unrelated to the gradle-intellij-plugin which is used exclusively for developing plugins for the IJ Platform.

Please report your issue in product support channels https://intellij-support.jetbrains.com/hc/en-us/?intellij-idea
