### ISSUE TITLE
Could not initialize class com.intellij.openapi.vfs.newvfs.ManagingFS$ManagingFSHolder when running tests with 1.9.0 

### ISSUE THREAD

**Issue by arturbosch** [JetBrains/gradle-intellij-plugin#1109]
**Describe the bug**

Upgrading the plugin from 1.6.0 to 1.9.0 (or 1.7/.8) and running `gradle build` will lead to a test crash with following stacktrace:

```
DetektAnnotatorTest > initializationError FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.intellij.openapi.vfs.newvfs.ManagingFS$ManagingFSHolder
        at com.intellij.openapi.vfs.newvfs.ManagingFS.getInstance(ManagingFS.java:19)
        at com.intellij.openapi.vfs.newvfs.persistent.PersistentFS.getInstance(PersistentFS.java:53)
        at com.intellij.SimpleApplicationBootstrapperKt.doLoadApp(simpleApplicationBootstrapper.kt:76)
        at com.intellij.testFramework.TestApplicationManager$Companion.createInstance(TestApplicationManager.kt:131)
        at com.intellij.testFramework.TestApplicationManager$Companion.getInstance(TestApplicationManager.kt:99)
        at com.intellij.testFramework.TestApplicationManager.getInstance(TestApplicationManager.kt)
        at com.intellij.testFramework.fixtures.impl.LightIdeaTestFixtureImpl.setUp(LightIdeaTestFixtureImpl.java:41)
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.lambda$setUp$28(CodeInsightTestFixtureImpl.java:1241)
        at com.intellij.testFramework.EdtTestUtil.lambda$runInEdtAndWait$1(EdtTestUtil.java:40)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
ERROR: Could not initialize class com.intellij.openapi.vfs.newvfs.ManagingFS$ManagingFSHolder
java.lang.NoClassDefFoundError: Could not initialize class com.intellij.openapi.vfs.newvfs.ManagingFS$ManagingFSHolder
        at com.intellij.openapi.vfs.newvfs.ManagingFS.getInstance(ManagingFS.java:19)
        at com.intellij.openapi.vfs.newvfs.persistent.PersistentFS.getInstance(PersistentFS.java:53)
        at com.intellij.openapi.vfs.impl.jar.ArchiveCachesCleaner.beforeConnectionClosed(ArchiveCachesCleaner.kt:17)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.disconnect(PersistentFSImpl.java:114)
        at com.intellij.openapi.util.ShutDownTracker.run(ShutDownTracker.java:46)
        at java.base/java.lang.Thread.run(Thread.java:829)
``` 

**To Reproduce**
1. `git clone https://github.com/detekt/detekt-intellij-plugin`
2. Increment plugin version in `build.gradle.kts:L14`
3. Run `gradle build`

**Expected behavior**
Tests do not crash.

**Environment:**
 - OS: Linux, Fedora 37 Beta (or Stable 36)
 - Gradle IntelliJ Plugin Version 1.9.0
 - Gradle Version 7.4.2

**Additional context**
Crash happens with 1.7 and 1.8 too.

Using Gradle 7.5.1 will lead to a different stacktrace:

```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 2.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
	at java.base@11.0.15/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.15/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.15/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.15/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.NoClassDefFoundError: org/junit/platform/launcher/LauncherSessionListener
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1210)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at org.junit.platform.launcher.core.LauncherFactory.createLauncherSessionListener(LauncherFactory.java:154)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:125)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:109)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:97)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	... 18 more
Caused by: java.lang.ClassNotFoundException: org.junit.platform.launcher.LauncherSessionListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 42 more
```

**Comment by arturbosch** [comment]
When using IJ 2022.2.3 the stacktrace changes to:

```
ERROR: Index data initialization failed
    java.util.MissingResourceException: Registry key indexing.filename.over.vfs is not defined
        at com.intellij.openapi.util.registry.Registry.getBundleValue(Registry.java:170)
        at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:233)
        at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:203)
        at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.java:62)
        at com.intellij.openapi.util.registry.Registry.is(Registry.java:63)
        at com.intellij.util.indexing.RegisteredIndexes.registerIndexExtension(RegisteredIndexes.java:120)
        at com.intellij.util.indexing.FileBasedIndexDataInitialization.initAssociatedDataForExtensions(FileBasedIndexDataInitialization.java:77)
        at com.intellij.util.indexing.FileBasedIndexDataInitialization.prepareTasks(FileBasedIndexDataInitialization.java:119)
        at com.intellij.util.indexing.IndexDataInitializer.call(IndexDataInitializer.kt:20)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
        at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
        at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
        at java.base/java.lang.Thread.run(Thread.java:829)

DetektAnnotatorTest > initializationError FAILED
    java.lang.ExceptionInInitializerError
        at com.intellij.util.concurrency.Propagation.propagateThreadContext(Propagation.java:47)
        at com.intellij.util.concurrency.AppExecutorUtil.propagateContextOrCancellation(AppExecutorUtil.java:114)
        at com.intellij.util.concurrency.SchedulingWrapper.createTask(SchedulingWrapper.java:368)
        at com.intellij.util.concurrency.SchedulingWrapper.scheduleWithFixedDelay(SchedulingWrapper.java:360)
        at com.intellij.util.concurrency.AppScheduledExecutorService.scheduleWithFixedDelay(AppScheduledExecutorService.java:25)
        at com.intellij.util.Timed.<clinit>(Timed.java:67)
        at com.intellij.openapi.project.impl.DefaultProject.<init>(DefaultProject.java:37)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.<init>(ProjectManagerImpl.java:73)
        at com.intellij.openapi.project.impl.ProjectManagerExImpl.<init>(ProjectManagerExImpl.kt:60)
        at com.intellij.project.TestProjectManager.<init>(TestProjectManager.kt:34)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
        at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:890)
        at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
        at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
        at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:609)
        at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:583)
        at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
        at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
        at com.intellij.openapi.project.ex.ProjectManagerEx.getInstanceEx(ProjectManagerEx.java:19)
        at com.intellij.testFramework.LightPlatformTestCase.initProject(LightPlatformTestCase.java:191)
        at com.intellij.testFramework.LightPlatformTestCase.lambda$doSetup$2(LightPlatformTestCase.java:277)
        at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:492)
        at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:525)
        at com.intellij.testFramework.LightPlatformTestCase.doSetup(LightPlatformTestCase.java:268)
        at com.intellij.testFramework.fixtures.impl.LightIdeaTestFixtureImpl.setUp(LightIdeaTestFixtureImpl.java:42)
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.lambda$setUp$28(CodeInsightTestFixtureImpl.java:1241)
        at com.intellij.testFramework.EdtTestUtil.lambda$runInEdtAndWait$1(EdtTestUtil.java:40)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

        Caused by:
        java.util.MissingResourceException: Registry key ide.propagate.context is not defined
            at com.intellij.openapi.util.registry.Registry.getBundleValue(Registry.java:170)
            at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:233)
            at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:203)
            at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.java:62)
            at com.intellij.openapi.util.registry.Registry.is(Registry.java:63)
            at com.intellij.util.concurrency.Propagation$Holder.<clinit>(Propagation.java:25)
            ... 47 more
```

**Comment by YannCebron** [comment]
are you using Snapshot version of plugin? https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin-faq.html#how-to-target-20223-platform

**Comment by hsz** [comment]
Is this issue still relevant with the `1.13.2`?

**Comment by arturbosch** [comment]
Hm, unfortunately I can't tell anymore as in the meantime I migrated away from `TestFixture`'s and `TestCase`'s to be able to upgrade the plugin and gradle.
I'm also on 2022.1.4 as the minimal plugin version.

Adding 
```kotlin
package io.gitlab.arturbosch.detekt.idea

import com.intellij.testFramework.fixtures.BasePlatformTestCase

class Test : BasePlatformTestCase() {

    fun testTest() {
        println("Hello")
    }
}
```

leads to a new kind of error:

```
ERROR: jarFiles is not set for PluginDescriptor(name=detekt, id=detekt, descriptorPath=plugin.xml, path=~/git/repos/detekt-intellij-plugin/out/production/resources, version=221.6008.13, package=null, isBundled=true)
java.lang.Throwable: jarFiles is not set for PluginDescriptor(name=detekt, id=detekt, descriptorPath=plugin.xml, path=~/git/repos/detekt-intellij-plugin/out/production/resources, version=221.6008.13, package=null, isBundled=true)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.ide.plugins.ClassLoaderConfigurator.configureModule(ClassLoaderConfigurator.kt:107)
	at com.intellij.ide.plugins.ClassLoaderConfigurator.configure(ClassLoaderConfigurator.kt:87)
	at com.intellij.ide.plugins.PluginManagerCore.initializePlugins(PluginManagerCore.java:867)
	at com.intellij.ide.plugins.PluginManagerCore.loadAndInitializePlugins(PluginManagerCore.java:987)
	at com.intellij.ide.plugins.PluginManagerCore.lambda$getOrScheduleLoading$5(PluginManagerCore.java:622)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

com.intellij.testFramework.TestLogger$TestLoggerAssertionError: jarFiles is not set for PluginDescriptor(name=detekt, id=detekt, descriptorPath=plugin.xml, path=~/git/repos/detekt-intellij-plugin/out/production/resources, version=221.6008.13, package=null, isBundled=true)

	at com.intellij.testFramework.TestLogger.error(TestLogger.java:45)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.ide.plugins.ClassLoaderConfigurator.configureModule(ClassLoaderConfigurator.kt:107)
	at com.intellij.ide.plugins.ClassLoaderConfigurator.configure(ClassLoaderConfigurator.kt:87)
	at com.intellij.ide.plugins.PluginManagerCore.initializePlugins(PluginManagerCore.java:867)
	at com.intellij.ide.plugins.PluginManagerCore.loadAndInitializePlugins(PluginManagerCore.java:987)
	at com.intellij.ide.plugins.PluginManagerCore.lambda$getOrScheduleLoading$5(PluginManagerCore.java:622)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.Throwable: jarFiles is not set for PluginDescriptor(name=detekt, id=detekt, descriptorPath=plugin.xml, path=~/git/repos/detekt-intellij-plugin/out/production/resources, version=221.6008.13, package=null, isBundled=true)
	... 13 more
```

I will close this as it may be related to Idea 2021.3 and/or old plugin - gradle combinations.
