### ISSUE TITLE
Java task rejected error 

### ISSUE THREAD

**Issue by pwypychamelco** [JetBrains/gradle-intellij-plugin#1171]
**Plugin error **

**To Reproduce**
Steps to reproduce the behavior – provide your build configuration, and/or link to the failing GitHub Action job.

**Expected behavior**
loading plugi properly

**Environment:**
 - OS: Win10 64bit
 - GitToolBox - 212.9.9
 - IntelliJ Version 2022.2.3 (comunity edition) 
 -Build #IC-222.4345.14, built on October 5, 2022
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Stacktrace.txt**
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6a45d064[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@6866e6d2[Wrapped task = l[task=zielu.a.b.n@41042b08]]] rejected from java.util.concurrent.ThreadPoolExecutor@1af09695[Running, pool size = 1024, active threads = 1024, queued tasks = 0, completed tasks = 3656]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
	at zielu.gittoolbox.b.a(SourceFile:72)
	at zielu.gittoolbox.C.r.a(SourceFile:40)
	at zielu.gittoolbox.d.m.a(SourceFile:21)
	at zielu.gittoolbox.d.i.a(SourceFile:22)
	at zielu.gittoolbox.d.k.changeListUpdateDone(SourceFile:21)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:646)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:625)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:399)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:378)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:437)
	at jdk.proxy2/jdk.proxy2.$Proxy75.changeListUpdateDone(Unknown Source)
	at com.intellij.openapi.vcs.changes.DelayedNotificator.lambda$changeListUpdateDone$13(DelayedNotificator.java:114)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl$MyLoggingRunnable.run(ChangeListManagerImpl.java:1699)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zielu** [comment]
@pwypychamelco should be reported here: https://github.com/zielu/GitToolBox/issues
