### ISSUE TITLE
Plugin dependencies not resolved in multi-module project

### ISSUE THREAD

**Issue by brian-mcnamara** [JetBrains/gradle-intellij-plugin#1196]
**Describe the bug**
In a multi-module plugin where two modules have an intellij block (in my case, the top level module is for IC and the child-module is for IU), the child modules do not resolve the IJ plugin dependencies when loaded into intellij.

**To Reproduce**
https://github.com/brian-mcnamara/plugin-demo/tree/multi-module
Load that branch into IJ using the latest 1.10 snapshot. Notice the IU module does not list any dependencies (the javascript plugin should be there)

**Expected behavior**
If you use 1.9.0, you will see that IJ does resolve the dependencies correctly

**Environment:**
 - OS: macOS
 - Gradle IntelliJ Plugin Version 1.10.0-SNAPSHOT
 - Gradle Version 7.4.2

**Additional context**
Thread here: https://jetbrains-platform.slack.com/archives/CPL5291JP/p1668123533621749

**Comment by hsz** [comment]
@brian-mcnamara I cannot reproduce it when pointing to the latest `1.10.0-SNAPSHOT`.
Both modules produce archives in `build/distributions` with to issues:
<img width="523" alt="image" src="https://user-images.githubusercontent.com/108333/201747860-6601260b-19ac-425b-89a2-97d7e40c29fa.png">

The IU module also contains relevant dependencies:
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/108333/201748282-e2a2685a-e3e9-4cbc-ac1b-1816d27f4d43.png">

**Comment by brian-mcnamara** [comment]
Hmm, I tried --refresh-dependencies again and still the same issue. Restarted IJ as well...
<img width="1026" alt="Screenshot 2022-11-14 at 11 39 34 AM" src="https://user-images.githubusercontent.com/22810320/201750606-f352b3be-4370-42a7-bac6-a7b0032bdccc.png">

**Comment by brian-mcnamara** [comment]
Ok cloned it on a different machine and everything is working. Wonder if there is another gradle cache somewhere effecting my main machine.

**Comment by hsz** [comment]
I guess so. There's `--refresh-dependencies` magic 🪄 switch available to invalidate the Gradle cache.

**Comment by brian-mcnamara** [comment]
Still unable to fix this locally, tried clearing ~/.gradle/caches, clearing IJ indexes, using `--refresh-dependencies`. Will keep trying. I have been getting 
```
Caused by: org.gradle.api.InvalidUserDataException: Cannot change dependencies of dependency configuration ':IU:compileOnly' after it has been included in dependency resolution.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.preventIllegalMutation(DefaultConfiguration.java:1384)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:1344)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.extendsFrom(DefaultConfiguration.java:395)
	at org.jetbrains.intellij.IntelliJPlugin$configureSetupDependenciesTask$1$ideaConfiguration$1$1.invoke(IntelliJPlugin.kt:1475)
	at org.jetbrains.intellij.IntelliJPlugin$configureSetupDependenciesTask$1.invoke(IntelliJPlugin.kt:1477)
	at org.jetbrains.intellij.IntelliJPlugin$configureSetupDependenciesTask$1.invoke(IntelliJPlugin.kt:112)
	at org.jetbrains.intellij.IntelliJPlugin$inlined$sam$i$org_gradle_api_Action$0.execute(TaskContainerExtensions.kt)
	at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:44)
	at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:44)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:107)
	at org.gradle.internal.ImmutableActionSet$SetWithManyActions.execute(ImmutableActionSet.java:329)
	at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:262)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.doAdd(DefaultNamedDomainObjectCollection.java:113)
	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:256)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:944)
	... 177 more
	```
Which I wonder if that is to be conserned with

**Comment by hsz** [comment]
I've reproduced the missing dependencies issue and sent the fix – it's now available as a snapshot.

**Comment by brian-mcnamara** [comment]
Looks good! Thanks for finding the repo, I tried for a while on the machine that worked without success.
