### ISSUE TITLE
Gradle 8.2 compatibility

### ISSUE THREAD

**Issue by TWiStErRob** [JetBrains/gradle-intellij-plugin#1413]
**Is your feature request related to a problem? Please describe.**
Gradle 8.2 deprecated conventions with nagging. They were deprecated for a long time, but without nagging.

https://docs.gradle.org/8.2-rc-2/userguide/upgrading_version_8.html#deprecated_access_to_conventions

**Describe the solution you'd like**
Migrate away from using conventions to extensions, so builds can pass nicely even with `org.gradle.warning.mode=fail`. At Gradle 9.0 this will become an error, so sooner or later the migration has to be done. Better do it sooner :)

**Describe alternatives you've considered**

**Additional context**
```
The Project.getConvention() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2-rc-2/userguide/upgrading_version_8.html#deprecated_access_to_conventions
	at org.gradle.api.internal.project.DefaultProject.getConvention(DefaultProject.java:593)
	at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(utils.kt:64)
	at org.jetbrains.intellij.IntelliJPlugin$configurePatchPluginXmlTask$1$2.call(IntelliJPlugin.kt:476)
	at org.jetbrains.intellij.IntelliJPlugin$configurePatchPluginXmlTask$1$2.call(IntelliJPlugin.kt:475)
	at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:72)
```

(this is just one example, you can see all usages at https://github.com/TWiStErRob/net.twisterrob.chroma/actions/runs/5355711906/jobs/9714328563?pr=13)

**Comment by TWiStErRob** [comment]
I had a quick look, it doesn't seem as bad as 2.x. In my simple project there are only a few usages, all centralized in the same method `sourcePluginXmlFiles`:

<details><summary>There's 5 usages of `org.gradle.api.plugins.JavaPluginConvention`</summary>

```
at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(utils.kt:65)
at org.jetbrains.intellij.IntelliJPlugin.configureTestTasks(IntelliJPlugin.kt:1169)
at org.jetbrains.intellij.IntelliJPlugin.configureProjectAfterEvaluate(IntelliJPlugin.kt:387)
at org.jetbrains.intellij.IntelliJPlugin.access$configureProjectAfterEvaluate(IntelliJPlugin.kt:122)
at org.jetbrains.intellij.IntelliJPlugin$configureTasks$7.execute(IntelliJPlugin.kt:236)
at org.jetbrains.intellij.IntelliJPlugin$configureTasks$7.execute(IntelliJPlugin.kt:235)

at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(utils.kt:65)
at org.jetbrains.intellij.IntelliJPlugin.prepareConventionMappingsForRunIdeTask(IntelliJPlugin.kt:888)
at org.jetbrains.intellij.IntelliJPlugin.access$prepareConventionMappingsForRunIdeTask(IntelliJPlugin.kt:122)
at org.jetbrains.intellij.IntelliJPlugin$configureTasks$1.execute(IntelliJPlugin.kt:189)
at org.jetbrains.intellij.IntelliJPlugin$configureTasks$1.execute(IntelliJPlugin.kt:188)

at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(utils.kt:65)
at org.jetbrains.intellij.IntelliJPlugin.verifyJavaPluginDependency(IntelliJPlugin.kt:393)
at org.jetbrains.intellij.IntelliJPlugin.configurePluginDependencies(IntelliJPlugin.kt:1580)
at org.jetbrains.intellij.IntelliJPlugin.access$configurePluginDependencies(IntelliJPlugin.kt:122)
at org.jetbrains.intellij.IntelliJPlugin$configureDependencies$ideaPlugins$1.execute(IntelliJPlugin.kt:308)
at org.jetbrains.intellij.IntelliJPlugin$configureDependencies$ideaPlugins$1.execute(IntelliJPlugin.kt:307)

at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(utils.kt:65)
at org.jetbrains.intellij.IntelliJPlugin$configurePatchPluginXmlTask$1$2.call(IntelliJPlugin.kt:476)
at org.jetbrains.intellij.IntelliJPlugin$configurePatchPluginXmlTask$1$2.call(IntelliJPlugin.kt:475)

at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(utils.kt:65)
at org.jetbrains.intellij.IntelliJPlugin$configurePatchPluginXmlTask$1$2.call(IntelliJPlugin.kt:476)
at org.jetbrains.intellij.IntelliJPlugin$configurePatchPluginXmlTask$1$2.call(IntelliJPlugin.kt:475)
```

</details>

<details><summary>There's 5 usages of `Project.getConvention()`</summary>

```
at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(utils.kt:64)
at org.jetbrains.intellij.IntelliJPlugin.configureTestTasks(IntelliJPlugin.kt:1169)
at org.jetbrains.intellij.IntelliJPlugin.configureProjectAfterEvaluate(IntelliJPlugin.kt:387)
at org.jetbrains.intellij.IntelliJPlugin.access$configureProjectAfterEvaluate(IntelliJPlugin.kt:122)
at org.jetbrains.intellij.IntelliJPlugin$configureTasks$7.execute(IntelliJPlugin.kt:236)
at org.jetbrains.intellij.IntelliJPlugin$configureTasks$7.execute(IntelliJPlugin.kt:235)

at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(utils.kt:64)
at org.jetbrains.intellij.IntelliJPlugin.prepareConventionMappingsForRunIdeTask(IntelliJPlugin.kt:888)
at org.jetbrains.intellij.IntelliJPlugin.access$prepareConventionMappingsForRunIdeTask(IntelliJPlugin.kt:122)
at org.jetbrains.intellij.IntelliJPlugin$configureTasks$1.execute(IntelliJPlugin.kt:189)
at org.jetbrains.intellij.IntelliJPlugin$configureTasks$1.execute(IntelliJPlugin.kt:188)

at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(utils.kt:64)
at org.jetbrains.intellij.IntelliJPlugin.verifyJavaPluginDependency(IntelliJPlugin.kt:393)
at org.jetbrains.intellij.IntelliJPlugin.configurePluginDependencies(IntelliJPlugin.kt:1580)
at org.jetbrains.intellij.IntelliJPlugin.access$configurePluginDependencies(IntelliJPlugin.kt:122)
at org.jetbrains.intellij.IntelliJPlugin$configureDependencies$ideaPlugins$1.execute(IntelliJPlugin.kt:308)
at org.jetbrains.intellij.IntelliJPlugin$configureDependencies$ideaPlugins$1.execute(IntelliJPlugin.kt:307)

at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(utils.kt:64)
at org.jetbrains.intellij.IntelliJPlugin$configurePatchPluginXmlTask$1$2.call(IntelliJPlugin.kt:476)
at org.jetbrains.intellij.IntelliJPlugin$configurePatchPluginXmlTask$1$2.call(IntelliJPlugin.kt:475)

at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(utils.kt:64)
at org.jetbrains.intellij.IntelliJPlugin$configurePatchPluginXmlTask$1$2.call(IntelliJPlugin.kt:476)
at org.jetbrains.intellij.IntelliJPlugin$configurePatchPluginXmlTask$1$2.call(IntelliJPlugin.kt:475)
```

</details>

<details><summary>There's a 4 usages of `org.gradle.api.plugins.Convention`</summary>

```
at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(utils.kt:383)
at org.jetbrains.intellij.IntelliJPlugin.configureTestTasks(IntelliJPlugin.kt:1169)
at org.jetbrains.intellij.IntelliJPlugin.configureProjectAfterEvaluate(IntelliJPlugin.kt:387)
at org.jetbrains.intellij.IntelliJPlugin.access$configureProjectAfterEvaluate(IntelliJPlugin.kt:122)
at org.jetbrains.intellij.IntelliJPlugin$configureTasks$7.execute(IntelliJPlugin.kt:236)
at org.jetbrains.intellij.IntelliJPlugin$configureTasks$7.execute(IntelliJPlugin.kt:235)

at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(utils.kt:383)
at org.jetbrains.intellij.IntelliJPlugin.prepareConventionMappingsForRunIdeTask(IntelliJPlugin.kt:888)
at org.jetbrains.intellij.IntelliJPlugin.access$prepareConventionMappingsForRunIdeTask(IntelliJPlugin.kt:122)
at org.jetbrains.intellij.IntelliJPlugin$configureTasks$1.execute(IntelliJPlugin.kt:189)
at org.jetbrains.intellij.IntelliJPlugin$configureTasks$1.execute(IntelliJPlugin.kt:188)

at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(utils.kt:383)
at org.jetbrains.intellij.IntelliJPlugin.verifyJavaPluginDependency(IntelliJPlugin.kt:393)
at org.jetbrains.intellij.IntelliJPlugin.configurePluginDependencies(IntelliJPlugin.kt:1580)
at org.jetbrains.intellij.IntelliJPlugin.access$configurePluginDependencies(IntelliJPlugin.kt:122)
at org.jetbrains.intellij.IntelliJPlugin$configureDependencies$ideaPlugins$1.execute(IntelliJPlugin.kt:308)
at org.jetbrains.intellij.IntelliJPlugin$configureDependencies$ideaPlugins$1.execute(IntelliJPlugin.kt:307)

at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(utils.kt:383)
at org.jetbrains.intellij.IntelliJPlugin$configurePatchPluginXmlTask$1$2.call(IntelliJPlugin.kt:476)
at org.jetbrains.intellij.IntelliJPlugin$configurePatchPluginXmlTask$1$2.call(IntelliJPlugin.kt:475)
```

</details>

Raised #1416 to fix.
