### ISSUE TITLE
Exception with 2023.3 eap6: `... module java.base does not "opens java.io" to unnamed module`

### ISSUE THREAD

**Issue by jansorg** [JetBrains/gradle-intellij-plugin#1484]
### What happened?

I updated to 2023.3 eap6 and executed a test. 
```
ideVersion=IC-233.11361.10-EAP-SNAPSHOT
```

### Relevant log output or stack trace

```shell
java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private static java.util.LinkedHashSet java.io.DeleteOnExitHook.files accessible: module java.base does not "opens java.io" to unnamed module @5afa04c
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.intellij.util.ReflectionUtil.findFieldInHierarchy(ReflectionUtil.java:153)
	at com.intellij.util.ReflectionUtil.findAssignableField(ReflectionUtil.java:141)
	at com.intellij.util.ReflectionUtil.getStaticFieldValue(ReflectionUtil.java:338)
	at com.intellij.testFramework.UsefulTestCase.<clinit>(UsefulTestCase.java:352)
	... 24 more


Process finished with exit code 255
```

### Steps to reproduce

I don't know exactly. When a test fails, it fails reproducible. But not all test fail.

### Gradle IntelliJ Plugin version

1.16.0

### Gradle version

8.4

### Operating System

Linux

**Comment by jansorg** [comment]
Hm, for unknown reasons the test was created as "JUnit" and not as "Gradle" run configuration. (I'm also using eap6 for development). Most likely, that's the reason of this exception, I think.
