### ISSUE TITLE
> Process 'command '/Library/Java/JavaVirtualMachines/corretto-17.0.8/Contents/Home/bin/java'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by Drjacky** [JetBrains/gradle-intellij-plugin#1513]
### What happened?

Cannot sign the plugin

### Relevant log output or stack trace

```shell
✗ ./gradlew signPlugin --stacktrace
Calculating task graph as configuration cache cannot be reused because file 'gradle.properties' has changed.

> Task :buildSearchableOptions
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
java.lang.Error: no ComponentUI class for: com.intellij.util.ui.tree.PerFileConfigurableBase$PerFileConfigurableComboBoxAction$1[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true]
        at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:763)
        at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:144)
        at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:793)
        at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1078)
        at java.desktop/javax.swing.JButton.updateUI(JButton.java:144)
        at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.updateUI(ComboBoxAction.java:372)
        at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2141)
        at java.desktop/javax.swing.JButton.<init>(JButton.java:134)
        at java.desktop/javax.swing.JButton.<init>(JButton.java:88)
        at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.<init>(ComboBoxAction.java:152)
        at com.intellij.util.ui.tree.PerFileConfigurableBase$PerFileConfigurableComboBoxAction$1.<init>(PerFileConfigurableBase.java:882)
        at com.intellij.util.ui.tree.PerFileConfigurableBase$PerFileConfigurableComboBoxAction.createComboBoxButton(PerFileConfigurableBase.java:882)
        at com.intellij.openapi.actionSystem.ex.ComboBoxAction.createCustomComponent(ComboBoxAction.java:86)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createActionPanel(PerFileConfigurableBase.java:614)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createActionPanel(PerFileConfigurableBase.java:606)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createActionPanel(PerFileConfigurableBase.java:600)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createDefaultMappingComponent(PerFileConfigurableBase.java:222)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createComponent(PerFileConfigurableBase.java:181)
        at com.intellij.openapi.vfs.encoding.FileEncodingConfigurable.createComponent(FileEncodingConfigurable.java:159)
        at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:169)
        at com.intellij.ide.ui.search.SearchUtil.processConfigurables(SearchUtil.java:75)
        at com.intellij.ide.ui.search.TraverseUIStarter.lambda$startup$0(TraverseUIStarter.java:120)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
        at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
java.lang.Error: no ComponentUI class for: com.intellij.util.ui.tree.PerFileConfigurableBase$PerFileConfigurableComboBoxAction$1[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true]
        at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:763)
        at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:144)
        at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:793)
        at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1078)
        at java.desktop/javax.swing.JButton.updateUI(JButton.java:144)
        at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.updateUI(ComboBoxAction.java:372)
        at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2141)
        at java.desktop/javax.swing.JButton.<init>(JButton.java:134)
        at java.desktop/javax.swing.JButton.<init>(JButton.java:88)
        at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.<init>(ComboBoxAction.java:152)
        at com.intellij.util.ui.tree.PerFileConfigurableBase$PerFileConfigurableComboBoxAction$1.<init>(PerFileConfigurableBase.java:882)
        at com.intellij.util.ui.tree.PerFileConfigurableBase$PerFileConfigurableComboBoxAction.createComboBoxButton(PerFileConfigurableBase.java:882)
        at com.intellij.openapi.actionSystem.ex.ComboBoxAction.createCustomComponent(ComboBoxAction.java:86)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createActionPanel(PerFileConfigurableBase.java:614)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createActionPanel(PerFileConfigurableBase.java:606)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createActionPanel(PerFileConfigurableBase.java:600)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createDefaultMappingComponent(PerFileConfigurableBase.java:222)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createComponent(PerFileConfigurableBase.java:181)
        at com.intellij.openapi.vfs.encoding.FileEncodingConfigurable.createComponent(FileEncodingConfigurable.java:159)
        at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:169)
        at com.intellij.ide.ui.search.SearchUtil.processConfigurables(SearchUtil.java:75)
        at com.intellij.ide.ui.search.TraverseUIStarter.lambda$startup$0(TraverseUIStarter.java:120)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
        at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
java.lang.Error: no ComponentUI class for: com.intellij.util.ui.tree.PerFileConfigurableBase$PerFileConfigurableComboBoxAction$1[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true]
        at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:763)
        at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:144)
        at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:793)
        at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1078)
        at java.desktop/javax.swing.JButton.updateUI(JButton.java:144)
        at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.updateUI(ComboBoxAction.java:372)
        at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2141)
        at java.desktop/javax.swing.JButton.<init>(JButton.java:134)
        at java.desktop/javax.swing.JButton.<init>(JButton.java:88)
        at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.<init>(ComboBoxAction.java:152)
        at com.intellij.util.ui.tree.PerFileConfigurableBase$PerFileConfigurableComboBoxAction$1.<init>(PerFileConfigurableBase.java:882)
        at com.intellij.util.ui.tree.PerFileConfigurableBase$PerFileConfigurableComboBoxAction.createComboBoxButton(PerFileConfigurableBase.java:882)
        at com.intellij.openapi.actionSystem.ex.ComboBoxAction.createCustomComponent(ComboBoxAction.java:86)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createActionPanel(PerFileConfigurableBase.java:614)
        at com.intellij.util.ui.tree.PerFileConfigurableBase.createActionPanel(PerFileConfigurableBase.java:610)
        at com.intellij.openapi.vfs.encoding.FileEncodingConfigurable.createComponent(FileEncodingConfigurable.java:163)
        at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:169)
        at com.intellij.ide.ui.search.SearchUtil.processConfigurables(SearchUtil.java:75)
        at com.intellij.ide.ui.search.TraverseUIStarter.lambda$startup$0(TraverseUIStarter.java:120)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
        at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-12-22 18:08:30,961 [   5051]   WARN - JetBrains UI DSL - Unsupported labeled component: com.intellij.ui.components.JBList
2023-12-22 18:08:31,407 [   5497]   WARN - #c.i.u.j.JBCefApp - JCEF is manually disabled in headless env via 'ide.browser.jcef.headless.enabled=false'
Found 218 configurables
Output written to /build/searchableOptions/devkit.jar!/search/devkit.jar!.searchableOptions.xml
Output written to /build/searchableOptions/platform-statistics-devkit.jar/search/platform-statistics-devkit.jar.searchableOptions.xml
Output written to /build/searchableOptions/textmate.jar/search/textmate.jar.searchableOptions.xml
.
.
.
Output written to /build/searchableOptions/settingsSync.jar/search/settingsSync.jar.searchableOptions.xml
Searchable options index builder completed

BUILD SUCCESSFUL in 8s
14 actionable tasks: 4 executed, 10 up-to-date
Configuration cache entry stored.
```

### Steps to reproduce

Try to sign this plugin: https://github.com/Drjacky/Avocado/

### Gradle IntelliJ Plugin version

1.16.1

### Gradle version

8.5

### Operating System

macOS

### Link to build, i.e. failing GitHub Action job

https://github.com/Drjacky/Avocado/actions/runs/7303002348/job/19902679041

**Comment by hsz** [comment]
I'm confused - you're mentioning three different issues here:

- the stack trace shows IDE errors, but the task eventually succeeds. This can be ignored.
- The linked build fails on plugin publishing, not signing: `token property must be specified for plugin publishing`. Please review your configuration.
- "Cannot sign the plugin" - how? There's no indicator that the signing failed.

Please review your setup and file a new ticket with more details.

**Comment by Drjacky** [comment]
All the steps were successful: https://github.com/Drjacky/Avocado/actions/runs/7709702259

When I changed pre-release to release on Github Release section, it tried to build and publish the plugin but I got: https://github.com/Drjacky/Avocado/actions/runs/7709858760/job/21011916928


@hsz

**Comment by Drjacky** [comment]
And PUBLISH_TOKEN is provided!
<img width="221" alt="Screenshot 2024-01-30 at 10 46 00" src="https://github.com/JetBrains/gradle-intellij-plugin/assets/2296754/01070a5c-ee12-4b18-aa7f-ebff1d4569b9">

Should I have it in the Variables and not in the Secrets?

**Comment by Drjacky** [comment]
It must be in the Secrets:
<img width="378" alt="Screenshot 2024-01-30 at 11 39 39" src="https://github.com/JetBrains/gradle-intellij-plugin/assets/2296754/86e4e417-0a65-4087-93a5-f2e2c3d67978">

which mine is. but still get the [error](https://github.com/Drjacky/Avocado/actions/runs/7709858760/job/21014037531) on publishing task!
