### ISSUE TITLE
2.0 - intellijPlatform in settings plugin tries to access project instance

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/gradle-intellij-plugin#1548]
### What happened?

```kotlin
// myRepos.settings.gradle.kts
import org.jetbrains.intellij.platform.gradle.extensions.intellijPlatform

plugins {
    id("org.jetbrains.intellij.platform.settings")
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven(url = "https://oss.sonatype.org/content/repositories/snapshots")
        maven(url = "https://s01.oss.sonatype.org/content/repositories/snapshots")

        intellijPlatform {
            defaultRepositories()
        }
    }
}
```

### Relevant log output or stack trace

```shell
Caused by: java.lang.IllegalStateException: The root project is not yet available for build.
	at org.gradle.invocation.DefaultGradle.getRootProject(DefaultGradle.java:258)
	at org.gradle.invocation.DefaultGradle_Decorated.getRootProject(Unknown Source)
	at org.gradle.invocation.DefaultGradle.getRootProject(DefaultGradle.java:82)
	at org.jetbrains.intellij.platform.gradle.extensions.ExtensionsKt.getProjectCacheDirectory(extensions.kt:84)
	at org.jetbrains.intellij.platform.gradle.extensions.ExtensionsKt.getLocalPlatformArtifacts(extensions.kt:98)
	at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformRepositoriesExtension$localPlatformArtifacts$2.execute(IntelliJPlatformRepositoriesExtension.kt:182)
	at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformRepositoriesExtension$localPlatformArtifacts$2.execute(IntelliJPlatformRepositoriesExtension.kt:180)
	at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.addRepository(DefaultArtifactRepositoryContainer.java:88)
	at org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.ivy(DefaultRepositoryHandler.java:172)
	at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformRepositoriesExtension.localPlatformArtifacts(IntelliJPlatformRepositoriesExtension.kt:180)
	at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformRepositoriesExtension.localPlatformArtifacts$default(IntelliJPlatformRepositoriesExtension.kt:180)
	at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformRepositoriesExtension.defaultRepositories(IntelliJPlatformRepositoriesExtension.kt:216)
	at MyRepos_settings_gradle$2$1$1.execute(myRepos.settings.gradle.kts:15)
```

### Steps to reproduce

1. Check out https://github.com/hfhbd/kobol/tree/intellij-2.0.0
2. `./gradlew :help`

### Gradle IntelliJ Plugin version

2.0.0

### Gradle version

8.6

### Operating System

Linux

**Comment by hsz** [comment]
Thank you, Philip!
What is interesting is that I already did exactly the same migration on my local. :D
I merged your PR and apply some of my changes on the top.

And huge thanks for introducing `setUrl` in `localPlatformArtifacts`. I didn't know how to overcome that. Phew...

**Comment by hsz** [comment]
Actually, dropping the Windows hack causes an incorrect resolution of IntelliJ Platform artifact jars resolution:

```
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find /Users/Jakub/IdeaProjects/gradle-intellij-plugin/build/testGradleHome/caches/transforms-4/b8a57bf475be876f09aa912ae7588f55/transformed/IC-2022.3.3/plugins/copyright/lib/copyright.jar-2022.3.3+550.jar (bundledPlugin:com.intellij.copyright:2022.3.3+550).
     Searched in the following locations:
         file:/C:/Users/Jakub/AppData/Local/Temp/tmp101707438565585168/.intellijPlatform/localPlatformArtifacts/bundledPlugin/com.intellij.copyright/2022.3.3+550/Users/Jakub/IdeaProjects/gradle-intellij-plugin/build/testGradleHome/caches/transforms-4/b8a57bf475be876f09aa912ae7588f55/transformed/IC-2022.3.3/plugins/copyright/lib/copyright.jar-2022.3.3+550.jar
         file:/C:/Users/Jakub/AppData/Local/Temp/tmp101707438565585168/Users/Jakub/IdeaProjects/gradle-intellij-plugin/build/testGradleHome/caches/transforms-4/b8a57bf475be876f09aa912ae7588f55/transformed/IC-2022.3.3/plugins/copyright/lib/copyright.jar
```

**Comment by hfhbd** [comment]
Hm, my PR did work on macOS, will test your branch on macOS and Windows too.
