### ISSUE TITLE
Plugin dependencies are not added transitively to test classpath

### ISSUE THREAD

**Issue by bjansen** [JetBrains/gradle-intellij-plugin#227]
I have a custom plugin which depends on the `Spring` plugin:

```groovy
    intellij {
...
        plugins = ['Spring']
    }

```

My `plugin.xml` declares an optional dep to the the plugin (although I'm not sure it's relevant to the issue):

```xml
<depends optional="true">com.intellij.spring</depends>
```

When I run unit tests with Gradle, I get the following error:

```
ERROR: Problems found loading plugins:<p/>Plugin "Spring Support" was not loaded: required plugin "com.intellij.java-i18n" not installed.<p/><br><a href="disable">Disable Spring Support</a><p/><a href="edit">Open plugin manager</a>
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.ide.plugins.PluginManagerCore.b(PluginManagerCore.java:556)
	at com.intellij.ide.plugins.PluginManagerCore.b(PluginManagerCore.java:1202)
	at com.intellij.ide.plugins.PluginManagerCore.a(PluginManagerCore.java:1362)
	at com.intellij.ide.plugins.PluginManagerCore.getPlugins(PluginManagerCore.java:122)
	at com.intellij.ide.plugins.PluginManagerCore.getPlugins(PluginManagerCore.java:116)
	at com.intellij.idea.IdeaApplication.getStarter(IdeaApplication.java:188)
	at com.intellij.idea.IdeaApplication.<init>(IdeaApplication.java:114)
	at com.intellij.openapi.application.impl.ApplicationImpl.<init>(ApplicationImpl.java:218)
	at com.intellij.openapi.application.ex.ApplicationManagerEx.createApplication(ApplicationManagerEx.java:45)
	at com.intellij.idea.CommandLineApplication.<init>(CommandLineApplication.java:45)
	at com.intellij.idea.CommandLineApplication.<init>(CommandLineApplication.java:38)
	at com.intellij.idea.IdeaTestApplication.<init>(IdeaTestApplication.java:32)
	at com.intellij.idea.IdeaTestApplication.getInstance(IdeaTestApplication.java:52)
	at com.intellij.idea.IdeaTestApplication.getInstance(IdeaTestApplication.java:46)
	at com.intellij.testFramework.LightPlatformTestCase.initApplication(LightPlatformTestCase.java:167)
	at com.intellij.testFramework.fixtures.impl.LightIdeaTestFixtureImpl.setUp(LightIdeaTestFixtureImpl.java:48)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.b(CodeInsightTestFixtureImpl.java:1157)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:27)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:58)
	at com.intellij.testFramework.EdtTestUtil$Companion.runInEdtAndWait(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil.runInEdtAndWait(EdtTestUtil.kt)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.setUp(CodeInsightTestFixtureImpl.java:1156)
	at com.intellij.testFramework.fixtures.LightCodeInsightFixtureTestCase.setUp(LightCodeInsightFixtureTestCase.java:113)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:353)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:27)
	at com.intellij.testFramework.EdtTestUtilKt$runInEdtAndWait$2.run(EdtTestUtil.kt:62)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:345)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

If I add these transitive deps manually to my build file, the tests work again:

    plugins = ['Spring', 'java-i18n', 'properties']

The first test that fails is a `LightCodeInsightFixtureTestCase` (with the error above), then all the following tests fail because the project/application is not correctly initialized:

```
java.lang.NullPointerException
	at com.intellij.openapi.application.impl.ApplicationImpl.isDispatchThread(ApplicationImpl.java:388)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:38)
	at com.intellij.testFramework.EdtTestUtil$Companion.runInEdtAndWait(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil.runInEdtAndWait(EdtTestUtil.kt)
	at com.intellij.testFramework.UsefulTestCase.runBare(UsefulTestCase.java:413)
```

**Comment by zolotov** [comment]
No ideas. Are you sure that after adding `plugins = ['Spring', 'java-i18n', 'properties']` you have the very same error message?

**Comment by zolotov** [comment]
What version do you use?

**Comment by JakeWharton** [comment]
Dupe of https://github.com/JetBrains/gradle-intellij-plugin/issues/38

**Comment by bjansen** [comment]
@zolotov as I said, once I list all the transitive dependencies, the tests work again. I use the version 0.2.17, [here's my full build file](https://github.com/bjansen/pebble-intellij/blob/3aaadad0c4ea753a0580d01b696637ee0f8f4585/build.gradle)

@JakeWharton you're right, I searched for the error message and your issue didn't show up, sorry for the duplicate :) I'm closing this one.

**Comment by zolotov** [comment]
I see, thanks. I misinterpreted the initial request. Yes, transition dependencies of plugins are not supported
