### ISSUE TITLE
Unable to run samples locally.

### ISSUE THREAD

**Issue by JakeWharton** [JetBrains/gradle-intellij-plugin#255]
Commit ea1699e, in the `examples/` directory running `./gradlew build` produces:
```
Caused by: java.net.MalformedURLException: no protocol: /files/6954/31339/kotlin-plugin-1.0.6-release-IJ2016.3-1.zip?updateId=31339&pluginId=6954
        at retrofit.client.UrlConnectionClient.openConnection(UrlConnectionClient.java:43)
        at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:36)
        at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.downloadFile(pluginRepositoryRest.kt:154)
        at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.download(pluginRepositoryRest.kt:121)
        at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance$download.call(Unknown Source)
        at org.jetbrains.intellij.dependency.PluginDependencyManager.downloadPlugin(PluginDependencyManager.groovy:131)
        at org.jetbrains.intellij.dependency.PluginDependencyManager.resolve(PluginDependencyManager.groovy:60)
        at org.jetbrains.intellij.dependency.PluginDependencyManager$resolve.call(Unknown Source)
        at org.jetbrains.intellij.dependency.PluginDependencyManager$resolve.call(Unknown Source)
        at org.jetbrains.intellij.IntelliJPlugin$_configurePluginDependencies_closure7.doCall(IntelliJPlugin.groovy:206)
        at org.jetbrains.intellij.IntelliJPlugin.configurePluginDependencies(IntelliJPlugin.groovy:190)
        at org.jetbrains.intellij.IntelliJPlugin.configureProjectAfterEvaluate(IntelliJPlugin.groovy:100)
        at org.jetbrains.intellij.IntelliJPlugin$_configureTasks_closure2.doCall(IntelliJPlugin.groovy:87)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        ... 88 more
```

**Comment by JakeWharton** [comment]
I can't tell if it's a problem with this Gradle plugin or inside `plugin-repository-rest-client`. Figured I'd start here.

**Comment by zolotov** [comment]
Do you use 3.0-snapshot?

**Comment by JakeWharton** [comment]
Hmm 3.0 of what? All I did was clone this repo, cd into examples, and run a build.

**Comment by zolotov** [comment]
Oh, got it. I’ll check

**Comment by JakeWharton** [comment]
Some of the examples do build. Looks like this failure is in the `plugin-with-dependencies` one. I can get `kotlin-plugin` to work using `./gradlew --configure-on-demand :kotlin-plugin:build`, for example.

**Comment by zolotov** [comment]
it was an issue of plugins repository. should work now
