### ISSUE TITLE
NoClassDefFoundError when execute task "instrumentCode" with SDK 182+

### ISSUE THREAD

**Issue by tangzx** [JetBrains/gradle-intellij-plugin#290]
I got this error when build my plugin with SDK `IC_182.2371.4`

```
Execution failed for task ':EmmyLua:instrumentCode'.
> java.lang.NoClassDefFoundError: com/jgoodies/forms/layout/CellConstraints$Alignment
```

After some researching, I found that `jgoodies-forms.jar` had been renamed to `forms-1.1-preview.jar` in `IC_182.2371.4`.
I copied `jgoodies-forms.jar` from `IC_181.4445.78`/`lib` to `IC_182.2371.4`/`lib` and rebuild, it working!

https://github.com/JetBrains/gradle-intellij-plugin/blob/5b6c26f9b9779b54ba1426d195c482672c48835e/src/main/groovy/org/jetbrains/intellij/tasks/IntelliJInstrumentCodeTask.groovy#L59-L63

hope these infos useful

**Comment by Eskibear** [comment]
Got the same error. A private issue was opened with detailed log files in Youtrack [HERE](https://youtrack.jetbrains.com/issue/IDEA-192497),  but I got no response.
Thank you @tangzx , your workaround solution possibly works for me, let me have a try. 

### Details in [IDEA-192497](https://youtrack.jetbrains.com/issue/IDEA-192497):

We build IntelliJ IDEA plugin using `gradle-intellij-plugin`. Error occurs when we specify the EAP version.

Error `java.lang.NoClassDefFoundError: com/jgoodies/forms/layout/CellConstraints$Alignment`  occurs in `:instrumentCode` stage.

In `builld.gradle`:
```
intellij {
    pluginName 'azure-toolkit-for-intellij'
    version intellij_version
    plugins = ['maven', dep_plugins]
    downloadSources Boolean.valueOf(sources)
}
```

In `gradle.properties`:
```
javaVersion=1.8
org.gradle.jvmargs='-Duser.language=en'
sources=false
intellij_version=IC-182.2574.2
dep_plugins=org.intellij.scala:2018.2.1
```

Log:
```
This is an unexpected error. Please file a bug containing the idea.log file. 
com.intellij.openapi.externalSystem.model.ExternalSystemException: Unable to load class 'com.jgoodies.forms.layout.CellConstraints$Alignment'.

This is an unexpected error. Please file a bug containing the idea.log file.
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionErrorHandler.createUserFriendlyError(GradleExecutionErrorHandler.java:155)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectImportErrorHandler.createUserFriendlyError(AbstractProjectImportErrorHandler.java:46)
	at org.jetbrains.plugins.gradle.service.project.BaseProjectImportErrorHandler.getUserFriendlyError(BaseProjectImportErrorHandler.java:125)
	at org.jetbrains.plugins.gradle.service.project.BaseGradleProjectResolverExtension.getUserFriendlyError(BaseGradleProjectResolverExtension.java:663)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:150)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:150)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:150)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:150)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:150)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:150)
	at org.jetbrains.plugins.gradle.service.project.JavaGradleProjectResolver.getUserFriendlyError(JavaGradleProjectResolver.java:94)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:150)
	at org.jetbrains.plugins.gradle.service.task.GradleTaskManager.lambda$executeTasks$0(GradleTaskManager.java:135)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.execute(GradleExecutionHelper.java:209)
	at org.jetbrains.plugins.gradle.service.task.GradleTaskManager.executeTasks(GradleTaskManager.java:138)
	at org.jetbrains.plugins.gradle.service.task.GradleTaskManager.executeTasks(GradleTaskManager.java:59)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemTaskManagerImpl.a(RemoteExternalSystemTaskManagerImpl.java:48)
	at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:58)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemTaskManagerImpl.executeTasks(RemoteExternalSystemTaskManagerImpl.java:47)
	at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemTaskManagerWrapper.executeTasks(ExternalSystemTaskManagerWrapper.java:52)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemExecuteTaskTask.doExecute(ExternalSystemExecuteTaskTask.java:171)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:163)
	at com.intellij.openapi.externalSystem.service.execution.ExternalSystemRunConfiguration$MyRunnableState.a(ExternalSystemRunConfiguration.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Eskibear** [comment]
are you sure 0.3.3 is already published ?

```
* What went wrong:
Plugin [id: 'org.jetbrains.intellij', version: '0.3.3'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Gradle Central Plugin Repository (plugin 'org.jetbrains.intellij' has no version '0.3.3' - see https://plugins.gradle.org/plugin/org.jetbrains.intellij for available versions)
```

**Comment by Eskibear** [comment]
@zolotov 
Correct me if I'm wrong but I think in the [commit](https://github.com/EmmyLua/IntelliJ-EmmyLua/commit/2de1d890d5540bd32daaa84aab266ec20a7c1b5c) just put a self-built plugin dierectly in the repo. So why do you close this issue? Are you suggesting me to do the same thing as a workaround instead of resolving the issue here?

**Comment by Eskibear** [comment]
I didn't notice the commit https://github.com/JetBrains/gradle-intellij-plugin/commit/d5d41ee7d6531f817cd3d7a63eb7ac281b937e0d you pushed minutes ago. And it's not available in the official repo. 🤦‍♂️ 
Thanks for fixing it.

**Comment by zolotov** [comment]
@Eskibear all tests are passed, it will take couple more minutes to be uploaded to official repository

**Comment by zolotov** [comment]
Uploaded, sorry for waiting. The issue was closed automatically by commit message, way before tests and uploading are started.

**Comment by Eskibear** [comment]
Tested, it works now.

**Comment by tangzx** [comment]
Great! The funny things is I am waiting 0.3.3 these five days, in the sixth day, I cant wait, so I made the 0.3.3 by self 3 hours ago. and now the official 0.3.3 was released... hahahaha:smile:

**Comment by Eskibear** [comment]
@tangzx The same with you, just made a `0.4.0-SNAPSHOT` one day ago. 🤣
