### ISSUE TITLE
IDE Fatal Error in intellij 2018.2

### ISSUE THREAD

**Issue by lsikora** [JetBrains/gradle-intellij-plugin#305]
Thrown just after restart of IDE :
java.lang.AbstractMethodError: org.jetbrains.plugins.gradle.execution.build.output.GradleOutputParserProvider.getBuildOutputParsers(Lcom/intellij/openapi/externalSystem/model/task/ExternalSystemTask;)Ljava/util/List;
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:468)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$5.run(ExternalSystemUtil.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

IDE is running with embedded jre64. IDE build  #IU-182.3684.101 . JRE 1.8.0_152-release-1248-b8 amd64

**Comment by zolotov** [comment]
It's not an intellij repo, please file an issue at https://youtrack.jetbrains.com
