### ISSUE TITLE
Exception when using Java 10

### ISSUE THREAD

**Issue by raniejade** [JetBrains/gradle-intellij-plugin#307]
The kotlin plugin failed to load, error looks like Java 10ish. I'm confused, the IDE should be running the bundled jdk right?  

Building against: `2018.2`, kotlin `1.2.51` and Java 10.

```
Plugin 'org.jetbrains.kotlin' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: com/sun/jdi/ObjectCollectedException
    at com.intellij.debugger.settings.DebuggerSettings.loadState(DebuggerSettings.java:124)
    at com.intellij.debugger.settings.DebuggerSettings.loadState(DebuggerSettings.java:28)
    at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:356)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:312)
    at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:115)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:90)
    at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:15)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:212)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:247)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:214)
    at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:47)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:26)
    at com.intellij.debugger.settings.DebuggerSettings.getInstance(DebuggerSettings.java:97)
    at org.jetbrains.kotlin.idea.debugger.filter.DebuggerFiltersUtilKt.addKotlinStdlibDebugFilterIfNeeded(DebuggerFiltersUtil.kt:27)
    at org.jetbrains.kotlin.idea.JvmPluginStartupComponent.initComponent(JvmPluginStartupComponent.java:41)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:488)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:442)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:449)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:91)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:401)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:387)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:206)
    at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:72)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.sun.jdi.ObjectCollectedException
    at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:224)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 45 more
```

**Comment by zolotov** [comment]
Have you compiled the plugin with Java 10?

**Comment by raniejade** [comment]
I'm using Java 10 when compiling, it's all kotlin code btw and the target is set to `1.8`.

**Comment by zolotov** [comment]
Does disabling instrumenting code help?

**Comment by raniejade** [comment]
Disabled instrumentation still no luck. Different but related error now:

```
Plugin Error: Plugin 'org.jetbrains.kotlin' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: com/sun/jdi/Type
        at com.intellij.debugger.settings.DebuggerSettings.loadState(DebuggerSettings.java:124)
        at com.intellij.debugger.settings.DebuggerSettings.loadState(DebuggerSettings.java:28)
        at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:356)
        at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:312)
        at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:115)
        at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:90)
        at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:15)
        at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:212)
        at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:247)
        at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:214)
        at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:47)
        at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:26)
        at com.intellij.debugger.settings.DebuggerSettings.getInstance(DebuggerSettings.java:97)
        at org.jetbrains.kotlin.idea.debugger.filter.DebuggerFiltersUtilKt.addKotlinStdlibDebugFilterIfNeeded(DebuggerFiltersUtil.kt:27)
        at org.jetbrains.kotlin.idea.JvmPluginStartupComponent.initComponent(JvmPluginStartupComponent.java:41)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:488)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:107)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:442)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
        at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:449)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:91)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:401)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:387)
        at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:206)
        at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:72)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
        at java.awt.EventQueue.access$500(EventQueue.java:98)
        at java.awt.EventQueue$3.run(EventQueue.java:715)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.sun.jdi.Type
        at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:224)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 45 more

```

Everything runs ok in Java 8 tho, compilation works in Java 10 but the problem is when running `runIde`. I'm confused, it should use the bundled JDK right? Instead of the one used to run gradle.

**Comment by zolotov** [comment]
Yes, by default `runIde` uses bundled JDK to run

**Comment by raniejade** [comment]
I can confirm that the bundled jdk is being used,so I think some parts in IDEA uses the jdk in the environment. The kotlin plugin is not being loaded because of the exception.

**Comment by raniejade** [comment]
I think I know the problem. `..\jetbrains\jbre\jbrex8u152b1248.8_windows_x64\lib\tools.jar` should be `..\jetbrains\jbre\jbrex8u152b1248.8_windows_x64\jre\lib\tools.jar`. Offending line is https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/groovy/org/jetbrains/intellij/tasks/RunIdeTask.groovy#L132. It works On java 8 because of:

```
        def toolsJar = Jvm.current().toolsJar
        if (toolsJar != null) classpath += project.files(toolsJar)
```

The ff path is added to the cp when running java 8: `;D:\Program Files\Java\jdk1.8.0_151\lib\tools.jar;`. I think we shouldn't rely on the JVM that is used to run gradle.

**Comment by zolotov** [comment]
Nice catch! Thank you for the investigation. I think I'll be able to get into this in a week or so. 

Feel free to make a PR, I think I'll be able to review/merge/publish plugin using my phone :)

**Comment by raniejade** [comment]
Sure, I'll work on a PR. :)

**Comment by zolotov** [comment]
btw, 0.3.6 was published
