### ISSUE TITLE
runIde runs an IDE using JRE instead of JDK

### ISSUE THREAD

**Issue by scana** [JetBrains/gradle-intellij-plugin#312]
Hi, I'm running `0.3.6` version of the plugin and encountered the following error:
```
17:12:07: Executing task 'runIde'...

> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :patchPluginXml UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :instrumentCode UP-TO-DATE
> Task :postInstrumentCode
> Task :inspectClassesForKotlinIC UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :prepareSandbox UP-TO-DATE

> Task :runIde
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0

JDK Required: JDK classes seem to be not on IDEA classpath.
Please ensure you run the IDE on JDK rather than JRE.

> Task :runIde FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runIde'.
> Process 'command '/Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbrex8u152b1248.8_osx_x64/jdk/Contents/Home/jre/bin/java'' finished with non-zero exit value 4

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
9 actionable tasks: 2 executed, 7 up-to-date
Process 'command '/Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbrex8u152b1248.8_osx_x64/jdk/Contents/Home/jre/bin/java'' finished with non-zero exit value 4
17:12:18: Task execution finished 'runIde'.
```

More details, when running `./gradlew runIde --info` command:
```
> Task :runIde
Task ':runIde' is not up-to-date because:
  Task.upToDateWhen is false.
Starting process 'command '/Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbrex8u152b1248.8_osx_x64/jdk/Contents/Home/jre/bin/java''. Working directory: /Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/fcb66fea071aa9c4de3a607c505f61d29ac56d8e/ideaIC-LATEST-EAP-SNAPSHOT/bin Command: /Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbrex8u152b1248.8_osx_x64/jdk/Contents/Home/jre/bin/java -Dapple.awt.fileDialogForDirectories=true -Dapple.laf.useScreenMenuBar=true -Didea.classpath.index.enabled=false -Didea.config.path=/Users/scana/work/private/ok-gradle/build/idea-sandbox/config -Didea.is.internal=true -Didea.platform.prefix=Idea -Didea.plugins.path=/Users/scana/work/private/ok-gradle/build/idea-sandbox/plugins -Didea.required.plugins.id=me.scana.okgradle -Didea.smooth.progress=false -Didea.system.path=/Users/scana/work/private/ok-gradle/build/idea-sandbox/system -XX:MaxPermSize=250m -Xms256m -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbrex8u152b1248.8_osx_x64/jdk/Contents/Home/jre/lib/tools.jar:/Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/fcb66fea071aa9c4de3a607c505f61d29ac56d8e/ideaIC-LATEST-EAP-SNAPSHOT/lib/idea_rt.jar:/Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/fcb66fea071aa9c4de3a607c505f61d29ac56d8e/ideaIC-LATEST-EAP-SNAPSHOT/lib/idea.jar:/Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/fcb66fea071aa9c4de3a607c505f61d29ac56d8e/ideaIC-LATEST-EAP-SNAPSHOT/lib/bootstrap.jar:/Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/fcb66fea071aa9c4de3a607c505f61d29ac56d8e/ideaIC-LATEST-EAP-SNAPSHOT/lib/extensions.jar:/Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/fcb66fea071aa9c4de3a607c505f61d29ac56d8e/ideaIC-LATEST-EAP-SNAPSHOT/lib/util.jar:/Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/fcb66fea071aa9c4de3a607c505f61d29ac56d8e/ideaIC-LATEST-EAP-SNAPSHOT/lib/openapi.jar:/Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/fcb66fea071aa9c4de3a607c505f61d29ac56d8e/ideaIC-LATEST-EAP-SNAPSHOT/lib/trove4j.jar:/Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/fcb66fea071aa9c4de3a607c505f61d29ac56d8e/ideaIC-LATEST-EAP-SNAPSHOT/lib/jdom.jar:/Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/fcb66fea071aa9c4de3a607c505f61d29ac56d8e/ideaIC-LATEST-EAP-SNAPSHOT/lib/log4j.jar com.intellij.idea.Main
Successfully started process 'command '/Users/scana/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbrex8u152b1248.8_osx_x64/jdk/Contents/Home/jre/bin/java''
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0

JDK Required: JDK classes seem to be not on IDEA classpath.
Please ensure you run the IDE on JDK rather than JRE.
```

Am I doing anything wrong? Is there any way to point the plugin to run the IDE from a different SDK?
If anything, I'm using 2018.2 version of Intellij IDEA.

I would be grateful for any tips on this matter.

**Comment by zolotov** [comment]
> JDK Required: JDK classes seem to be not on IDEA classpath. Please ensure you run the IDE on JDK rather than JRE

This means that `tools.jar` is absent in the classpath. I think this is result of #309. @raniejade do you have any ideas about this?

**Comment by scana** [comment]
@zolotov oh, right - switching back to `0.3.5` solves the issue.

**Comment by raniejade** [comment]
Yeah, caused by my change. I'll look into it.

**Comment by zolotov** [comment]
@novotnyr what's the OS you use?

**Comment by novotnyr** [comment]
MacOS High Sierra 10.13.6

**Comment by zolotov** [comment]
@novotnyr please try 0.3.8

**Comment by novotnyr** [comment]
I have tried, but now it is failing in incompatible Gradle API. I have tried both Gradle 3.4.x and the 4.8.x.

```
Cannot cast object '[/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/tools.jar]' with class 'java.util.ArrayList' to class 'org.gradle.api.file.FileCollection' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.api.file.FileCollection(java.io.File)

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':runIde'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:256)
	at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:253)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:175)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:50)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:75)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '[/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/tools.jar]' with class 'java.util.ArrayList' to class 'org.gradle.api.file.FileCollection' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.api.file.FileCollection(java.io.File)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.setProperty(BeanDynamicObject.java:358)
	at org.gradle.internal.metaobject.BeanDynamicObject.setProperty(BeanDynamicObject.java:161)
	at org.gradle.internal.metaobject.CompositeDynamicObject.setProperty(CompositeDynamicObject.java:65)
	at org.gradle.internal.metaobject.AbstractDynamicObject.setProperty(AbstractDynamicObject.java:75)
	at org.jetbrains.intellij.tasks.RunIdeTask_Decorated.setProperty(Unknown Source)
	at org.jetbrains.intellij.tasks.RunIdeTask.configureClasspath(RunIdeTask.groovy:134)
	at org.jetbrains.intellij.tasks.RunIdeTask.exec(RunIdeTask.groovy:123)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 78 more
```

**Comment by zolotov** [comment]
@novotnyr ouch, sorry. 0.3.9 is on the way

**Comment by novotnyr** [comment]
Yes, works for me now. Thanks for quickfix!

**Comment by xuzhiyiYoh** [comment]
Hi~ all, I have some problems when I using toos.jar in my plugin.

**os version: macOS Mojave 10.14.1**
**java version "1.8.0_172"**

**`./gradlew runIde --info`**

```
Initialized native services in: /Users/letian/.gradle/native
Found daemon DaemonInfo{pid=59043, address=[de00b963-e7cf-4045-ae0f-f56ad193957c port:57590, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1559008898134, context=DefaultDaemonContext[uid=c1f4d535-9a40-4551-862c-7b2efe13e88d,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home,daemonRegistryDir=/Users/letian/.gradle/daemon,pid=59043,idleTimeout=10800000,daemonOpts=-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]} however its context does not match the desired criteria.
Java home is different.
Wanted: DefaultDaemonContext[uid=null,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home,daemonRegistryDir=/Users/letian/.gradle/daemon,pid=65467,idleTimeout=null,daemonOpts=-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]
Actual: DefaultDaemonContext[uid=c1f4d535-9a40-4551-862c-7b2efe13e88d,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home,daemonRegistryDir=/Users/letian/.gradle/daemon,pid=59043,idleTimeout=10800000,daemonOpts=-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]

  Looking for a different daemon...
The client will now receive all logging from the daemon (pid: 26350). The daemon log file: /Users/letian/.gradle/daemon/4.4/daemon-26350.out.log
Starting 49th build in daemon [uptime: 6 hrs 30 mins 2.718 secs, performance: 100%, no major garbage collections]
Using 4 worker leases.
Creating new cache for fileHashes, path /Users/letian/IdeaProjects/dtrace/.gradle/4.4/fileHashes/fileHashes.bin, access org.gradle.cache.internal.DefaultCacheAccess@153d45fc
Starting Build
Settings evaluated using settings file '/Users/letian/IdeaProjects/dtrace/settings.gradle'.
Projects loaded. Root project using build file '/Users/letian/IdeaProjects/dtrace/build.gradle'.
Included projects: [root project 'cn.xzy.dtrace']

> Configure project : 
Evaluating root project 'cn.xzy.dtrace' using build file '/Users/letian/IdeaProjects/dtrace/build.gradle'.
Creating new cache for metadata-1.1/results, path /Users/letian/.gradle/caches/transforms-1/metadata-1.1/results.bin, access org.gradle.cache.internal.DefaultCacheAccess@72c4a4af
Creating new cache for metadata-2.36/module-metadata, path /Users/letian/.gradle/caches/modules-2/metadata-2.36/module-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@2b9cd311
Creating new cache for metadata-2.36/module-artifacts, path /Users/letian/.gradle/caches/modules-2/metadata-2.36/module-artifacts.bin, access org.gradle.cache.internal.DefaultCacheAccess@2b9cd311
Creating new cache for metadata-2.36/module-artifact, path /Users/letian/.gradle/caches/modules-2/metadata-2.36/module-artifact.bin, access org.gradle.cache.internal.DefaultCacheAccess@2b9cd311
Configuring IntelliJ IDEA gradle plugin
Configuring patch plugin.xml task
Configuring prepare IntelliJ sandbox task
Configuring prepare IntelliJ sandbox task
Configuring plugin verification task
Configuring run IntelliJ task
Configuring build searchable options task
Configuring jar searchable options task
Configuring building IntelliJ IDEA plugin task
Configuring publishing IntelliJ IDEA plugin task
Configuring IntelliJ resources task
Configuring IntelliJ compile tasks
Configuring IntelliJ IDEA dependency
Using IDE from remote repository
IntelliJ IDEA dependency cache directory: /Users/letian/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2018.1.2/752dd984246060e700028040862adfd20620c6dc/ideaIC-2018.1.2
Adding IntelliJ IDEA sources repository
Configuring IntelliJ IDEA extra dependencies []
IntelliJ IDEA IC-181.4668.68 is used for building
Configuring IntelliJ IDEA plugin dependencies
Configuring IntelliJ tests tasks

All projects evaluated.
Selected primary task 'runIde' from project :
Creating new cache for annotation-processors, path /Users/letian/IdeaProjects/dtrace/.gradle/4.4/fileContent/annotation-processors.bin, access org.gradle.cache.internal.DefaultCacheAccess@2c660bc8
Tasks to be executed: [task ':compileJava', task ':patchPluginXml', task ':processResources', task ':classes', task ':instrumentCode', task ':postInstrumentCode', task ':jar', task ':prepareSandbox', task ':runIde']
Creating new cache for resourceHashesCache, path /Users/letian/IdeaProjects/dtrace/.gradle/4.4/fileHashes/resourceHashesCache.bin, access org.gradle.cache.internal.DefaultCacheAccess@153d45fc
Creating new cache for taskHistory, path /Users/letian/IdeaProjects/dtrace/.gradle/4.4/taskHistory/taskHistory.bin, access org.gradle.cache.internal.DefaultCacheAccess@3f69fd3b
Creating new cache for outputFiles, path /Users/letian/IdeaProjects/dtrace/.gradle/buildOutputCleanup/outputFiles.bin, access org.gradle.cache.internal.DefaultCacheAccess@63799cc1
:compileJava (Thread[Task worker for ':',5,main]) started.

> Task :compileJava FAILED
Putting task artifact state for task ':compileJava' into context took 0.0 secs.
Deleting stale output file: /Users/letian/IdeaProjects/dtrace/build/classes/java/main
Up-to-date check for task ':compileJava' took 0.082 secs. It is not up-to-date because:
  Task has failed previously.
All input files are considered out-of-date for incremental task ':compileJava'.
Compiling with JDK Java compiler API.
/Users/letian/IdeaProjects/dtrace/src/main/java/com/intellij/debugger/impl/DtraceDebuggerRunner.java:28: 错误: 程序包com.sun.jdi不存在
import com.sun.jdi.VirtualMachine;
                  ^
/Users/letian/IdeaProjects/dtrace/src/main/java/com/intellij/debugger/impl/DtraceDebuggerRunner.java:91: 错误: 找不到符号
        VirtualMachine virtualMachine = debuggerSession.getProcess().getVirtualMachineProxy().getVirtualMachine();
        ^
  符号:   类 VirtualMachine
  位置: 类 DtraceDebuggerRunner
2 个错误

:compileJava (Thread[Task worker for ':',5,main]) completed. Took 0.57 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

**bulid.gradle**

```
plugins {
    id 'java'
    id 'org.jetbrains.intellij' version '0.4.8'
}

group 'org.jetbrains.intellij'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

intellij {
    version '2018.1.2'
}
patchPluginXml {
    changeNotes """
      Add change notes here.<br>
      <em>most HTML tags may be used</em>"""
}
```

**Comment by xuzhiyiYoh** [comment]
@zolotov Do you have some idea to fix it ? Thanks a million.

**Comment by zolotov** [comment]
@xuzhiyiYoh it's not the same problem as you have it in compile time. JRE is not used for compilation, it's just impossible. Also, gradle-intellij-plugin doesn't compile your plugin, java-plugin does and it's on you to provide all required dependencies, including `tools.jar`.

**Comment by xuzhiyiYoh** [comment]
Add Gradle VM options:
```
-Xbootclasspath/a:/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/lib/tools.jar
```
Works well~
