### ISSUE TITLE
Form binding not working (NPE)

### ISSUE THREAD

**Issue by leinardi** [JetBrains/gradle-intellij-plugin#314]
I am trying to use the `gradle-intellij-plugin` on one of my projects, [pylint-PyCharm-plugin](https://github.com/leinardi/pylint-PyCharm-plugin), but I am stuck because the form bindings seems to not work.

I always get a NPE as soon as the UI is loaded:

```
failed to init toolwindow com.leinardi.plugins.pylint_plugin.PylintToolWindowFactory

java.lang.NullPointerException
	at com.leinardi.plugins.pylint_plugin.PylintTerminal.initUI(PylintTerminal.java:105)
	at com.leinardi.plugins.pylint_plugin.PylintToolWindowFactory.createToolWindowContent(PylintToolWindowFactory.java:21)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:512)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.lambda$initToolWindow$10(ToolWindowManagerImpl.java:523)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.initToolWindow(ToolWindowManagerImpl.java:526)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$5.run(ToolWindowManagerImpl.java:478)
	at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
	at com.intellij.openapi.wm.impl.CommandProcessor.flush(CommandProcessor.java:32)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.flushCommands(ToolWindowManagerImpl.java:609)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.access$2900(ToolWindowManagerImpl.java:76)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$InitToolWindowsActivity.lambda$runActivity$0(ToolWindowManagerImpl.java:2299)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:864)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:205)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:588)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:250)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:203)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectUnderProgress(ProjectManagerImpl.java:439)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:414)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:245)
	at com.intellij.ide.RecentProjectsManagerBase.doOpenProject(RecentProjectsManagerBase.java:579)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:706)
	at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:748)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:376)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:357)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:208)
	at com.sun.proxy.$Proxy46.appStarting(Unknown Source)
	at com.intellij.idea.IdeaApplication$IdeStarter.lambda$main$1(IdeaApplication.java:374)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:372)
	at com.intellij.idea.IdeaApplication.lambda$run$1(IdeaApplication.java:212)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:212)
	at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:75)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
The line 105 is [this one](https://github.com/leinardi/pylint-PyCharm-plugin/blob/master/pylint-plugin/src/com/leinardi/plugins/pylint_plugin/PylintTerminal.java#L105) where errorList is declared as `JBList<PylintViolation> errorsList;`. I also tried to change the scope of the variable to public, but the result is the same.

This is the content of the `build.gradle`:

```
plugins {
    id 'org.jetbrains.intellij' version '0.3.7'
}

group 'com.leinardi.plugins'
version '0.1.0'

apply plugin: "org.jetbrains.intellij"

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

intellij {
    localPath '/home/leinardi/pycharm-community-2018.1.3'
}
patchPluginXml {
    changeNotes """
      Add change notes here.<br>
      <em>most HTML tags may be used</em>"""
}
```

I just copy/pasted all the sources and resources inside the `src/main` directory. No errors are shown during build and the plugin is imported correctly.

I also double checked the `bind to class` property and re-assigned it using the Browse feature:
![image](https://user-images.githubusercontent.com/273338/44491488-b7c54f00-a661-11e8-9ec4-e75f55d2ceae.png)

I get the NPE using the `buildPlugin` task and importing the jar manually to PyCharm or just pressing the green play button and running the plugin on the sandbox PyCharm.

The same exact code works correctly if I don't use gradle but just use the Build -> Prepare Plugin Module for Deployment feature.

**Comment by zolotov** [comment]
```

intellij {
    localPath '/home/leinardi/pycharm-community-2018.1.3'
}
```

You cannot use PyCharm for compilation forms, it doesn't contain java compiler inside

**Comment by leinardi** [comment]
Hi @zolotov, thank you for your answer.

There is still something not clear to me, since the plugin is already working on PyCharm, including the forms on the master branch, where I don't use Gradle:

![image](https://user-images.githubusercontent.com/273338/44509164-1fef5180-a6b1-11e8-98dc-b26663d0b4ad.png)

So the issue seems to happen only if I use the Gradle plugin to build.

In the hope that can be useful, I pushed the branch I am using to migrate the project to Gradle: https://github.com/leinardi/pylint-PyCharm-plugin/tree/gradle.

Can you please have another look at this issue?

**Comment by zolotov** [comment]
> There is still something not clear to me, since the plugin is already working on PyCharm, including the forms on the master branch, where I don't use Gradle

Becuase there you compile it with IDEA, which contains javac2 that is able to compile forms

**Comment by leinardi** [comment]
I see. Sorry for the silly questions but I am new to plugin development: is there a way to use Gradle and keep the forms or the only way to support PyCharm is to declare all the UI programmatically?

**Comment by zolotov** [comment]
For forms instrumentation you should use IntelliJ for compiling using `version` or `localPath` to IntelliJ installation. Running PyCharm is possible with `alternativeIdePath` option.

**Comment by leinardi** [comment]
Thanks! I will try this evening and let you know.

**Comment by leinardi** [comment]
Hey it seems to work! Thanks!

I had to do these changes:

```
intellij {
//    localPath '/home/leinardi/pycharm-community-2018.1.3'
    version = 'IC-2018.2'
    alternativeIdePath = '/home/rleinardi/pycharm-community'
}
```

```
    <!-- please see http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html
         on how to target different products -->
    <!-- uncomment to enable plugin in all products -->
    <depends>com.intellij.modules.lang</depends>
    <!--<depends>com.intellij.modules.python</depends>-->
```
I commented the `com.intellij.modules.python` because it was not being resolved without using PyCharm as `localPath`, but I noticed that it builds anyway. Is that mark the plugin as a PyCharm only? Is it ok to leave it even if is not resolved?
![image](https://user-images.githubusercontent.com/273338/44513169-e4f31b00-a6bc-11e8-82cf-b4f60f8a9a87.png)
