### ISSUE TITLE
'Permission denied' when running :prepareSandbox a second time

### ISSUE THREAD

**Issue by hmemcpy** [JetBrains/gradle-intellij-plugin#344]
I'm using the following in the build file:
```gradle
...
intellij {
    version '2018.3.2'
    plugins 'com.google.idea.bazel.ijwb:2018.12.03.0.2'
}
```
This adds [Bazel plugin](https://plugins.jetbrains.com/plugin/8609-bazel) support in the sandboxed IntelliJ.
It works great the first time, the plugin zip is downloaded, and extracted to the sandbox directory. 

Unfortunately, after making some change, trying to run the plugin again causes the `:prepareSandbox` step to fail with the following:
```
* What went wrong:
Execution failed for task ':prepareSandbox'.
> Could not copy file '/Users/<usr>/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins/com.google.idea.bazel.ijwb-2018.12.03.0.2/ijwb/lib/ijwb_bazel.jar' to '/Users/<usr>/code/permissions-bug/build/idea-sandbox/plugins/ijwb/lib/ijwb_bazel.jar'.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':prepareSandbox'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        ...
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Could not copy file '/Users/<usr>/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/unzipped.com.jetbrains.plugins/com.google.idea.bazel.ijwb-2018.12.03.0.2/ijwb/lib/ijwb_bazel.jar' to '/Users/<usr>/code/permissions-bug/build/idea-sandbox/plugins/ijwb/lib/ijwb_bazel.jar'.
	at org.gradle.api.internal.file.AbstractFileTreeElement.copyTo(AbstractFileTreeElement.java:79)
	at org.gradle.api.internal.file.copy.DefaultFileCopyDetails.copyTo(DefaultFileCopyDetails.java:111)
	at org.gradle.api.internal.file.copy.FileCopyAction$FileCopyDetailsInternalAction.processFile(FileCopyAction.java:44)
        ...
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 31 more
Caused by: java.io.FileNotFoundException: /Users/<usr>/code/permissions-bug/build/idea-sandbox/plugins/ijwb/lib/ijwb_bazel.jar (Permission denied)
	at org.gradle.api.internal.file.AbstractFileTreeElement.copyFile(AbstractFileTreeElement.java:91)
	at org.gradle.api.internal.file.AbstractFileTreeElement.copyTo(AbstractFileTreeElement.java:74)
	... 79 more
```

Running `ls -al` on the target directory shows me:
```
-r-xr-xr-x  1 <usr>  MYDOMAIN\Domain Users   7.5M Dec 24 10:22 ijwb_bazel.jar
```

Compared to other plugins, this seems to be missing the `w` permission on all files.

**Comment by zolotov** [comment]
> Compared to other plugins, this seems to be missing the w permission on all files.

It's worth to ask Bazel team why they do this.

What do you suggest to change in `gradle-intellij-plugin`?

**Comment by hmemcpy** [comment]
I'm not sure they're aware of any problem, to be honest...
I wasn't (yet) able to debug the `gradle-intellij-plugin` to understand how `:prepareSandbox` worked, I imagine it tries to unzip the downloaded plugins to the sandbox directory. I wonder if there could be an additional step performed for (re)setting file permissions.

I currently "worked around" the problem by creating a "Before launch" task, calling `rm -rf` on the sandboxed `ijwb` directory.

Is there an easy way I could step through the task in the debugger? Is there an equivalent of `:runIde` for the gradle plugin? Or manually attach sources to an existing installation?

**Comment by zolotov** [comment]
> I'm not sure they're aware of any problem, to be honest...

You can report it to them. I think it might lead to problems on the production as well. Probably, IDE won't be able to upgrade or delete the plugin.

> Is there an easy way I could step through the task in the debugger?

Clone the repo, choose any of the project in `examples/` directory, change it as you need and debug its `:runIde` task. Debugger will be able to stop at breakpoints in `gradle-intellij-plugin` sources.

**Comment by hmemcpy** [comment]
I'm suddenly not sure it has anything to do with write access, but I'll try to repro this and see if I can pintpoint the problem. Thanks for the debugging instructions!

**Comment by zolotov** [comment]
closing due to lack of feedback. feel free to add details and I'll reopen the issue

**Comment by tharakadesilva** [comment]
Hi, @zolotov I am seeing this issue, what information can I gather to help you?
