### ISSUE TITLE
java.lang.AssertionError 	at org.jetbrains.plugins.gradle.config.GradleResourceCompilerConfigurationGenerator.generateAffectedGradleModulesConfiguration(GradleResourceCompilerConfigurationGenerator.java:186)

### ISSUE THREAD

**Issue by MichaelShumenko** [JetBrains/gradle-intellij-plugin#350]
Could you please assist why is this may happen?

```
2019-01-10 00:39:27,958 [ 751254]   INFO - g.FileBasedIndexProjectHandler - Has changed files: false; project=Project '/home/msh/IdeaProjects/google-cloud-intellij' google-cloud-intellij 
2019-01-10 00:39:27,988 [ 751284]   INFO - j.ide.ui.OptionsTopHitProvider - 26 ms spent to cache options in project 
2019-01-10 00:39:27,990 [ 751286]   INFO - cloudConfig.CloudConfigManager - === StatusBar ignored === 
2019-01-10 00:39:28,249 [ 751545]  DEBUG - lij.tasks.impl.TaskManagerImpl - Updating issues cache (every 20 min) 
2019-01-10 00:39:28,388 [ 751684]   INFO - j.ide.ui.OptionsTopHitProvider - 140 ms spent on EDT to cache options in project 
2019-01-10 00:41:20,330 [ 863626]   INFO - ij.compiler.impl.CompileDriver - COMPILATION STARTED (BUILD PROCESS) 
2019-01-10 00:41:20,331 [ 863627]  ERROR - ij.compiler.impl.CompileDriver - null 
java.lang.AssertionError
	at org.jetbrains.plugins.gradle.config.GradleResourceCompilerConfigurationGenerator.generateAffectedGradleModulesConfiguration(GradleResourceCompilerConfigurationGenerator.java:186)
	at org.jetbrains.plugins.gradle.config.GradleResourceCompilerConfigurationGenerator.generateBuildConfiguration(GradleResourceCompilerConfigurationGenerator.java:113)
	at org.jetbrains.plugins.gradle.startup.GradleJvmStartupActivity$1.lambda$execute$0(GradleJvmStartupActivity.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:948)
	at org.jetbrains.plugins.gradle.startup.GradleJvmStartupActivity$1.execute(GradleJvmStartupActivity.java:52)
	at com.intellij.compiler.impl.CompileDriver.a(CompileDriver.java:592)
	at com.intellij.compiler.impl.CompileDriver.a(CompileDriver.java:410)
	at com.intellij.compiler.progress.CompilerTask.run(CompilerTask.java:185)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by zolotov** [comment]
Please use https://youtrack.jetbrains.com for reporting any problems regarding gradle support in IntelliJ. This repo is about plugin for Gradle itself.
