### ISSUE TITLE
Cannot change dependencies of configuration ':runtimeOnly' after it has been included in dependency resolution

### ISSUE THREAD

**Issue by nbransby** [JetBrains/gradle-intellij-plugin#364]
Ive added a proguard task to my gradle file which includes:

`    libraryjars configurations.runtimeClasspath.getFiles().findAll(exclude)`

It appears use of runtimeClasspath causes this error on gradle sync:

```
org.gradle.api.InvalidUserDataException: Cannot change dependencies of configuration ':runtimeOnly' after it has been included in dependency resolution.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.preventIllegalMutation(DefaultConfiguration.java:875)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:837)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$2.execute(DefaultConfiguration.java:257)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$2.execute(DefaultConfiguration.java:254)
	at org.gradle.internal.ImmutableActionSet$SingletonSet.execute(ImmutableActionSet.java:155)
	at org.gradle.api.internal.DefaultDomainObjectCollection.assertMutable(DefaultDomainObjectCollection.java:320)
	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:197)
	at org.gradle.api.internal.DelegatingDomainObjectSet.add(DelegatingDomainObjectSet.java:82)
	at org.gradle.api.internal.artifacts.DefaultDependencySet.add(DefaultDependencySet.java:63)
	at org.gradle.api.internal.artifacts.DefaultDependencySet.add(DefaultDependencySet.java:33)
	at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.doAdd(DefaultDependencyHandler.java:113)
	at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.add(DefaultDependencyHandler.java:88)
	at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.add(DefaultDependencyHandler.java:83)
	at org.gradle.api.artifacts.dsl.DependencyHandler$add$0.call(Unknown Source)
	at org.jetbrains.intellij.IntelliJPlugin.configureIntellijDependency(IntelliJPlugin.groovy:191)
	at org.jetbrains.intellij.IntelliJPlugin.configureProjectAfterEvaluate(IntelliJPlugin.groovy:113)
	at org.jetbrains.intellij.IntelliJPlugin$_configureTasks_closure2.doCall(IntelliJPlugin.groovy:98)
```

**Comment by nbransby** [comment]
I solved it with `libraryjars "${->configurations.runtimeClasspath.getFiles().findAll(exclude)}"
`

**Comment by nbransby** [comment]
Ok it works but runtimeClasspath does not include the intellij runtime - how do I get that included?

**Comment by nbransby** [comment]
Can you help @zolotov ?

**Comment by zolotov** [comment]
@nbransby I have no idea what `libraryjars` is and what you're trying to achieve. What I can say is that you should not resolve runtime classpath on the configuration time.

**Comment by nbransby** [comment]
@zolotov `libraryjars` is the way to specify the runtime to proguard via its gradle plugin so

`libraryjars "${System.getProperty('java.home')}/lib/rt.jar"`

Would add the java runtime so proguard can resolve the classes used. My question is how to get the list of intellij platform jars in gradle so I can add it to the proguard config. Im assuming they get linked in automatically by the gradle-intellij-plugin as they don't appear external libraries list in intellij.

Any pointers would be a great help. Additional do you know of any open source plugins using proguard?

**Comment by zolotov** [comment]
> My question is how to get the list of intellij platform jars in gradle so I can add it to the proguard config.

You can take it from the IDE directory or from compile classpath.

> Im assuming they get linked in automatically by the gradle-intellij-plugin as they don't appear external libraries list in intellij.

They do appear in external libraries list in intellij.
