### ISSUE TITLE
buildSearchableOptions fails with Idea version 2019.1 and java 11

### ISSUE THREAD

**Issue by nehashri** [JetBrains/gradle-intellij-plugin#382]
I get the following error when running with 
Intellij Idea 2019.1, 
gradle version 5.3.1  
Java version 11
org.jetbrains.intellij plugin 0.4.7

Error 
```
$ ./gradlew clean buildPlugin

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :buildSearchableOptions

Plugin Error: Plugin 'com.thoughtworks.gauge' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

com.intellij.diagnostic.PluginException: While loading class com.thoughtworks.gauge.settings.GaugeSettingsService: com/thoughtworks/gauge/settings/GaugeSettingsService has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 [Plugin: com.thoughtworks.gauge]
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:185)
        at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:136)
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:49)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:367)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:81)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:407)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:393)
        at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
        at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
        at java.awt.EventQueue.access$500(EventQueue.java:98)
        at java.awt.EventQueue$3.run(EventQueue.java:715)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:347)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.UnsupportedClassVersionError: com/thoughtworks/gauge/settings/GaugeSettingsService has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
        at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:306)
        at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:302)
        at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:271)
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:182)
        ... 26 more


> Task :buildSearchableOptions FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSearchableOptions'.
> Process 'command '/Users/user/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbrx-8u202-osx-x64-b1483.39/jdk/Contents/Home/jre/bin/java'' finished with non-zero exit value 8

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
9 actionable tasks: 9 executed
```

The same seems to work with Intellij version 2018. (183.*)

**Comment by zolotov** [comment]
> Caused by: java.lang.UnsupportedClassVersionError: com/thoughtworks/gauge/settings/GaugeSettingsService has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0


Apparently, you're trying to run your Java 11 plugin on IDEA with bundled Java 8 JRE. I don't see how it's related to building searchable options. What's your build.gradle look like? How do you usually run the plugin?

**Comment by nehashri** [comment]
@zolotov The build.gradle is https://github.com/getgauge/Intellij-Plugin/blob/master/build.gradle . 
I update `id "org.jetbrains.intellij" version "0.3.4"` to `id "org.jetbrains.intellij" version "0.4.7" here.

**Comment by zolotov** [comment]
so you use `ideaVersion=2019.1`, it's compiled and run with Java 8, you cannot use your Java 11-compiled plugin under java 8

**Comment by nehashri** [comment]
@zolotov Oh I see. I will try to work with Java 8 for now. Thanks for your help.

**Comment by zolotov** [comment]
I think you can also try to run IDE under java 11. See `jbrVersion` description property in the README

**Comment by nehashri** [comment]
You mean something like 
```
runIde {
        jbrVersion = '11_0_2b159'
    }
```

**Comment by zolotov** [comment]
yes

**Comment by zolotov** [comment]
but note that the real installation which uses Java8 will throw the same exception anyway.

**Comment by nehashri** [comment]
Ok. I think its best to work with Java 8 then.

**Comment by SingingBush** [comment]
I'm seeing this same error and am using JDK 8 as well as forcing the plugin not to use JBR with:

```
    runIde {
        jbrVersion null
    }
```

I am targeting 2019.1

**Comment by zolotov** [comment]
> I'm seeing this same error and am using JDK 8 as well as forcing the plugin not to use JBR with:

`null` doesn't mean "not to use JBR"

**Comment by SingingBush** [comment]
Similar but not the same, I'll create a new issue

**Comment by ciez** [comment]
ran into a similar limitation in the buildSearchableOptions task:

```
java.lang.UnsupportedClassVersionError: {code file name} has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

is it currently possible to build and run with java 15?

**Comment by YannCebron** [comment]
@ciez No, the Java version should match the supported version of the IDE platform (11 for 2020.3, 8 for earlier versions)
