### ISSUE TITLE
`:buildSearchableOptions` task fails on linux

### ISSUE THREAD

**Issue by bbyk** [JetBrains/gradle-intellij-plugin#391]
I switched to `id 'org.jetbrains.intellij' version '0.4.8'` recently and my linux build for an IDEA plugin started failing with the error below. Can I at least suppress this somehow?

```
> Task :buildSearchableOptions
Starting searchable options index builder
Searchable options index builder failed
java.lang.UnsatisfiedLinkError: /root/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbrx-8u202-linux-x64-b1483.44/jre/lib/amd64/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:60)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:32)
	at sun.font.SunFontManager$1.run(SunFontManager.java:314)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<clinit>(SunFontManager.java:310)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:82)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.awt.Font.getFont2D(Font.java:492)
	at java.awt.Font.getFamily(Font.java:1221)
	at java.awt.Font.getFamily_NoClientCode(Font.java:1195)
	at java.awt.Font.getFamily(Font.java:1187)
	at sun.swing.SwingUtilities2.displayPropertiesToCSS(SwingUtilities2.java:1600)
	at javax.swing.plaf.basic.BasicHTML$BasicDocument.setFontAndColor(BasicHTML.java:379)
	at javax.swing.plaf.basic.BasicHTML$BasicDocument.<init>(BasicHTML.java:368)
	at javax.swing.plaf.basic.BasicHTML$BasicEditorKit.createDefaultDocument(BasicHTML.java:324)
	at javax.swing.plaf.basic.BasicHTML.createHTMLView(BasicHTML.java:61)
	at javax.swing.plaf.basic.BasicHTML.updateRenderer(BasicHTML.java:220)
	at javax.swing.plaf.basic.BasicLabelUI.propertyChange(BasicLabelUI.java:481)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8445)
	at javax.swing.JLabel.setText(JLabel.java:330)
	at com.android.tools.idea.databinding.config.DataBindingConfigurable.$$$setupUI$$$(DataBindingConfigurable.java)
	at com.android.tools.idea.databinding.config.DataBindingConfigurable.<init>(DataBindingConfigurable.java:41)
	at com.android.tools.idea.databinding.config.DataBindingConfigurableProvider.createConfigurable(DataBindingConfigurableProvider.java:26)
	at com.intellij.openapi.options.ConfigurableEP$ProviderProducer.createElement(ConfigurableEP.java:333)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:263)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createConfigurable(ConfigurableWrapper.java:43)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:108)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:83)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:129)
	at com.intellij.openapi.options.ex.Weighted.lambda$static$0(Weighted.java:35)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections.sort(Collections.java:175)
	at com.intellij.openapi.options.ex.SortedConfigurableGroup.buildConfigurables(SortedConfigurableGroup.java:52)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:96)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.collect(ShowSettingsUtilImpl.java:76)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurables(ShowSettingsUtilImpl.java:67)
	at com.intellij.ide.ui.search.SearchUtil.processProjectConfigurables(SearchUtil.java:46)
	at com.intellij.ide.ui.search.TraverseUIStarter.startup(TraverseUIStarter.java:103)
	at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:87)
	at com.intellij.idea.IdeaApplication.lambda$run$1(IdeaApplication.java:211)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:211)
	at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:347)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

> Task :buildSearchableOptions FAILED
```

**Comment by bbyk** [comment]
The workaround is to add `buildSearchableOptions.enabled = false`. Not sure what implications for skipping the task are though.

**Comment by zolotov** [comment]
What's the IDE version and Java version you use for running IDE?

**Comment by zolotov** [comment]
also, please take a look at this comment: https://youtrack.jetbrains.com/issue/JBR-34#focus=streamItem-27-1615609.0-0

**Comment by bbyk** [comment]
> What's the IDE version and Java version you use for running IDE?

The build is being run on in docker container on a CI system.
```
Linux version 4.18.7-64
Red Hat 7.3.1-5
```
```
intellij {
    version '191.6707.61'
    ...
}
````

**Comment by bbyk** [comment]
What do I lose if I set
```
buildSearchableOptions.enabled = false
```

**Comment by zolotov** [comment]
have you tried the workaround I posted before? https://youtrack.jetbrains.com/issue/JBR-34#focus=streamItem-27-1615609.0-0

> What do I lose if I set

Settings of your plugin won't be searchable in the Settings and Find action popup

**Comment by bbyk** [comment]
> have you tried the workaround I posted before?
No because of the build constraints. But I don't think that `youtrack` you referred to applies to the issue. There they had `libfreetype.so` and it was crashing in it. I did some digging and it appears that the Linux machines running my build don't have `freetype` library (`libfreetype.so`) installed on them. So this sort of staging of AWT app in `buildSearchableOptions` on them won't be possible for me.

**Comment by zolotov** [comment]
well, then `buildSearchableOptions.enabled = false` is a proper solution for this case. closing the issue
