### ISSUE TITLE
Cannot build searchable options

### ISSUE THREAD

**Issue by ice1000** [JetBrains/gradle-intellij-plugin#396]
I got this exception:

```
> Task :buildSearchableOptions
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.ide.ClassUtilCore to field sun.net.www.protocol.jar.JarFileFactory.fileCache
WARNING: Please consider reporting this to the maintainers of com.intellij.ide.ClassUtilCore
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Starting searchable options index builder
java.lang.Error: no ComponentUI class for: com.intellij.ide.plugins.newui.MyOptionButton[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true]
        at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:762)
        at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:131)
        at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:792)
        at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1066)
        at java.desktop/javax.swing.JButton.updateUI(JButton.java:141)
        at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2136)
        at java.desktop/javax.swing.JButton.<init>(JButton.java:131)
        at java.desktop/javax.swing.JButton.<init>(JButton.java:85)
        at java.desktop/javax.swing.JButton.<init>(JButton.java:116)
        at com.intellij.ui.components.JBOptionButton.<init>(JBOptionButton.java:28)
        at com.intellij.ide.plugins.newui.MyOptionButton.<init>(MyOptionButton.java:14)
        at com.intellij.ide.plugins.newui.PluginDetailsPageComponent.createButtons(PluginDetailsPageComponent.java:193)
        at com.intellij.ide.plugins.newui.PluginDetailsPageComponent.createCenterPanel(PluginDetailsPageComponent.java:129)
        at com.intellij.ide.plugins.newui.PluginDetailsPageComponent.createPluginPanel(PluginDetailsPageComponent.java:104)
        at com.intellij.ide.plugins.newui.PluginDetailsPageComponent.<init>(PluginDetailsPageComponent.java:75)
        at com.intellij.ide.plugins.PluginManagerConfigurableNewLayout$9.createDetailsPanel(PluginManagerConfigurableNewLayout.java:753)
        at com.intellij.ide.plugins.newui.PluginsTab.createPanel(PluginsTab.java:105)
        at com.intellij.ide.plugins.PluginManagerConfigurableNewLayout$2.create(PluginManagerConfigurableNewLayout.java:181)
        at com.intellij.ide.plugins.PluginManagerConfigurableNewLayout$2.create(PluginManagerConfigurableNewLayout.java:174)
        at com.intellij.ui.CardLayoutPanel.createValue(CardLayoutPanel.java:87)
        at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:115)
        at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:100)
        at com.intellij.ide.plugins.PluginManagerConfigurableNewLayout.lambda$createComponent$0(PluginManagerConfigurableNewLayout.java:138)
        at com.intellij.ide.plugins.newui.TabbedPaneHeaderComponent.lambda$setListener$0(TabbedPaneHeaderComponent.java:87)
        at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:418)
        at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:269)
        at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:143)
        at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:74)
        at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:622)
        at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:597)
        at com.intellij.ui.components.JBTabbedPane.setSelectedIndex(JBTabbedPane.java:68)
        at com.intellij.ide.plugins.newui.TabbedPaneHeaderComponent.setSelection(TabbedPaneHeaderComponent.java:111)
        at com.intellij.ide.plugins.PluginManagerConfigurableNewLayout.createComponent(PluginManagerConfigurableNewLayout.java:191)
        at com.intellij.ide.plugins.PluginManagerConfigurableProxy.createComponent(PluginManagerConfigurableProxy.java:102)
        at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:155)
        at com.intellij.ide.ui.search.SearchUtil.processConfigurables(SearchUtil.java:75)
        at com.intellij.ide.ui.search.SearchUtil.processProjectConfigurables(SearchUtil.java:48)
        at com.intellij.ide.ui.search.TraverseUIStarter.startup(TraverseUIStarter.java:97)
        at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:80)
        at com.intellij.idea.IdeaApplication.lambda$run$2(IdeaApplication.java:276)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:181)
        at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:276)
        at com.intellij.idea.IdeaApplication.lambda$null$0(IdeaApplication.java:79)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:360)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Searchable options index builder completed
```

when building with local idea IC-192.4205.45

**Comment by zolotov** [comment]
Will be fixed in the next eap: https://youtrack.jetbrains.com/issue/IDEA-214885
