### ISSUE TITLE
ClassNotFoundException: org.jetbrains.plugins.gradle.util.GradleBundle

### ISSUE THREAD

**Issue by ice1000** [JetBrains/gradle-intellij-plugin#399]
```
2019-06-09 13:45:17,565 [   9613]  ERROR - nSystem.impl.ActionManagerImpl - org.jetbrains.plugins.gradle.integrations.maven.codeInsight.actions.AddGradleDslDependencyAction (Gradle.AddGradleDslDependencyAction): group with id "Gradle.GenerateGroup" isn't registered; action will be added to the "Other" group [Plugin: org.jetbrains.plugins.gradle.maven] 
com.intellij.diagnostic.PluginException: org.jetbrains.plugins.gradle.integrations.maven.codeInsight.actions.AddGradleDslDependencyAction (Gradle.AddGradleDslDependencyAction): group with id "Gradle.GenerateGroup" isn't registered; action will be added to the "Other" group [Plugin: org.jetbrains.plugins.gradle.maven]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:357)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:352)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getParentGroup(ActionManagerImpl.java:861)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processAddToGroupNode(ActionManagerImpl.java:827)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionElement(ActionManagerImpl.java:607)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionsChildElement(ActionManagerImpl.java:1003)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.java:470)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:133)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:88)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:487)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at org.picocontainer.defaults.BasicComponentParameter.resolveInstance(BasicComponentParameter.java:77)
	at org.picocontainer.defaults.ComponentParameter.resolveInstance(ComponentParameter.java:114)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getConstructorArguments(CachingConstructorInjectionComponentAdapter.java:109)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:88)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.createAndInitialize(ServiceManagerImpl.java:243)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:227)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at org.picocontainer.defaults.BasicComponentParameter.resolveInstance(BasicComponentParameter.java:77)
	at org.picocontainer.defaults.ComponentParameter.resolveInstance(ComponentParameter.java:114)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getConstructorArguments(CachingConstructorInjectionComponentAdapter.java:109)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:88)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:487)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:444)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:403)
	at com.intellij.idea.IdeaApplication.lambda$null$4(IdeaApplication.java:112)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:364)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2019-06-09 13:45:17,572 [   9620]  ERROR - nSystem.impl.ActionManagerImpl - IntelliJ IDEA 2019.2 EAP  Build #IC-192.4787.16 
2019-06-09 13:45:17,572 [   9620]  ERROR - nSystem.impl.ActionManagerImpl - JDK: 12.0.1; VM: OpenJDK 64-Bit Server VM; Vendor: Oracle Corporation 
2019-06-09 13:45:17,572 [   9620]  ERROR - nSystem.impl.ActionManagerImpl - OS: Windows 10 
Starting searchable options index builder
2019-06-09 13:45:29,698 [  21746]  ERROR - nSystem.impl.ActionManagerImpl - java.lang.reflect.InvocationTargetException [Plugin: org.jetbrains.plugins.gradle.maven] 
com.intellij.diagnostic.PluginException: java.lang.reflect.InvocationTargetException [Plugin: org.jetbrains.plugins.gradle.maven]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:163)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:139)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:492)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:480)
	at com.intellij.ide.ui.search.TraverseUIStarter.processKeymap(TraverseUIStarter.java:268)
	at com.intellij.ide.ui.search.TraverseUIStarter.startup(TraverseUIStarter.java:135)
	at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:87)
	at com.intellij.idea.IdeaApplication.lambda$null$2(IdeaApplication.java:116)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
	at com.intellij.idea.IdeaApplication.lambda$null$4(IdeaApplication.java:116)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:364)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:116)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:408)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:376)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:156)
	... 23 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:389)
	... 25 more
Caused by: java.lang.NoClassDefFoundError: org/jetbrains/plugins/gradle/util/GradleBundle
	at org.jetbrains.plugins.gradle.integrations.maven.codeInsight.actions.AddGradleDslDependencyAction.<init>(AddGradleDslDependencyAction.java:40)
	... 31 more
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.gradle.util.GradleBundle PluginClassLoader[org.jetbrains.plugins.gradle.maven, 192.4787.16] com.intellij.ide.plugins.cl.PluginClassLoader@41a74038
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:69)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 32 more
2019-06-09 13:45:29,701 [  21749]  ERROR - nSystem.impl.ActionManagerImpl - IntelliJ IDEA 2019.2 EAP  Build #IC-192.4787.16 
2019-06-09 13:45:29,701 [  21749]  ERROR - nSystem.impl.ActionManagerImpl - JDK: 12.0.1; VM: OpenJDK 64-Bit Server VM; Vendor: Oracle Corporation 
2019-06-09 13:45:29,701 [  21749]  ERROR - nSystem.impl.ActionManagerImpl - OS: Windows 10 
2019-06-09 13:45:29,701 [  21749]  ERROR - nSystem.impl.ActionManagerImpl - Last Action:  
Searchable options index builder failed
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null
	at com.intellij.util.ObjectUtils.$$$reportNull$$$0(ObjectUtils.java)
	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java)
	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java:123)
	at com.intellij.ide.ui.search.TraverseUIStarter.processKeymap(TraverseUIStarter.java:268)
	at com.intellij.ide.ui.search.TraverseUIStarter.startup(TraverseUIStarter.java:135)
	at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:87)
	at com.intellij.idea.IdeaApplication.lambda$null$2(IdeaApplication.java:116)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
	at com.intellij.idea.IdeaApplication.lambda$null$4(IdeaApplication.java:116)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:364)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

> Task :buildSearchableOptions FAILED

FAILURE: Build failed with an exception.
```

The local IDE selected by gradle is `IDEA-C/192.4787.16`

**Comment by zolotov** [comment]
closing in favor of #400
