### ISSUE TITLE
Missing essential plugins: com.intellij.java

### ISSUE THREAD

**Issue by ice1000** [JetBrains/gradle-intellij-plugin#400]
Using the same IntelliJ version as in #399, I've tried to disable running searchable options and it gives me this error when trying to run tests:

```
java.lang.AssertionError: Missing essential plugins: com.intellij.java
	at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:61)
	at com.intellij.testFramework.TestLogger.error(TestLogger.java:40)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:170)
	at com.intellij.ide.plugins.PluginManagerCore.initPlugins(PluginManagerCore.java:1670)
	at com.intellij.ide.plugins.PluginManagerCore.getLoadedPlugins(PluginManagerCore.java:141)
	at com.intellij.idea.IdeaTestApplication.lambda$createInstance$0(IdeaTestApplication.java:96)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: com.intellij.ide.plugins.PluginManagerCore$EssentialPluginMissingException: Missing essential plugins: com.intellij.java
	at com.intellij.ide.plugins.PluginManagerCore.checkEssentialPluginsAreAvailable(PluginManagerCore.java:1467)
	at com.intellij.ide.plugins.PluginManagerCore.initializePlugins(PluginManagerCore.java:1478)
	at com.intellij.ide.plugins.PluginManagerCore.initPlugins(PluginManagerCore.java:1664)
	... 6 more
```

**Comment by zolotov** [comment]
add `intellij { plugins = ['java'] }`

**Comment by YannCebron** [comment]
https://blog.jetbrains.com/platform/2019/06/java-functionality-extracted-as-a-plugin/

**Comment by ice1000** [comment]
Fixed
