### ISSUE TITLE
Custom runIde task requires idea and pluginDirectory

### ISSUE THREAD

**Issue by utikeev** [JetBrains/gradle-intellij-plugin#401]
Plugin version: `0.4.9`
Building plugin for PyCharm

I've created custom `runIde` task as described in `custom-run-ide-task` example:
```
task runIdeNonInternal(type: RunIdeTask) {
    jvmArgs "-Didea.is.internal=false"
}
```
Nevertheless, I receive the following errors when trying to run this task:
```
17:56:44: Executing task 'runIdeNonInternal'...

> Task :wrapper

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :patchPluginXml UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :inspectClassesForKotlinIC UP-TO-DATE
> Task :instrumentCode UP-TO-DATE
> Task :postInstrumentCode
> Task :jar UP-TO-DATE
> Task :prepareSandbox UP-TO-DATE
> Task :copyStubs NO-SOURCE
> Task :runIdeNonInternal FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':runIdeNonInternal'.
> No value has been specified for property 'ideaDirectory'.
> No value has been specified for property 'pluginsDirectory'.
```
`runIde` task works fine for me with this argument.

**Comment by zolotov** [comment]
> No value has been specified for property 'ideaDirectory'.
> No value has been specified for property 'pluginsDirectory'.

You have to set them

> runIde task works fine for me with this argument.

Those parameters are filled by gradle-intellij-plugin

**Comment by utikeev** [comment]
And is there any way to run exactly runIde with these jvmArgs? Maybe the way to pass it as an argument to run configuration?

**Comment by zolotov** [comment]
`runIde.ideaDirectory` or something like that

**Comment by utikeev** [comment]
``` gradle
task runIdeNonInternal(type: RunIdeTask) {
    jvmArgs "-Didea.is.internal=false"
    ideaDirectory runIde.ideaDirectory
    pluginsDirectory runIde.pluginsDirectory
}
```

`> Cannot get property 'classes' on null object`

So it seems these parameters are mapped only when the task is called?

**Comment by zolotov** [comment]
` ideaDirectory { runIde.ideaDirectory }` to make it lazy?

**Comment by utikeev** [comment]
`> Cannot get property 'absolutePath' on null object`

**Comment by zolotov** [comment]
the same for pluginsDirectory of course

**Comment by utikeev** [comment]
Yeah, but that still occurs :)

**Comment by zolotov** [comment]
please attach the full stacktrace using (use `--stacktrace` argument to get it)

**Comment by utikeev** [comment]
```
> Task :runIdeNonInternal FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runIdeNonInternal'.
> Cannot get property 'absolutePath' on null object

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':runIdeNonInternal'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NullPointerException: Cannot get property 'absolutePath' on null object
        at org.jetbrains.intellij.Utils.getIdeaSystemProperties(Utils.groovy:78)
        at org.jetbrains.intellij.Utils$getIdeaSystemProperties$9.call(Unknown Source)
        at org.jetbrains.intellij.tasks.RunIdeBase.configureSystemProperties(RunIdeBase.groovy:200)
        at org.jetbrains.intellij.tasks.RunIdeBase.exec(RunIdeBase.groovy:173)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more
```

**Comment by zolotov** [comment]
thanks, I'll take a look

**Comment by zolotov** [comment]
also, you need 

```
        configDirectory = {runIde.configDirectory}
        systemDirectory = {runIde.systemDirectory}
```

**Comment by ArtsiomCh** [comment]
Got the same issue moving from 0.3.12 to 0.4.9.
IMHO would be better to maintain consistency and set `pluginsDirectory`, `configDirectory` and `systemDirectory` to defaults if not specified, as it was before.

**Comment by ArtsiomCh** [comment]
To not create new similar issue will ask here:
If I need to create a few RunIde tasks how to avoid setting pluginsDirectory, configDirectory, and systemDirectory for each task repeatedly?
Example:
```
task runCLion_191(type: RunIdeTask){
    ideaDirectory '.../CLion/ch-0/191.7141.37/'
}
task runCLion_183(type: RunIdeTask){
    ideaDirectory '.../CLion/ch-1/183.5429.37/'
}
etc...
```
Should I made some kind of "proto-task/abstract-task" with
```
    pluginsDirectory = {runIde.pluginsDirectory}
    configDirectory = {runIde.configDirectory}
    systemDirectory = {runIde.systemDirectory}
```
and then declare all runClion_xxx tasks as `type:` from it? If so how to do it in groovy?
PS that's probably my lack of experience with groovy rather than issue with this plugin...

**Comment by zolotov** [comment]
@ArtsiomCh to avoid it you can just use SNAPSHOT version of the plugin. Another way is you can just interate all RunIde tasks and set their properties: `project.tasks.withType(RunIde.class).forEach{}` or something like this
