### ISSUE TITLE
Different test result depending on which host system it is executed on

### ISSUE THREAD

**Issue by fharms** [JetBrains/gradle-intellij-plugin#402]
We have strange issue when running the gradle command `./gradlew build check -i -s` our tests behave different on a Linux system, but if I run it on OSX the test cases run successfully. 

The tests has been running fine for a long time both on OSX and Linux, but was start failing after we upgraded to `IC-2019.1.3`

I have a hard time understanding what is causing this, and I'm not even sure this is a gradle plug-in issue, test or framework problem, but  it seems like on linux it does not recognize the test directory is set to `src/test/resources/testData/annotator/method`?

```java
@Override
protected String getTestDataPath() {
        return "src/test/resources/testData/annotator/method";
}
```

Thanks,
Flemming 

The complete travis build log can be viewed here [travis log](https://api.travis-ci.org/v3/job/544876248/log.txt)

test result 
```
com.intellij.rt.execution.junit.FileComparisonFailure: AnnotatorJavaBeanRoute3TestData.java: missing (32:33/18): '"myOverLoadedBean"' (Ambiguous matches 'myOverLoadedBean' in bean 'testData.annotator.method.AnnotatorJavaBeanTestData')
 expected:<...")
            .bean[(beanTestData, "myOverLoadedBean2")
            .bean(beanTestData, "myOverLoadedBean(${body})")
            .bean(beanTestData, <error descr="Ambiguous matches 'myOverLoadedBean' in bean 'testData.annotator.method.AnnotatorJavaBeanTestData'">"myOverLoadedBean"</error>)]
            .to("lo...> but was:<...")
            .bean[<error descr="Cannot resolve method 'bean(testData.annotator.method.AnnotatorJavaBeanTestData, java.lang.String)'">(beanTestData, "myOverLoadedBean2")</error>
            .bean<error descr="Cannot resolve method 'bean(testData.annotator.method.AnnotatorJavaBeanTestData, java.lang.String)'">(beanTestData, "myOverLoadedBean(${body})")</error>
            .bean<error descr="Cannot resolve method 'bean(testData.annotator.method.AnnotatorJavaBeanTestData, java.lang.String)'">(beanTestData, "myOverLoadedBean")</error>]
            .to("lo...>
	at com.intellij.testFramework.ExpectedHighlightingData.compareTexts(ExpectedHighlightingData.java:536)
	at com.intellij.testFramework.ExpectedHighlightingData.checkResult(ExpectedHighlightingData.java:501)
	at com.intellij.testFramework.ExpectedHighlightingData.checkResult(ExpectedHighlightingData.java:444)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.collectAndCheckHighlighting(CodeInsightTestFixtureImpl.java:1458)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.collectAndCheckHighlighting(CodeInsightTestFixtureImpl.java:1421)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.checkHighlighting(CodeInsightTestFixtureImpl.java:499)
	at com.github.cameltooling.idea.annotator.CamelBeanMethodAnnotatorTestIT.testAnnotatorJavaBeanAmbiguousMatch(CamelBeanMethodAnnotatorTestIT.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at com.intellij.testFramework.UsefulTestCase.lambda$runTest$11(UsefulTestCase.java:319)
	at com.intellij.testFramework.UsefulTestCase.lambda$invokeTestRunnable$12(UsefulTestCase.java:360)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:43)
	at com.intellij.testFramework.UsefulTestCase.invokeTestRunnable(UsefulTestCase.java:359)
	at com.intellij.testFramework.UsefulTestCase.runTest(UsefulTestCase.java:338)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:374)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:19)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:14)
	at com.intellij.testFramework.EdtTestUtilKt$runInEdtAndWait$1.run(EdtTestUtil.kt:49)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:156)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by zolotov** [comment]
I don't think I can help you without sources to recreate the issue. Have you tried to debug it on linux?

**Comment by fharms** [comment]
This turned out to be an issue with our test case, and particular the ordre it was running on Linux was different.
