### ISSUE TITLE
NullPointerException during buildSearchableOptions

### ISSUE THREAD

**Issue by carymrobbins** [JetBrains/gradle-intellij-plugin#424]
HaskForce commit [4e0a23a](https://github.com/carymrobbins/intellij-haskforce/commits/4e0a23ad93d89f2c720d5ac536bd8d3a98ee06c2)
gradle-intellij-plugin v0.4.10

I'm not sure if this is a bug in gradle-intellij-plugin, IntelliJ proper, or maybe even HaskForce (perhaps we might be breaking some mysterious invariant?).

The `:buildSearchableOptions` task is failing with a NullPointerException. It looks like the `getEditor()` call from [CodeStyleAbstractPanel#installPreviewPanel](https://github.com/JetBrains/intellij-community/blob/4bea9ee426d631ab83f0bd04525be775cbbc883c/platform/lang-impl/src/com/intellij/application/options/CodeStyleAbstractPanel.java#L437) can return `null`, and so the `getEditor().getComponent()` call throws the NPE.

Full stack trace can be seen below -

```
% ./gradlew :buildSearchableOptions
```
```
...
:buildSearchableOptions
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.ide.ClassUtilCore to field sun.net.www.protocol.jar.JarFileFactory.fileCache
WARNING: Please consider reporting this to the maintainers of com.intellij.ide.ClassUtilCore
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Starting searchable options index builder
2019-08-16 17:51:34,255 [   2930]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting
Searchable options index builder failed
java.lang.NullPointerException
        at com.intellij.application.options.CodeStyleAbstractPanel.installPreviewPanel(CodeStyleAbstractPanel.java:437)
        at com.intellij.application.options.TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.<init>(TabbedLanguageCodeStylePanel.java:513)
        at com.intellij.application.options.TabbedLanguageCodeStylePanel.addIndentOptionsTab(TabbedLanguageCodeStylePanel.java:88)
        at com.haskforce.language.formatting.HaskellTabbedCodeStylePanel.initTabs(HaskellTabbedCodeStylePanel.java:20)
        at com.intellij.application.options.TabbedLanguageCodeStylePanel.ensureTabs(TabbedLanguageCodeStylePanel.java:121)
        at com.intellij.application.options.TabbedLanguageCodeStylePanel.getPreviewText(TabbedLanguageCodeStylePanel.java:199)
        at com.intellij.application.options.CodeStyleAbstractPanel.createEditor(CodeStyleAbstractPanel.java:138)
        at com.intellij.application.options.CodeStyleAbstractPanel.<init>(CodeStyleAbstractPanel.java:97)
        at com.intellij.application.options.TabbedLanguageCodeStylePanel.<init>(TabbedLanguageCodeStylePanel.java:54)
        at com.haskforce.language.formatting.HaskellTabbedCodeStylePanel.<init>(HaskellTabbedCodeStylePanel.java:15)
        at com.haskforce.language.formatting.HaskellCodeStyleSettingsProvider$1.createPanel(HaskellCodeStyleSettingsProvider.java:24)
        at com.intellij.application.options.CodeStyleAbstractConfigurable.createComponent(CodeStyleAbstractConfigurable.java:34)
        at com.intellij.application.options.codeStyle.NewCodeStyleSettingsPanel.<init>(NewCodeStyleSettingsPanel.java:35)
        at com.intellij.ConfigurableFactory$createCodeStyleConfigurable$codeStyleConfigurableWrapper$1.createPanel(ConfigurableFactory.kt:46)
        at com.intellij.application.options.codeStyle.CodeStyleMainPanel.ensurePanel(CodeStyleMainPanel.java:238)
        at com.intellij.application.options.codeStyle.CodeStyleMainPanel.ensureCurrentPanel(CodeStyleMainPanel.java:223)
        at com.intellij.application.options.codeStyle.CodeStyleMainPanel.lambda$onCurrentSchemeChanged$0(CodeStyleMainPanel.java:163)
        at com.intellij.application.options.codeStyle.CodeStyleMainPanel.onCurrentSchemeChanged(CodeStyleMainPanel.java:170)
        at com.intellij.application.options.codeStyle.CodeStyleMainPanel.<init>(CodeStyleMainPanel.java:134)
        at com.intellij.application.options.CodeStyleConfigurableWrapper.createComponent(CodeStyleConfigurableWrapper.java:48)
        at com.intellij.ide.ui.search.SearchUtil.processConfigurables(SearchUtil.java:76)
        at com.intellij.ide.ui.search.SearchUtil.processProjectConfigurables(SearchUtil.java:48)
        at com.intellij.ide.ui.search.TraverseUIStarter.startup(TraverseUIStarter.java:106)
        at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:87)
        at com.intellij.idea.IdeaApplication.lambda$null$3(IdeaApplication.java:154)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
        at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:154)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:433)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
:buildSearchableOptions FAILED
```

**Comment by zolotov** [comment]
have you tried to debug it? Is `getEditor` is null? Why? May this be because previewText is empty for the Haskell code style configuration?

**Comment by zolotov** [comment]
closing due to lack of feedback

**Comment by carymrobbins** [comment]
I did try to debug it, but it wasn't clear to me _why_ the editor was null. Once I get back around to this issue (working on other issues at the moment, I've worked around it for now) I'll post back if I need to. I have a feeling you are likely right about some invariant I'm violating.

**Comment by zolotov** [comment]
I couldn't recreate this on my plugin so yeah, if you face it again, please try to debug it and comment here if something wrong on IDEA or on gradle-intellij-plugin side. Thanks

**Comment by carymrobbins** [comment]
Ok, problem was that the code sample was an empty string. Was pretty confusing with the indent editor stuff going on under the hood, but apparently actually having a code sample is important. It's actually pretty unclear how the sample is supposed to update for indent changes, but hopefully I'll figure that part out later.

**Comment by zolotov** [comment]
So it looks like failing buildSearchableOptions task was showing the real problem on the production, is this the case? Or the problem is reproducible in headless mode only?

**Comment by carymrobbins** [comment]
I guess it _did_ start happening in production and no one noticed. Maybe with the upgrade to 2019.2.
