### ISSUE TITLE
The buildSearchableOptions task fails when targeting 2019.2

### ISSUE THREAD

**Issue by SingingBush** [JetBrains/gradle-intellij-plugin#437]
I'm targeting Inttelij 2019.2 using version 0.4.11 of the gradle-intellij-plugin with Gradle 4.8.1 and JDK 1.8.0_211.

When running `./gradlew buildPlugin` it fails on the _buildSearchableOptions_ task. 

The task attempts to use my `%HOME%\.gradle\caches\modules-2\files-2.1\com.jetbrains\jbre\jbr-11_0_3-windows-x64-b304.10\jbr\bin\java.exe`

and spits out the following stack trace:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.ide.ClassUtilCore to field sun.net.www.protocol.jar.JarFileFactory.fileCache
WARNING: Please consider reporting this to the maintainers of com.intellij.ide.ClassUtilCore
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Starting searchable options index builder
2019-11-03 17:45:44,630 [   4238]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting
Searchable options index builder failed
java.lang.AssertionError: Wrong line separators: '/*\r\n * Some ...' at offset 2
        at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2726)
        at com.intellij.openapi.editor.impl.DocumentImpl.assertValidSeparators(DocumentImpl.java:693)
        at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:137)
        at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:132)
        at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:123)
        at com.intellij.openapi.editor.impl.EditorFactoryImpl.createDocument(EditorFactoryImpl.java:112)
        at com.intellij.application.options.colors.FontEditorPreview.createPreviewEditor(FontEditorPreview.java:86)
        at com.intellij.application.options.colors.SimpleEditorPreview.<init>(SimpleEditorPreview.java:65)
        at com.intellij.application.options.colors.SimpleEditorPreview.<init>(SimpleEditorPreview.java:55)
        at com.intellij.application.options.colors.ColorAndFontOptions$1.createPanel(ColorAndFontOptions.java:407)
        at com.intellij.application.options.colors.ColorAndFontOptions$InnerSearchableConfigurable.createPanel(ColorAndFontOptions.java:1325)
        at com.intellij.application.options.colors.ColorAndFontOptions$InnerSearchableConfigurable.createComponent(ColorAndFontOptions.java:1356)
        at com.intellij.ide.ui.search.SearchUtil.processConfigurables(SearchUtil.java:76)
        at com.intellij.ide.ui.search.SearchUtil.processProjectConfigurables(SearchUtil.java:48)
        at com.intellij.ide.ui.search.TraverseUIStarter.startup(TraverseUIStarter.java:106)
        at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:87)
        at com.intellij.idea.IdeaApplication.lambda$null$3(IdeaApplication.java:154)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
        at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:154)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:433)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

> Task :buildSearchableOptions FAILED
:buildSearchableOptions (Thread[Task worker for ':' Thread 4,5,main]) completed. Took 12.392 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSearchableOptions'.
```

Should I be using JDK 11?

**Comment by zolotov** [comment]
It looks like one of the ColorsAndFont configurable page contains incorrect example text. Could you run it in debug mode, stop at `com.intellij.openapi.editor.impl.DocumentImpl.assertValidSeparators(DocumentImpl.java:693)` and see what is the `page` variable up to the stack at `com.intellij.application.options.colors.ColorAndFontOptions$1.createPanel(ColorAndFontOptions.java:407)`?

**Comment by SingingBush** [comment]
It's this:

```
/*
 * Some block commments
 * go here
 */

/+
 + Nesting comment
 +/

// Line comment
module net.masterthought.cucumber.report_information;

import std.algorithm;
import std.array;

import jsonizer.tojson;
import net.masterthought.cucumber.report_parser;

class ReportInformation {
    string runId;
    Feature[] features;

    private string m_name;
    @property string name() { return m_name; }

    this(ReportParser parser) {
        this.runId = parser.getRunId();
        this.features = parser.getReports().map!(report => report.getFeatures()).joiner.array;
    }

    private Feature[] processFeatures(Feature[] features) {
        return features.map!((f) {
            f.featureInformation = calculateFeatureInformation(f);
            f.scenarios = addScenarioInformation(f);
            return f;
        }).array;
    }

    public auto getTotalNumberOfBackgroundScenariosUnknown() {
        return features.map!(f => f.getBackgroundScenariosUnknown().length).sum;
    }
}

struct {
    string name;
}

union {
    string day;
}

unittest {
    // load test json from file
    auto testJson = to!string(read("src/test/resources/project1.json"));
    string runId = "run 1";
    ReportInformation ri = new ReportInformation(new ReportParser(runId,[testJson]));

    // should have correct number of features
    ri.getFeatures().length.assertEqual(2);

    // overall status
    ri.getOverallStatus.assertEqual(to!string(Status.Failed));

    // feature totals
    Feature feature = ri.getFeatures().front;
}

T foo(T, E : Exception)(Node node, in string path) {
    return node.bar!(T, E)(path);
}
```

**Comment by zolotov** [comment]
well, the message is pretty straightforward: `java.lang.AssertionError: Wrong line separators: '/*\r\n * Some ...' at offset 2`. If it's your extension you just need to fix it and everything will be fine.

**Comment by SingingBush** [comment]
I can change the line endings but it's weird that it's happening at all. That file has not changed since Nov 2017 when it was first added to the code base.

**Comment by zolotov** [comment]
apparently, the platform was changed.
regarding your question about jdk11: you can use it but it's not required for now.

**Comment by SingingBush** [comment]
ok, thanks Zolotov. That was a really fast response!
