### ISSUE TITLE
Remove usages of deprecated Gradle API

### ISSUE THREAD

**Issue by DreierF** [JetBrains/gradle-intellij-plugin#445]
When running the plugin with Gradle 6 I get two warnings for usages of deprecated APIs.

```
The baseName property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveBaseName property instead.
        at org.gradle.api.tasks.bundling.AbstractArchiveTask.setBaseName(AbstractArchiveTask.java:231)
        at org.jetbrains.intellij.tasks.JarSearchableOptionsTask_Decorated.setBaseName(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.intellij.tasks.JarSearchableOptionsTask_Decorated.setProperty(Unknown Source)
        at groovy.lang.Closure.setPropertyTryThese(Closure.java:370)
        at groovy.lang.Closure.setPropertyDelegateFirst(Closure.java:360)
        at groovy.lang.Closure.setProperty(Closure.java:341)
        at org.jetbrains.intellij.IntelliJPlugin$_configureJarSearchableOptionsTask_closure23.doCall(IntelliJPlugin.groovy:401)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:421)
        at org.jetbrains.intellij.IntelliJPlugin.configureJarSearchableOptionsTask(IntelliJPlugin.groovy:398)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.intellij.IntelliJPlugin.configureTasks(IntelliJPlugin.groovy:98)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.intellij.IntelliJPlugin.apply(IntelliJPlugin.groovy:70)
        at org.jetbrains.intellij.IntelliJPlugin.apply(IntelliJPlugin.groovy)
```

```
The destinationDir property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the destinationDirectory property instead.
        at org.gradle.api.tasks.bundling.AbstractArchiveTask.setDestinationDir(AbstractArchiveTask.java:196)
        at org.jetbrains.intellij.tasks.JarSearchableOptionsTask_Decorated.setDestinationDir(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.intellij.tasks.JarSearchableOptionsTask_Decorated.setProperty(Unknown Source)
        at groovy.lang.Closure.setPropertyTryThese(Closure.java:370)
        at groovy.lang.Closure.setPropertyDelegateFirst(Closure.java:360)
        at groovy.lang.Closure.setProperty(Closure.java:341)
        at org.jetbrains.intellij.IntelliJPlugin$_configureJarSearchableOptionsTask_closure23.doCall(IntelliJPlugin.groovy:402)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:421)
        at org.jetbrains.intellij.IntelliJPlugin.configureJarSearchableOptionsTask(IntelliJPlugin.groovy:398)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.intellij.IntelliJPlugin.configureTasks(IntelliJPlugin.groovy:98)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.intellij.IntelliJPlugin.apply(IntelliJPlugin.groovy:70)
        at org.jetbrains.intellij.IntelliJPlugin.apply(IntelliJPlugin.groovy)
```

**Comment by zolotov** [comment]
as soon as Gradle 4 support will be dropped, these usages also will be dropped. until then – won't fix

**Comment by FWDekker** [comment]
@zolotov I understand the reason for not dropping these usages just yet, but I'm not sure what kind of support you're referring to. Do you mean that this will not be resolved until the Gradle team stops supporting it, until this plugin stops supporting it, until JetBrains stops supporting it, or is it something else?

**Comment by zolotov** [comment]
Until JetBrains stops supporting it. I'm going to support 3 recent major versions of gradle. Dropping drop Gradle 3 is on the way.
