### ISSUE TITLE
Cannot download JetBrains Java Runtime jbr-11_0_5-linux-x64-b520.30. Cannot resolve builtin JBR 11_0_5b520.30. Falling local Java.

### ISSUE THREAD

**Issue by AlexanderBartash** [JetBrains/gradle-intellij-plugin#457]
Hello. When I run my plugin using "runIde" task it fails to download JBR. This happens only if my project is located on a different partition (in my case it is even different SSD) than gradle home.

It happens because Gradle-Intellij-Plugin is using [gradle-download-task](https://github.com/michel-kraemer/gradle-download-task) which is using `File.renameTo` and it is not able to move files between partitions. See https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4073756

I've opened an issue for the other Gradle plugin as well: https://github.com/michel-kraemer/gradle-download-task/issues/146

### Steps to reproduce:

1. Make sure that your Intellij Plugin project is located on a different partition than your Gradle home.
2. Remove your downloaded JVMs because if it is cached download won't start again `rm -rf ~/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/`
3. `./gradlew clean :runIde`

```
> Task :runIde
Download https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-jbr/jbr-11_0_5-linux-x64-b520.30.tar.gz
[gradle-intellij-plugin :idea-pluginrunIde] Cannot download JetBrains Java Runtime jbr-11_0_5-linux-x64-b520.30. Run with --debug option to get more log output.
[gradle-intellij-plugin :idea-plugin:runIde] Cannot resolve builtin JBR 11_0_5b520.30. Falling local Java.

Download https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-jbr/jbr-11_0_5-linux-x64-b520.30.tar.gz
[gradle-intellij-plugin :idea-plugin:runIde] Cannot download JetBrains Java Runtime jbr-11_0_5-linux-x64-b520.30. Run with --debug option to get more log output.
[gradle-intellij-plugin :idea-plugin:runIde] Cannot resolve builtin JBR 11_0_5b520.30. Falling local Java.

Download https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-jbr/jbr-11_0_5-linux-x64-b520.30.tar.gz
[gradle-intellij-plugin :idea-plugin:runIde] Cannot download JetBrains Java Runtime jbr-11_0_5-linux-x64-b520.30. Run with --debug option to get more log output.
[gradle-intellij-plugin :idea-plugin:runIde] Cannot resolve builtin JBR 11_0_5b520.30. Falling local Java.
```

Permissions on the folders look good:
```
sasha@sasha-kubuntu:~ $ ll ~/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/
total 8.0K
drwxrwxr-x 2 sasha sasha 4.0K Jan 25 21:14 .
drwxrwxr-x 3 sasha sasha 4.0K Jan 25 21:14 ..

sasha@sasha-kubuntu:~ $ ll ~/sources/idea-plugin/build/download-task/
total 258M
drwxrwxr-x  2 sasha sasha 4.0K Jan 25 21:16 .
drwxrwxr-x 11 sasha sasha 4.0K Jan 25 21:15 ..
-rw-rw-r--  1 sasha sasha 106M Jan 25 21:16 jbr-11_0_5-linux-x64-b520.30.tar.gz3826401119714448048.part
-rw-rw-r--  1 sasha sasha  46M Jan 25 21:16 jbr-11_0_5-linux-x64-b520.30.tar.gz5393996891986106795.part
-rw-rw-r--  1 sasha sasha 106M Jan 25 21:15 jbr-11_0_5-linux-x64-b520.30.tar.gz7231496779691058520.part
```

Debug logs:
```
2020-01-25T21:19:39.282+0200 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Putting task artifact state for task ':runIde' into context took 0.0 secs.

2020-01-25T21:19:39.282+0200 [LIFECYCLE] [org.gradle.api.Project] Download https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-jbr/jbr-11_0_5-linux-x64-b520.30.tar.gz

2020-01-25T21:19:39.389+0200 [DEBUG] [jdk.event.security] ValidationChain: -1472444962, -1011578998, 1965755716
2020-01-25T21:19:39.421+0200 [DEBUG] [jdk.event.security]  TLSHandshake: cache-redirector.jetbrains.com:443, TLSv1.2, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, 1965755716
2020-01-25T21:19:39.665+0200 [DEBUG] [jdk.event.security] ValidationChain: 1136084297, 767446962, -1082064671
2020-01-25T21:19:39.700+0200 [DEBUG] [jdk.event.security]  TLSHandshake: dtahfujkndrht.cloudfront.net:443, TLSv1.2, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, -1082064671
2020-01-25T21:19:44.248+0200 [LIFECYCLE] [sun.rmi.transport.tcp] 
2020-01-25T21:19:44.248+0200 [DEBUG] [sun.rmi.transport.tcp] RMI RenewClean-[127.0.0.1:17319,org.jetbrains.kotlin.daemon.common.LoopbackNetworkInterface$ClientLoopbackSocketFactory@582844f4]: close connection
2020-01-25T21:19:44.249+0200 [DEBUG] [sun.rmi.client.ref] RMI RenewClean-[127.0.0.1:17319,org.jetbrains.kotlin.daemon.common.LoopbackNetworkInterface$ClientLoopbackSocketFactory@582844f4]: get connection
2020-01-25T21:19:44.249+0200 [DEBUG] [sun.rmi.transport.tcp] RMI RenewClean-[127.0.0.1:17319,org.jetbrains.kotlin.daemon.common.LoopbackNetworkInterface$ClientLoopbackSocketFactory@751e37b4]: close connection
2020-01-25T21:19:44.249+0200 [DEBUG] [sun.rmi.transport.tcp] RMI RenewClean-[127.0.0.1:17319,org.jetbrains.kotlin.daemon.common.LoopbackNetworkInterface$ClientLoopbackSocketFactory@582844f4]: create connection
2020-01-25T21:19:44.249+0200 [DEBUG] [sun.rmi.client.ref] RMI RenewClean-[127.0.0.1:17319,org.jetbrains.kotlin.daemon.common.LoopbackNetworkInterface$ClientLoopbackSocketFactory@751e37b4]: get connection
2020-01-25T21:19:44.249+0200 [DEBUG] [sun.rmi.transport.tcp] RMI RenewClean-[127.0.0.1:17319,org.jetbrains.kotlin.daemon.common.LoopbackNetworkInterface$ClientLoopbackSocketFactory@751e37b4]: create connection
2020-01-25T21:19:44.250+0200 [DEBUG] [sun.rmi.client.ref] RMI RenewClean-[127.0.0.1:17319,org.jetbrains.kotlin.daemon.common.LoopbackNetworkInterface$ClientLoopbackSocketFactory@582844f4]: free connection (reuse = true)
2020-01-25T21:19:44.250+0200 [DEBUG] [sun.rmi.client.ref] RMI RenewClean-[127.0.0.1:17319,org.jetbrains.kotlin.daemon.common.LoopbackNetworkInterface$ClientLoopbackSocketFactory@751e37b4]: free connection (reuse = true)
2020-01-25T21:19:44.250+0200 [DEBUG] [sun.rmi.transport.tcp] RMI RenewClean-[127.0.0.1:17319,org.jetbrains.kotlin.daemon.common.LoopbackNetworkInterface$ClientLoopbackSocketFactory@582844f4]: reuse connection
2020-01-25T21:19:44.250+0200 [DEBUG] [sun.rmi.transport.tcp] RMI RenewClean-[127.0.0.1:17319,org.jetbrains.kotlin.daemon.common.LoopbackNetworkInterface$ClientLoopbackSocketFactory@751e37b4]: reuse connection
2020-01-25T21:19:45.614+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-01-25T21:19:45.614+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-01-25T21:19:45.614+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-01-25T21:19:45.615+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-01-25T21:19:45.615+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-01-25T21:19:45.615+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-01-25T21:19:41.309+0200 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] 
2020-01-25T21:19:41.309+0200 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :runIde

2020-01-25T21:19:49.404+0200 [WARN] [org.jetbrains.intellij.IntelliJPlugin] [gradle-intellij-plugin :idea-plugin:runIde] Cannot download JetBrains Java Runtime jbr-11_0_5-linux-x64-b520.30
java.io.IOException: Failed to move temporary file '/media/sasha/nvme/sources/idea-plugin/build/download-task/jbr-11_0_5-linux-x64-b520.30.tar.gz568367918405127325.part' to destination file '/home/sasha/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr-11_0_5-linux-x64-b520.30.tar.gz'.
        at de.undercouch.gradle.tasks.download.DownloadAction.streamAndMove(DownloadAction.java:355)
        at de.undercouch.gradle.tasks.download.DownloadAction.performDownload(DownloadAction.java:320)
        at de.undercouch.gradle.tasks.download.DownloadAction.executeHttpProtocol(DownloadAction.java:279)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:210)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:162)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:160)
        at org.jetbrains.intellij.jbr.JbrResolver$_getJavaArchive_closure1.doCall(JbrResolver.groovy:77)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:421)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:370)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:317)
        at org.codehaus.groovy.runtime.dgm$829.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.jetbrains.intellij.jbr.JbrResolver.getJavaArchive(JbrResolver.groovy:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
        at org.jetbrains.intellij.jbr.JbrResolver.resolve(JbrResolver.groovy:43)
        at org.jetbrains.intellij.jbr.JbrResolver$resolve.call(Unknown Source)
        at org.jetbrains.intellij.IntelliJPlugin$_prepareConventionMappingsForRunIdeTask_closure22.doCall(IntelliJPlugin.groovy:386)
        at org.jetbrains.intellij.IntelliJPlugin$_prepareConventionMappingsForRunIdeTask_closure22.doCall(IntelliJPlugin.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:399)
        at org.gradle.util.GUtil.uncheckedCall(GUtil.java:425)
        at org.gradle.internal.extensibility.ConventionAwareHelper$2.doGetValue(ConventionAwareHelper.java:81)
        at org.gradle.internal.extensibility.ConventionAwareHelper$MappedPropertyImpl.getValue(ConventionAwareHelper.java:127)
        at org.gradle.internal.extensibility.ConventionAwareHelper.getConventionValue(ConventionAwareHelper.java:109)
        at org.jetbrains.intellij.tasks.RunIdeTask_Decorated.getExecutable(Unknown Source)
        at org.gradle.api.tasks.JavaExec.getJavaVersion(JavaExec.java:484)
        at org.jetbrains.intellij.tasks.RunIdeTask_Decorated.getJavaVersion(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1$1.create(AbstractNestedRuntimeBeanNode.java:80)
        at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:518)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1.get(AbstractNestedRuntimeBeanNode.java:76)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue.call(AbstractNestedRuntimeBeanNode.java:148)
        at org.gradle.api.internal.tasks.properties.AbstractValidatingProperty.validate(AbstractValidatingProperty.java:39)
        at org.gradle.api.internal.tasks.properties.DefaultTaskProperties.validate(DefaultTaskProperties.java:193)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.validate(ExecuteActionsTaskExecuter.java:505)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:50)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
2020-01-25T21:19:49.405+0200 [WARN] [org.jetbrains.intellij.IntelliJPlugin] [gradle-intellij-plugin :idea-plugin:runIde] Cannot resolve builtin JBR 11_0_5b520.30. Falling local Java.
```

In fact if I try to move it manually it works and on the next run Gradle plugin is not trying to download JBR again.
```
mv /media/sasha/nvme/sources/idea-plugin/build/download-task/jbr-11_0_5-linux-x64-b520.30.tar.gz568367918405127325.part /home/sasha/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr-11_0_5-linux-x64-b520.30.tar.gz
```

**Comment by AlexanderBartash** [comment]
Similar to:

- https://github.com/JetBrains/gradle-intellij-plugin/issues/404
- https://github.com/JetBrains/gradle-intellij-plugin/issues/367
- https://github.com/JetBrains/gradle-intellij-plugin/issues/397

**Comment by AlexanderBartash** [comment]
Can it be caused by https://github.com/JetBrains/gradle-intellij-plugin/commit/8c222678ccf566b484dd3f3b6d2470b3e6f114ce ?

**Comment by AlexanderBartash** [comment]
The code which causes it:
https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/groovy/org/jetbrains/intellij/jbr/JbrResolver.groovy#L76
https://github.com/michel-kraemer/gradle-download-task/blob/master/src/main/java/de/undercouch/gradle/tasks/download/DownloadAction.java#L357

**Comment by AlexanderBartash** [comment]
I've submitted a bug for that Gradle plugin as well https://github.com/michel-kraemer/gradle-download-task/issues/146

**Comment by AlexanderBartash** [comment]
I've identified the cause here https://github.com/michel-kraemer/gradle-download-task/issues/146#issuecomment-578437549 and fixed description of this issue.

**Comment by AlexanderBartash** [comment]
A new version of the Gradle Download Task has been released with the fix for this problem https://github.com/michel-kraemer/gradle-download-task/releases/tag/4.0.4
We should update the dependency.

**Comment by zolotov** [comment]
Hi Alexander, thank you for the report and investigation. 0.5-SNAPSHOT is on the way, 0.4.16 will be published in a couple days

**Comment by AlexanderBartash** [comment]
Hi @zolotov Awesome. Thank you!

**Comment by AlexanderBartash** [comment]
Hi. I have updated the dependency and it works now. Thank you!
