### ISSUE TITLE
Unit tests throw NoClassDefFoundError in IDEA 2019.3.3

### ISSUE THREAD

**Issue by baron1405** [JetBrains/gradle-intellij-plugin#461]
Upgrading my IntelliJ plugin's SDK to IU-2019.3.3 resulted in my unit tests failing with the following stack trace:
```
    java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: Could not initialize class com.intellij.util.io.FileChannelUtil
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
        at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
        at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:193)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.intellij.util.io.FileChannelUtil
        at com.intellij.util.io.ReadWriteDirectBufferWrapper$FileContext$1.execute(ReadWriteDirectBufferWrapper.java:50)
        at com.intellij.util.io.ReadWriteDirectBufferWrapper$FileContext$1.execute(ReadWriteDirectBufferWrapper.java:42)
        at com.intellij.openapi.util.io.FileUtilRt.doIOOperation(FileUtilRt.java:945)
        at com.intellij.util.io.ReadWriteDirectBufferWrapper$FileContext.<init>(ReadWriteDirectBufferWrapper.java:42)
        at com.intellij.util.io.ReadWriteDirectBufferWrapper.create(ReadWriteDirectBufferWrapper.java:27)
        at com.intellij.util.io.DirectBufferWrapper.getBuffer(DirectBufferWrapper.java:24)
        at com.intellij.util.io.ReadWriteDirectBufferWrapper.getBuffer(ReadWriteDirectBufferWrapper.java:16)
        at com.intellij.util.io.PagedFileStorage$StorageLock.createValue(PagedFileStorage.java:631)
        at com.intellij.util.io.PagedFileStorage$StorageLock.get(PagedFileStorage.java:558)
        at com.intellij.util.io.PagedFileStorage$StorageLock.access$500(PagedFileStorage.java:466)
        at com.intellij.util.io.PagedFileStorage.getBufferWrapper(PagedFileStorage.java:407)
        at com.intellij.util.io.PagedFileStorage.getBuffer(PagedFileStorage.java:371)
        at com.intellij.util.io.PagedFileStorage.put(PagedFileStorage.java:278)
        at com.intellij.util.io.PagedFileStorage.fillWithZeros(PagedFileStorage.java:356)
        at com.intellij.util.io.PagedFileStorage.resize(PagedFileStorage.java:330)
        at com.intellij.util.io.ResizeableMappedFile.expand(ResizeableMappedFile.java:108)
        at com.intellij.util.io.ResizeableMappedFile.ensureSize(ResizeableMappedFile.java:77)
        at com.intellij.util.io.ResizeableMappedFile.putInt(ResizeableMappedFile.java:221)
        at com.intellij.util.io.PersistentEnumeratorBase.markDirty(PersistentEnumeratorBase.java:597)
        at com.intellij.util.io.PersistentEnumeratorBase.<init>(PersistentEnumeratorBase.java:185)
        at com.intellij.util.io.PersistentBTreeEnumerator.<init>(PersistentBTreeEnumerator.java:73)
        at com.intellij.util.io.PersistentBTreeEnumerator.<init>(PersistentBTreeEnumerator.java:65)
        at com.intellij.util.io.PersistentEnumeratorDelegate.<init>(PersistentEnumeratorDelegate.java:38)
        at com.intellij.util.io.PersistentStringEnumerator.<init>(PersistentStringEnumerator.java:53)
        at com.intellij.util.io.PersistentStringEnumerator.<init>(PersistentStringEnumerator.java:46)
        at com.intellij.util.io.PersistentStringEnumerator.<init>(PersistentStringEnumerator.java:32)
        at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.tryInit(FSRecords.java:262)
        at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.init(FSRecords.java:227)
        at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.lambda$connect$0(FSRecords.java:178)
        at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.writeAndHandleErrors(FSRecords.java:980)
        at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.access$300(FSRecords.java:48)
        at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.connect(FSRecords.java:176)
        at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.connect(FSRecords.java:548)
        at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.<init>(PersistentFSImpl.java:76)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:44)
        at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:505)
        at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:52)
        at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
        at com.intellij.serviceContainer.PlatformComponentManagerImpl$preloadServices$future$1.run(PlatformComponentManagerImpl.kt:622)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        ... 7 more
```
After a number of hours of investigation, I found the cause and a workaround. It turns out that a new class called FileChannelUtil was [introduced in 2019.3.3](http://git.jetbrains.org/?p=idea/community.git;a=commit;h=5b2ed5bbcb879bf78256378a7948fba0adff93d4). During static initialization, this class attempts to introspect on the class sun.nio.ch.FileChannelImpl. In general, this is a very questionable thing to do since that class is considered internal. While this will work in Java 8, it will fail in Java 11 since the class is inaccessible by default. Because I compile my plugin using Java 11 and because that makes the class inaccessible, the static initialization of the FileChannelUtil class fails. That generates the stack trace shown above. To work around this issue, I specified the following in my build.gradle.kts file:
```
tasks {
   ...
    withType<Test>().configureEach {
        jvmArgs("--add-opens", "java.base/sun.nio.ch=ALL-UNNAMED")
    }
    ...
}
```
I am reporting this as a bug against the gradle-intellij-plugin because it can be worked around in the plugin. However, I would prefer to see the questionable code in FileChannelUtil corrected. I will leave that to you folks to decide.

Environment:
* CentOS 7.6
* gradle-intellij-plugin 0.4.15
* Gradle 6.1.1

**Comment by zolotov** [comment]
should be fixed in 2020.1. There are no plans with backporting the fix to 2019.3 branch, though

**Comment by illeatmyhat** [comment]
I came across this issue in 2021.3.2.
The OP's solution worked.

**Comment by hsz** [comment]
@illeatmyhat @dstibbe Can you please provide more input on your configuration?

**Comment by dstibbe** [comment]
This disapeared for me after upgrading to gradle 7.3 and java 17.
