### ISSUE TITLE
Unable to inlude Icons

### ISSUE THREAD

**Issue by rishabhdeepsingh** [JetBrains/gradle-intellij-plugin#493]
I am getting the following error
> java.lang.RuntimeException: Can't find icon in 'name/admitriev/jhelper/icons/task.png' near PluginClassLoader[name.admitriev.jhelper, 0.18] com.intellij.ide.plugins.cl.PluginClassLoader@5c714a39
	at com.intellij.openapi.util.IconLoader$CachedImageIcon$HandleNotFound$1.handle(IconLoader.java:822)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon$MyUrlResolver.resolve(IconLoader.java:940)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon$MyUrlResolver.resolve(IconLoader.java:864)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getRealIcon(IconLoader.java:632)
	at com.intellij.ui.icons.LazyImageIcon.getRealIcon(LazyImageIcon.java:76)
	at com.intellij.ui.icons.LazyImageIcon.getIconWidth(LazyImageIcon.java:60)
	at com.intellij.ui.DeferredIconImpl.getIconWidth(DeferredIconImpl.java:308)
	at java.desktop/javax.swing.SwingUtilities.layoutCompoundLabelImpl(SwingUtilities.java:1091)
	at java.desktop/javax.swing.SwingUtilities.layoutCompoundLabel(SwingUtilities.java:1004)
	at java.desktop/javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:357)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaButtonUI.getPreferredSize(DarculaButtonUI.java:260)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1683)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.getPreferredSize(ComboBoxAction.java:297)
	at com.intellij.execution.actions.RunConfigurationsComboBoxAction$1.getPreferredSize(RunConfigurationsComboBoxAction.java:136)
	at java.desktop/java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:724)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1823)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1807)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1685)
	at com.intellij.ui.components.panels.Wrapper.getPreferredSize(Wrapper.java:128)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.getChildPreferredSize(ActionToolbarImpl.java:464)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.calculateBoundsAutoImp(ActionToolbarImpl.java:569)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.calculateBounds(ActionToolbarImpl.java:803)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.getPreferredSize(ActionToolbarImpl.java:834)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.actionsUpdated(ActionToolbarImpl.java:1102)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.java:1090)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:53)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$1.updateActionsImpl(ActionToolbarImpl.java:162)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:157)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2319)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:188)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:140)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:171)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:81)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.access$300(ToolbarUpdater.java:26)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyTimerListener.run(ToolbarUpdater.java:130)
	at com.intellij.openapi.actionSystem.impl.WeakTimerListener.run(WeakTimerListener.java:35)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.runListenerAction(ActionManagerImpl.java:1675)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.notifyListeners(ActionManagerImpl.java:1664)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1648)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

My Project structure
src/main/resources/icons/\*.png
src/main/java/name/admitriev/jhelper/\*.java

```
<action
	id="name.admitriev.jhelper.actions.CopySourceAction"
	class="name.admitriev.jhelper.actions.CopySourceAction"
	text="Copy source"
	description="Copies source of output file"
	icon="/icons/copy.png"
/>
```

**Comment by YannCebron** [comment]
How is this related to gradle plugin? Please follow guide from here https://www.jetbrains.org/intellij/sdk/docs/reference_guide/work_with_icons_and_images.html

if it still doesn't work, use channels listed here https://www.jetbrains.org/intellij/sdk/docs/intro/getting_help.html#problems-with-code---support-issues and provide a full project to reproduce.

**Comment by rishabhdeepsingh** [comment]
Thanks a lot Got it working now
