### ISSUE TITLE
Plagin build fails with NPE on buildSearchOptions step

### ISSUE THREAD

**Issue by MikhailShumenko** [JetBrains/gradle-intellij-plugin#498]
Showing the recent process error output.  Show more
[00:44:59][:buildSearchableOptions] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[00:44:59][:buildSearchableOptions] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:44:59][:buildSearchableOptions] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[00:44:59][:buildSearchableOptions] 	at com.intellij.util.pico.InstantiatingComponentAdapter.newInstance(CachingConstructorInjectionComponentAdapter.java:294)
[00:44:59][:buildSearchableOptions] 	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:88)
[00:44:59][:buildSearchableOptions] 	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
[00:44:59][:buildSearchableOptions] 	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:103)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:97)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:400)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:309)
[00:44:59][:buildSearchableOptions] 	at com.intellij.remoteServer.impl.configuration.RemoteServerListConfigurableProvider.tryGetServerTypes(RemoteServerListConfigurableProvider.java:54)
[00:44:59][:buildSearchableOptions] 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
[00:44:59][:buildSearchableOptions] 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[00:44:59][:buildSearchableOptions] 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[00:44:59][:buildSearchableOptions] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[00:44:59][:buildSearchableOptions] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[00:44:59][:buildSearchableOptions] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[00:44:59][:buildSearchableOptions] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[00:44:59][:buildSearchableOptions] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
[00:44:59][:buildSearchableOptions] 	at com.intellij.remoteServer.impl.configuration.RemoteServerListConfigurableProvider.getServerTypesInCloudsList(RemoteServerListConfigurableProvider.java:35)
[00:44:59][:buildSearchableOptions] 	at com.intellij.remoteServer.impl.configuration.RemoteServerListConfigurableProvider.canCreateConfigurable(RemoteServerListConfigurableProvider.java:22)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.options.ConfigurableEP$ProviderProducer.canCreateElement(ConfigurableEP.java:384)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.options.ConfigurableEP.canCreateConfigurable(ConfigurableEP.java:342)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.options.ex.ConfigurableWrapper.wrapConfigurable(ConfigurableWrapper.java:34)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurables(ConfigurableExtensionPointUtil.java:369)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.lambda$getConfigurableGroup$0(ConfigurableExtensionPointUtil.java:128)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.util.ClearableLazyValue$2.compute(ClearableLazyValue.java:30)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:45)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.util.AtomicClearableLazyValue.getValue(AtomicClearableLazyValue.java:21)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.options.ex.EpBasedConfigurableGroup.<init>(EpBasedConfigurableGroup.kt:100)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:127)
[00:44:59][:buildSearchableOptions] 	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurables(ShowSettingsUtilImpl.java:61)
[00:44:59][:buildSearchableOptions] 	at com.intellij.ide.ui.search.SearchUtil.processProjectConfigurables(SearchUtil.java:49)
[00:44:59][:buildSearchableOptions] 	at com.intellij.ide.ui.search.TraverseUIStarter.startup(TraverseUIStarter.java:97)
[00:44:59][:buildSearchableOptions] 	at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:80)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.application.ApplicationStarter.main(ApplicationStarter.java:62)
[00:44:59][:buildSearchableOptions] 	at com.intellij.idea.ApplicationLoader$startApp$8$1$1.run(ApplicationLoader.kt:228)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
[00:44:59][:buildSearchableOptions] 	at com.intellij.idea.ApplicationLoader$startApp$8$1.run(ApplicationLoader.kt:227)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
[00:44:59][:buildSearchableOptions] 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
[00:44:59][:buildSearchableOptions] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
[00:44:59][:buildSearchableOptions] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
[00:44:59][:buildSearchableOptions] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
[00:44:59][:buildSearchableOptions] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[00:44:59][:buildSearchableOptions] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[00:44:59][:buildSearchableOptions] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
[00:44:59][:buildSearchableOptions] 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
[00:44:59][:buildSearchableOptions] 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
[00:44:59][:buildSearchableOptions] 	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
[00:44:59][:buildSearchableOptions] 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
[00:44:59][:buildSearchableOptions] 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
[00:44:59][:buildSearchableOptions] 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
[00:44:59][:buildSearchableOptions] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[00:44:59][:buildSearchableOptions] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[00:44:59][:buildSearchableOptions] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[00:44:59][:buildSearchableOptions] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[00:44:59][:buildSearchableOptions] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[00:44:59][:buildSearchableOptions] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[00:44:59][:buildSearchableOptions] Caused by: java.lang.reflect.InvocationTargetException
[00:44:59][:buildSearchableOptions] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[00:44:59][:buildSearchableOptions] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[00:44:59][:buildSearchableOptions] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:44:59][:buildSearchableOptions] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[00:44:59][:buildSearchableOptions] 	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
[00:44:59][:buildSearchableOptions] 	... 97 more
[00:44:59][:buildSearchableOptions] Caused by: java.lang.NullPointerException
[00:44:59][:buildSearchableOptions] 	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
[00:44:59][:buildSearchableOptions] 	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
[00:44:59][:buildSearchableOptions] 	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
[00:44:59][:buildSearchableOptions] 	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
[00:44:59][:buildSearchableOptions] 	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:472)
[00:44:59][:buildSearchableOptions] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[00:44:59][:buildSearchableOptions] 	at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:418)
[00:44:59][:buildSearchableOptions] 	at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
[00:44:59][:buildSearchableOptions] 	at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
[00:44:59][:buildSearchableOptions] 	... 102 more
[00:45:01]
[00:45:01]Process exited with code 1
[00:45:01]Gradle failure report
[00:45:01][Gradle failure report] FAILURE: Build failed with an exception.
[00:45:01][Gradle failure report] 
[00:45:01][Gradle failure report] * What went wrong:
[00:45:01][Gradle failure report] Execution failed for task ':buildSearchableOptions'.
[00:45:01][Gradle failure report] > Process 'command '/root/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr-11_0_6-linux-x64-b765.25/jbr/bin/java'' finished with non-zero exit value 255
[00:45:01][Gradle failure report] 
[00:45:01][Gradle failure report] * Try:
[00:45:01][Gradle failure report] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[00:45:01][Gradle failure report] 
[00:45:01][Gradle failure report] * Get more help at https://help.gradle.org
[00:45:01][Gradle failure report] 
[00:45:01][Gradle failure report] BUILD FAILED in 56s

**Comment by zolotov** [comment]
Can you recreate it if you open RemoteServerListConfigurableProvider configurable manually in the debug IDE instance? What IDE version you use for building?

**Comment by MikhailShumenko** [comment]
We used 2020.1 

This error from our CI process, it is not clear for me what should I open?

```
 intellij {
    type = 'IU'
    version = '2020.1'
    updateSinceUntilBuild = false
    sandboxDirectory = "$buildDir/idea-sandbox"
  }
```

**Comment by zolotov** [comment]
> This error from our CI process

so can you recreate it locally?

>  it is not clear for me what should I open?

Run your plugin, open the settings and find `RemoteServerListConfigurableProvider` page. Depending on the plugins set, it will be named `Clouds` or `Google App Engine`, or `CloudFoundry`, or `Docker`, then check whether the exception will be logged.

**Comment by abrooksv** [comment]
Going to chime in, we have seen this on our internal build fleet.

This is caused by fonts not being installed into the OS image.

`apt-get intall fontconfig fonts` should fix it.

**Comment by MikhailShumenko** [comment]
Only docker is presented.

![image](https://user-images.githubusercontent.com/4786289/84590441-490d4300-ae3f-11ea-9610-a64432f3a03e.png)

No errors in idea.log

**Comment by zolotov** [comment]
@MikhailShumenko could you try to install fonts and libfontconfig1 on build agents as Austin suggested?

**Comment by MikhailShumenko** [comment]
@zolotov DevOps set CI environment 1 year ago and we don't change it, I would prefer to disable buildSearchOptions because I don't need it. Could you advise how to disable it?

**Comment by YannCebron** [comment]
@MikhailShumenko https://github.com/JetBrains/gradle-intellij-plugin/blob/master/FAQ.md#how-to-disable-building-searchable-options

**Comment by MikhailShumenko** [comment]
Could we fix that situation and prevent the case that we need "patch" our build agents?

**Comment by zolotov** [comment]
no idea, the issue looks similar though: https://youtrack.jetbrains.com/issue/IDEA-183679
