### ISSUE TITLE
v0.0.34 fails on Java 8

### ISSUE THREAD

**Issue by Turbo87** [JetBrains/gradle-intellij-plugin#50]
```
* What went wrong:
A problem occurred configuring root project 'intellij-rust'.
> Could not create task of type 'RunIdeaTask'.

Caused by: java.lang.NoClassDefFoundError: java/util/HashMap$Entry
	at org.jetbrains.intellij.RunIdeaTask$1.$getStaticMetaClass(RunIdeaTask.groovy)
	at org.jetbrains.intellij.RunIdeaTask$1.<init>(RunIdeaTask.groovy)
	at org.jetbrains.intellij.RunIdeaTask.<init>(RunIdeaTask.groovy:11)
	at org.jetbrains.intellij.RunIdeaTask_Decorated.<init>(Unknown Source)
	at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:48)
```

This [occured](https://travis-ci.org/intellij-rust/intellij-rust/builds/96368060) on the `intellij-rust` project with `0.0.34` of this plugin (see https://github.com/intellij-rust/intellij-rust/pull/179). Using `0.0.33` it seems to work [fine](https://travis-ci.org/intellij-rust/intellij-rust/builds/96375383). `intellij-rust` is compiling and running Gradle with Java 8.

I'm using `0.0.34` [without any issues](https://travis-ci.org/Turbo87/intellij-emberjs/builds/96367782) on `intellij-emberjs` but with Java 7 instead.

**Comment by zolotov** [comment]
Please try 0.0.35
