### ISSUE TITLE
`Action` classes is missing

### ISSUE THREAD

**Issue by izhangzhihao** [JetBrains/gradle-intellij-plugin#515]
I made a copy of the stream debugger, I want to create something similar. So I just take the code from https://github.com/JetBrains/intellij-community

And I did turn it into a gradle project, it all looks fine(gradle compileKotlin passed).
And I changed the package name to com.izhangzhihao.something so there should no package conflict(and plugin id)

And if I run gradle buildPlugin, I will get this error

```
Caused by: java.lang.ClassNotFoundException: com.github.izhangzhihao.visual.debugger.action.TraceStreamAction PluginClassLoader[izhangzhihao.rainbow.visual.debugger, 1.0.0] com.intellij.ide.plugins.cl.PluginClassLoader@6dcc367
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:190)
        ... 76 more
```

Yes, if I add `buildSearchableOptions.enabled = false` to gradle file, `gradle buildPlugin` works fine, but if I run `gradle runide`, the error happened again! And I unzipped the plugin package, and I found that the `action` package does not exist in the jar file at all! it's there anything I did wrong?

The code is here: https://github.com/izhangzhihao/intellij-visual-debugger

**Comment by izhangzhihao** [comment]
Fixed by adding:
```
sourceSets {
    main.java.srcDirs += 'src/main/kotlin'
}
```

**Comment by CJCrafter** [comment]
For kotlin
```
java.sourceSets["main"].java {
    srcDir("src/main/kotlin")
}
```
