### ISSUE TITLE
Latest version incompatible with Kotlin 1.4

### ISSUE THREAD

**Issue by amandeepg** [JetBrains/gradle-intellij-plugin#532]
We are using Kotlin 1.4 with serialization, with this plugin, so that brings in the dependencies `org.jetbrains.intellij.plugins:structure-intellij:3.105` (from the latest version of `gradle-intellij-plugin`) and `org.jetbrains.kotlinx:kotlinx-serialization-runtime:1.0-M1-1.4.0-rc` from Kotlin 1.4.

However this crashes during the configuration step with the following stack trace:
```
Caused by: java.lang.InstantiationError: kotlinx.serialization.json.Json	
	at com.jetbrains.plugin.structure.intellij.plugin.PluginCreator.<clinit>(PluginCreator.kt:45)	
	at com.jetbrains.plugin.structure.intellij.plugin.IdePluginManager.loadPluginInfoFromJarFile(IdePluginManager.java:109)	
	at com.jetbrains.plugin.structure.intellij.plugin.IdePluginManager.loadPluginInfoFromLibDirectory(IdePluginManager.java:213)	
	at com.jetbrains.plugin.structure.intellij.plugin.IdePluginManager.loadPluginInfoFromDirectory(IdePluginManager.java:152)	
	at com.jetbrains.plugin.structure.intellij.plugin.IdePluginManager.loadPluginInfoFromJarOrDirectory(IdePluginManager.java:312)	
	at com.jetbrains.plugin.structure.intellij.plugin.IdePluginManager.getPluginCreatorWithResult(IdePluginManager.java:448)	
	at com.jetbrains.plugin.structure.intellij.plugin.IdePluginManager.createPlugin(IdePluginManager.java:425)	
	at com.jetbrains.plugin.structure.intellij.plugin.IdePluginManager.createPlugin(IdePluginManager.java:418)	
	at com.jetbrains.plugin.structure.intellij.plugin.IdePluginManager$createPlugin$0.call(Unknown Source)	
	at org.jetbrains.intellij.Utils.createPlugin(Utils.groovy:324)	
	at org.jetbrains.intellij.Utils$createPlugin$5.call(Unknown Source)	
	at org.jetbrains.intellij.dependency.BuiltinPluginsRegistry.add(BuiltinPluginsRegistry.groovy:117)	
	at org.jetbrains.intellij.dependency.BuiltinPluginsRegistry$add$0.callCurrent(Unknown Source)	
	at org.jetbrains.intellij.dependency.BuiltinPluginsRegistry.fillFromDirectory(BuiltinPluginsRegistry.groovy:52)	
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
	at org.jetbrains.intellij.dependency.BuiltinPluginsRegistry.fromDirectory(BuiltinPluginsRegistry.groovy:22)	
	at org.jetbrains.intellij.dependency.BuiltinPluginsRegistry$fromDirectory.call(Unknown Source)	
	at org.jetbrains.intellij.dependency.IdeaDependencyManager.createDependency(IdeaDependencyManager.groovy:112)	
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
	at org.jetbrains.intellij.dependency.IdeaDependencyManager.resolveRemote(IdeaDependencyManager.groovy:63)	
	at org.jetbrains.intellij.dependency.IdeaDependencyManager$resolveRemote.call(Unknown Source)	
	at org.jetbrains.intellij.IntelliJPlugin.configureIntellijDependency(IntelliJPlugin.groovy:198)	
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
	at org.jetbrains.intellij.IntelliJPlugin.configureProjectAfterEvaluate(IntelliJPlugin.groovy:134)	
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
	at org.jetbrains.intellij.IntelliJPlugin$_configureTasks_closure4.doCall(IntelliJPlugin.groovy:119)	
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
	...
```

It appears that `structure-intellij:3.105` is build against Kotlin 1.3, causing this incompatibility. Upgrading the dependency to 1.4 in `structure-intellij` I believe should fix this. For now we have downgraded to `
gradle-intellij-plugin:0.4.18` as it doesn't use a version of `structure-intellij` incompatible with Kotlin 1.4.

Here's a screenshot of a Gradle scan showing the version upgrade done by Gradle during the build:
<img width="538" alt="Screen Shot 2020-09-09 at 1 49 13 PM" src="https://user-images.githubusercontent.com/984237/92636710-d1b44780-f2a5-11ea-9387-3670c2e119b3.png">

Also reported this to IntelliJ's YouTrack: https://youtrack.jetbrains.com/issue/IDEA-250454

**Comment by zolotov** [comment]
Could you provide steps to recreate the issue, please? I'm not quite understand how classpath of gradle-intellij-plugin affects the compile classpath of your project.

**Comment by amandeepg** [comment]
Sure, I've uploaded a project that has the configuration I specified, namely using the `org.jetbrains.intellij` plugin along with `kotlinx-serialization` in the `buildscript` using the latest version from https://github.com/Kotlin/kotlinx.serialization#dependency-on-the-runtime-library.

You can see the failure by running `rm -rf ~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ ; ./gradlew tasks --scan`, and I've uploaded the scan, here's a link to the scan, specifically to where it reports the version upgrade: https://scans.gradle.com/s/7icr64l5blqpe/build-dependencies?toggled=W1swXSxbMCwwXSxbMCwwLFsxXV0sWzAsMCxbMSwyXV0sWzAsMCxbMSwyLDM3XV0sWzAsMCxbMSwyLDM3LDQyXV1d

[gradle-intellij-plugin_issues_532.zip](https://github.com/JetBrains/gradle-intellij-plugin/files/5229772/gradle-intellij-plugin_issues_532.zip)
