### ISSUE TITLE
runPluginVerifier: java.nio.file.FileAlreadyExistsException as ERROR in logs

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/gradle-intellij-plugin#552]
See https://github.com/VirtusLab/git-machete-intellij-plugin/pull/637/files for a sample PR where this happens.

Full build logs can be seen under https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/3675/workflows/8c46c821-3518-4a1b-be9e-c03268609d37/jobs/3851 , step `Verify binary compatibility with supported IntelliJ versions` (failure of this pipeline is expected and **not** related to this very issue).

This might ofc be innocuous... at least if the verification-verdict.txt is always actually ensured to be up to date after the verification (and not corresponding to some old verifications insteads) :/

```
$ ./gradlew runPluginVerifier

> Task :buildSearchableOptions
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil to field java.awt.event.InvocationEvent.runnable
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-10-29 19:30:07,519 [   1023]   WARN - j.internal.DebugAttachDetector - Unable to start DebugAttachDetector, please add `--add-exports java.base/jdk.internal.vm=ALL-UNNAMED` to VM options 
Starting searchable options index builder
2020-10-29 19:30:08,226 [   1730]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting 
Searchable options index builder completed

> Task :runPluginVerifier FAILED
Starting the IntelliJ Plugin Verifier 1.252
2020-10-29T19:30:28 [main] INFO  c.j.p.options.OptionsParser - Delete the verification directory /home/pawellipski/git-machete-intellij-plugin/build/reports/pluginVerifier because it isn't empty
Verification reports directory: /home/pawellipski/git-machete-intellij-plugin/build/reports/pluginVerifier
2020-10-29T19:30:28 [main] INFO  verification - Reading IDE /home/pawellipski/.pluginVerifier/ides/IC-2020.1
2020-10-29T19:30:33 [main] INFO  verification - Reading IDE /home/pawellipski/.pluginVerifier/ides/IC-2020.1.4
2020-10-29T19:30:36 [main] INFO  verification - Reading IDE /home/pawellipski/.pluginVerifier/ides/IC-2020.2.3
2020-10-29T19:30:39 [main] INFO  verification - Reading IDE /home/pawellipski/.pluginVerifier/ides/IC-203.5251.39
2020-10-29T19:30:41 [main] INFO  verification - Reading plugin to check from /home/pawellipski/git-machete-intellij-plugin/build/distributions/git-machete-intellij-plugin-0.8.1-32-SNAPSHOT+git.6c1a6d8.zip
2020-10-29T19:30:43 [main] INFO  verification - Task check-plugin parameters:
Scheduled verifications (4):
com.virtuslab.git-machete:0.8.1-32-SNAPSHOT+git.6c1a6d8 against IC-202.7660.26, com.virtuslab.git-machete:0.8.1-32-SNAPSHOT+git.6c1a6d8 against IC-201.8743.12, com.virtuslab.git-machete:0.8.1-32-SNAPSHOT+git.6c1a6d8 against IC-202.7660.26, com.virtuslab.git-machete:0.8.1-32-SNAPSHOT+git.6c1a6d8 against IC-203.5251.39

2020-10-29T19:30:44 [main] INFO  verification - Finished 1 of 4 verifications (in 1.8 s): IC-201.8743.12 against com.virtuslab.git-machete:0.8.1-32-SNAPSHOT+git.6c1a6d8: Compatible. 1 usage of deprecated API
2020-10-29T19:30:45 [main] INFO  verification - Finished 2 of 4 verifications (in 1.9 s): IC-202.7660.26 against com.virtuslab.git-machete:0.8.1-32-SNAPSHOT+git.6c1a6d8: Compatible. 1 usage of deprecated API
2020-10-29T19:30:45 [verifier_3] ERROR c.j.p.reporting.common.FileReporter - Failed to open file writer for /home/pawellipski/git-machete-intellij-plugin/build/reports/pluginVerifier/IC-202.7660.26/plugins/com.virtuslab.git-machete/0.8.1-32-SNAPSHOT_git.6c1a6d8/verification-verdict.txt
java.nio.file.FileAlreadyExistsException: /home/pawellipski/git-machete-intellij-plugin/build/reports/pluginVerifier/IC-202.7660.26/plugins/com.virtuslab.git-machete/0.8.1-32-SNAPSHOT_git.6c1a6d8/verification-verdict.txt
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.createFile(Files.java:647)
        at com.jetbrains.plugin.structure.base.utils.FileUtilKt.create(FileUtil.kt:70)
        at com.jetbrains.pluginverifier.reporting.common.FileReporter.openFileWriter(FileReporter.kt:31)
        at com.jetbrains.pluginverifier.reporting.common.FileReporter.report(FileReporter.kt:44)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.useReporter(DirectoryBasedPluginVerificationReportage.kt:99)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationDetails(DirectoryBasedPluginVerificationReportage.kt:141)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationResult(DirectoryBasedPluginVerificationReportage.kt:108)
        at com.jetbrains.pluginverifier.PluginVerifierRunKt$runSeveralVerifiers$$inlined$map$lambda$1.call(PluginVerifierRun.kt:29)
        at com.jetbrains.pluginverifier.PluginVerifierRunKt$runSeveralVerifiers$$inlined$map$lambda$1.call(PluginVerifierRun.kt)
        at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:131)
        at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:125)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-10-29T19:30:45 [verifier_3] ERROR c.j.p.reporting.common.FileReporter - Failed to open file writer for /home/pawellipski/git-machete-intellij-plugin/build/reports/pluginVerifier/IC-202.7660.26/plugins/com.virtuslab.git-machete/0.8.1-32-SNAPSHOT_git.6c1a6d8/dependencies.txt
java.nio.file.FileAlreadyExistsException: /home/pawellipski/git-machete-intellij-plugin/build/reports/pluginVerifier/IC-202.7660.26/plugins/com.virtuslab.git-machete/0.8.1-32-SNAPSHOT_git.6c1a6d8/dependencies.txt
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.createFile(Files.java:647)
        at com.jetbrains.plugin.structure.base.utils.FileUtilKt.create(FileUtil.kt:70)
        at com.jetbrains.pluginverifier.reporting.common.FileReporter.openFileWriter(FileReporter.kt:31)
        at com.jetbrains.pluginverifier.reporting.common.FileReporter.report(FileReporter.kt:44)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.useReporter(DirectoryBasedPluginVerificationReportage.kt:99)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationDetails(DirectoryBasedPluginVerificationReportage.kt:141)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationResult(DirectoryBasedPluginVerificationReportage.kt:114)
        at com.jetbrains.pluginverifier.PluginVerifierRunKt$runSeveralVerifiers$$inlined$map$lambda$1.call(PluginVerifierRun.kt:29)
        at com.jetbrains.pluginverifier.PluginVerifierRunKt$runSeveralVerifiers$$inlined$map$lambda$1.call(PluginVerifierRun.kt)
        at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:131)
        at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:125)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-10-29T19:30:45 [verifier_3] ERROR c.j.p.reporting.common.FileReporter - Failed to open file writer for /home/pawellipski/git-machete-intellij-plugin/build/reports/pluginVerifier/IC-202.7660.26/plugins/com.virtuslab.git-machete/0.8.1-32-SNAPSHOT_git.6c1a6d8/deprecated-usages.txt
java.nio.file.FileAlreadyExistsException: /home/pawellipski/git-machete-intellij-plugin/build/reports/pluginVerifier/IC-202.7660.26/plugins/com.virtuslab.git-machete/0.8.1-32-SNAPSHOT_git.6c1a6d8/deprecated-usages.txt
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.createFile(Files.java:647)
        at com.jetbrains.plugin.structure.base.utils.FileUtilKt.create(FileUtil.kt:70)
        at com.jetbrains.pluginverifier.reporting.common.FileReporter.openFileWriter(FileReporter.kt:31)
        at com.jetbrains.pluginverifier.reporting.common.FileReporter.report(FileReporter.kt:44)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.useReporter(DirectoryBasedPluginVerificationReportage.kt:99)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationDetails(DirectoryBasedPluginVerificationReportage.kt:141)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationDetails$default(DirectoryBasedPluginVerificationReportage.kt:139)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationResult(DirectoryBasedPluginVerificationReportage.kt:115)
        at com.jetbrains.pluginverifier.PluginVerifierRunKt$runSeveralVerifiers$$inlined$map$lambda$1.call(PluginVerifierRun.kt:29)
        at com.jetbrains.pluginverifier.PluginVerifierRunKt$runSeveralVerifiers$$inlined$map$lambda$1.call(PluginVerifierRun.kt)
        at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:131)
        at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:125)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-10-29T19:30:45 [main] INFO  verification - Finished 3 of 4 verifications (in 1.9 s): IC-202.7660.26 against com.virtuslab.git-machete:0.8.1-32-SNAPSHOT+git.6c1a6d8: Compatible. 1 usage of deprecated API
2020-10-29T19:30:45 [main] INFO  verification - Finished 4 of 4 verifications (in 2.0 s): IC-203.5251.39 against com.virtuslab.git-machete:0.8.1-32-SNAPSHOT+git.6c1a6d8: Compatible. 25 usages of scheduled for removal API and 3 usages of deprecated API
```

**Comment by hsz** [comment]
That issue is related to #553 - because IDEs incorrectly resolved to the latest stable version, which is currently `IC-202.7660.26` - we run into a situation that one version is used more than once to test your plugin.
Plugin Verifier tries to generate such a report into the same directory.

In addition, I've applied proper checks to avoid providing duplicated versions.
