### ISSUE TITLE
Issues #552 and #553 persist in v0.6.2

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/gradle-intellij-plugin#560]
When running `./gradlew runPluginVerifier` on https://github.com/VirtusLab/git-machete-intellij-plugin/pull/637/files (which uses v0.6.2 as of commit `140f2a3070308bce9978bc0f305a0a0c976647a0`) , I'm getting the following output:

```
$ ./gradlew runPluginVerifier 

> Task :frontendFile:generateMacheteParser
WARN: The registry key 'psi.track.invalidation' accessed, but not loaded yet
WARN: The registry key 'psi.incremental.reparse.depth.limit' accessed, but not loaded yet
Machete.bnf parser generated to /home/pawellipski/git-machete-intellij-plugin/frontendFile/build/generated

> Task :frontendFile:generateMacheteLexer
Reading "/home/pawellipski/git-machete-intellij-plugin/frontendFile/src/main/grammar/Machete.flex"
Constructing NFA : 48 states in NFA
Converting NFA to DFA : 
..................
26 states before minimization, 13 states in minimized DFA
Writing code to "/home/pawellipski/git-machete-intellij-plugin/frontendFile/build/generated/com/virtuslab/gitmachete/frontend/file/grammar/MacheteGeneratedLexer.java"

> Task :buildSearchableOptions
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil to field java.awt.event.InvocationEvent.runnable
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-11-05 16:11:09,285 [   1677]   WARN - j.internal.DebugAttachDetector - Unable to start DebugAttachDetector, please add `--add-exports java.base/jdk.internal.vm=ALL-UNNAMED` to VM options 
Starting searchable options index builder
2020-11-05 16:11:10,917 [   3309]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting 
Searchable options index builder completed

> Task :runPluginVerifier FAILED
Starting the IntelliJ Plugin Verifier 1.252
Verification reports directory: /home/pawellipski/git-machete-intellij-plugin/build/reports/pluginVerifier
2020-11-05T16:11:48 [main] INFO  verification - Reading IDE /home/pawellipski/.pluginVerifier/ides/IC-2020.1
2020-11-05T16:11:55 [main] INFO  verification - Reading IDE /home/pawellipski/.pluginVerifier/ides/IC-2020.1.4
2020-11-05T16:12:00 [main] INFO  verification - Reading IDE /home/pawellipski/.pluginVerifier/ides/IC-2020.2.3
2020-11-05T16:12:04 [main] INFO  verification - Reading IDE /home/pawellipski/.pluginVerifier/ides/IC-203.5419.21
2020-11-05T16:12:09 [main] INFO  verification - Reading plugin to check from /home/pawellipski/git-machete-intellij-plugin/build/distributions/git-machete-intellij-plugin-0.8.1-27-SNAPSHOT+git.c72f4ee-dirty.zip
2020-11-05T16:12:12 [main] INFO  verification - Task check-plugin parameters:
Scheduled verifications (4):
com.virtuslab.git-machete:0.8.1-27-SNAPSHOT+git.c72f4ee-dirty against IC-202.7660.26, com.virtuslab.git-machete:0.8.1-27-SNAPSHOT+git.c72f4ee-dirty against IC-201.8743.12, com.virtuslab.git-machete:0.8.1-27-SNAPSHOT+git.c72f4ee-dirty against IC-202.7660.26, com.virtuslab.git-machete:0.8.1-27-SNAPSHOT+git.c72f4ee-dirty against IC-203.5419.21

2020-11-05T16:12:15 [main] INFO  verification - Finished 1 of 4 verifications (in 2.6 s): IC-202.7660.26 against com.virtuslab.git-machete:0.8.1-27-SNAPSHOT+git.c72f4ee-dirty: Compatible. 1 usage of deprecated API
2020-11-05T16:12:15 [main] INFO  verification - Finished 2 of 4 verifications (in 2.6 s): IC-203.5419.21 against com.virtuslab.git-machete:0.8.1-27-SNAPSHOT+git.c72f4ee-dirty: Compatible. 25 usages of scheduled for removal API and 2 usages of deprecated API
2020-11-05T16:12:15 [verifier_1] ERROR c.j.p.reporting.common.FileReporter - Failed to open file writer for /home/pawellipski/git-machete-intellij-plugin/build/reports/pluginVerifier/IC-202.7660.26/plugins/com.virtuslab.git-machete/0.8.1-27-SNAPSHOT_git.c72f4ee-dirty/verification-verdict.txt
java.nio.file.FileAlreadyExistsException: /home/pawellipski/git-machete-intellij-plugin/build/reports/pluginVerifier/IC-202.7660.26/plugins/com.virtuslab.git-machete/0.8.1-27-SNAPSHOT_git.c72f4ee-dirty/verification-verdict.txt
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.createFile(Files.java:647)
        at com.jetbrains.plugin.structure.base.utils.FileUtilKt.create(FileUtil.kt:70)
        at com.jetbrains.pluginverifier.reporting.common.FileReporter.openFileWriter(FileReporter.kt:31)
        at com.jetbrains.pluginverifier.reporting.common.FileReporter.report(FileReporter.kt:44)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.useReporter(DirectoryBasedPluginVerificationReportage.kt:99)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationDetails(DirectoryBasedPluginVerificationReportage.kt:141)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationResult(DirectoryBasedPluginVerificationReportage.kt:108)
        at com.jetbrains.pluginverifier.PluginVerifierRunKt$runSeveralVerifiers$$inlined$map$lambda$1.call(PluginVerifierRun.kt:29)
        at com.jetbrains.pluginverifier.PluginVerifierRunKt$runSeveralVerifiers$$inlined$map$lambda$1.call(PluginVerifierRun.kt)
        at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:131)
        at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:125)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-05T16:12:15 [verifier_1] ERROR c.j.p.reporting.common.FileReporter - Failed to open file writer for /home/pawellipski/git-machete-intellij-plugin/build/reports/pluginVerifier/IC-202.7660.26/plugins/com.virtuslab.git-machete/0.8.1-27-SNAPSHOT_git.c72f4ee-dirty/dependencies.txt
java.nio.file.FileAlreadyExistsException: /home/pawellipski/git-machete-intellij-plugin/build/reports/pluginVerifier/IC-202.7660.26/plugins/com.virtuslab.git-machete/0.8.1-27-SNAPSHOT_git.c72f4ee-dirty/dependencies.txt
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.createFile(Files.java:647)
        at com.jetbrains.plugin.structure.base.utils.FileUtilKt.create(FileUtil.kt:70)
        at com.jetbrains.pluginverifier.reporting.common.FileReporter.openFileWriter(FileReporter.kt:31)
        at com.jetbrains.pluginverifier.reporting.common.FileReporter.report(FileReporter.kt:44)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.useReporter(DirectoryBasedPluginVerificationReportage.kt:99)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationDetails(DirectoryBasedPluginVerificationReportage.kt:141)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationResult(DirectoryBasedPluginVerificationReportage.kt:114)
        at com.jetbrains.pluginverifier.PluginVerifierRunKt$runSeveralVerifiers$$inlined$map$lambda$1.call(PluginVerifierRun.kt:29)
        at com.jetbrains.pluginverifier.PluginVerifierRunKt$runSeveralVerifiers$$inlined$map$lambda$1.call(PluginVerifierRun.kt)
        at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:131)
        at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:125)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-05T16:12:15 [verifier_1] ERROR c.j.p.reporting.common.FileReporter - Failed to open file writer for /home/pawellipski/git-machete-intellij-plugin/build/reports/pluginVerifier/IC-202.7660.26/plugins/com.virtuslab.git-machete/0.8.1-27-SNAPSHOT_git.c72f4ee-dirty/deprecated-usages.txt
java.nio.file.FileAlreadyExistsException: /home/pawellipski/git-machete-intellij-plugin/build/reports/pluginVerifier/IC-202.7660.26/plugins/com.virtuslab.git-machete/0.8.1-27-SNAPSHOT_git.c72f4ee-dirty/deprecated-usages.txt
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.createFile(Files.java:647)
        at com.jetbrains.plugin.structure.base.utils.FileUtilKt.create(FileUtil.kt:70)
        at com.jetbrains.pluginverifier.reporting.common.FileReporter.openFileWriter(FileReporter.kt:31)
        at com.jetbrains.pluginverifier.reporting.common.FileReporter.report(FileReporter.kt:44)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.useReporter(DirectoryBasedPluginVerificationReportage.kt:99)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationDetails(DirectoryBasedPluginVerificationReportage.kt:141)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationDetails$default(DirectoryBasedPluginVerificationReportage.kt:139)
        at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationResult(DirectoryBasedPluginVerificationReportage.kt:115)
        at com.jetbrains.pluginverifier.PluginVerifierRunKt$runSeveralVerifiers$$inlined$map$lambda$1.call(PluginVerifierRun.kt:29)
        at com.jetbrains.pluginverifier.PluginVerifierRunKt$runSeveralVerifiers$$inlined$map$lambda$1.call(PluginVerifierRun.kt)
        at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:131)
        at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:125)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-05T16:12:15 [main] INFO  verification - Finished 3 of 4 verifications (in 2.6 s): IC-202.7660.26 against com.virtuslab.git-machete:0.8.1-27-SNAPSHOT+git.c72f4ee-dirty: Compatible. 1 usage of deprecated API
2020-11-05T16:12:15 [main] INFO  verification - Finished 4 of 4 verifications (in 2.6 s): IC-201.8743.12 against com.virtuslab.git-machete:0.8.1-27-SNAPSHOT+git.c72f4ee-dirty: Compatible. 1 usage of deprecated API
Plugin com.virtuslab.git-machete:0.8.1-27-SNAPSHOT+git.c72f4ee-dirty against IC-202.7660.26: Compatible. 1 usage of deprecated API
Deprecated API usages (1): 
    #Deprecated method com.intellij.openapi.externalSystem.settings.AbstractExternalSystemSettings.subscribe(ExternalSystemSettingsListener) is overridden
        Deprecated method com.intellij.openapi.externalSystem.settings.AbstractExternalSystemSettings.subscribe(com.intellij.openapi.externalSystem.settings.ExternalSystemSettingsListener arg0) : void is overridden in class com.virtuslab.gitmachete.frontend.externalsystem.settings.MacheteSettings
    Plugin can be loaded/unloaded without IDE restart

Plugin com.virtuslab.git-machete:0.8.1-27-SNAPSHOT+git.c72f4ee-dirty against IC-203.5419.21: Compatible. 25 usages of scheduled for removal API and 2 usages of deprecated API
Deprecated API usages (27): 
    #Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyWarning(String, String) invocation
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyWarning(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.vcsmenu.OpenMacheteTabAction.lambda$actionPerformed$0(Project) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyWarning(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.base.BaseResetBranchToRemoteAction.actionPerformed(AnActionEvent) : void. This method will be removed in 2020.4
    #Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyError(String, String) invocation
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyError(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.base.BaseResetBranchToRemoteAction.actionPerformed(AnActionEvent) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyError(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.backgroundables.SlideInBackgroundable.lambda$run$1(Throwable) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyError(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.unanchored.DiscoverAction.saveDiscoveredLayout(IGitMacheteRepositorySnapshot, Path, Project, BaseEnhancedGraphTable, IBranchLayoutWriter) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyError(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.toolbar.OpenMacheteFileAction.actionPerformed(AnActionEvent) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyError(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.base.BaseSlideInBranchBelowAction.actionPerformed(AnActionEvent) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyError(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.base.BaseSlideOutBranchAction.doSlideOut(AnActionEvent, IManagedBranchSnapshot) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyError(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.backgroundables.SlideInBackgroundable.notifyError(String, Throwable) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyError(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.unanchored.DiscoverAction.actionPerformed(AnActionEvent) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyError(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.unanchored.DiscoverAction.lambda$openMacheteFile$6(GitRepository, Project) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyError(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.unanchored.DiscoverAction.lambda$actionPerformed$2(Project, Throwable) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyError(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.base.BaseResetBranchToRemoteAction$1.run(ProgressIndicator) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyError(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.unanchored.DiscoverAction$1.lambda$run$1(Project, Throwable) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyError(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.base.BaseRebaseBranchOntoParentAction.doRebase(Project, GitRepository, IGitMacheteRepositorySnapshot, INonRootManagedBranchSnapshot, boolean) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyError(java.lang.String title, java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.base.BaseRebaseBranchOntoParentAction$1.run(ProgressIndicator) : void. This method will be removed in 2020.4
    #Deprecated method git4idea.util.GitUIUtil.notifyError(Project, String, String, boolean, Exception) invocation
        Deprecated method git4idea.util.GitUIUtil.notifyError(com.intellij.openapi.project.Project project, java.lang.String title, java.lang.String description, boolean important, java.lang.Exception error) : void is invoked in com.virtuslab.gitmachete.frontend.actions.backgroundables.GitCommandUpdatingCurrentBranchBackgroundable.handleResult(GitCommandResult, GitLocalChangesWouldBeOverwrittenDetector, GitUntrackedFilesOverwrittenByOperationDetector, GitRevisionNumber, Label, GitUpdatedRanges) : void
    #Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifySuccess(String) invocation
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifySuccess(java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.base.BaseSlideOutBranchAction.deleteBranchIfRequired(AnActionEvent, String) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifySuccess(java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.backgroundables.FetchBackgroundable.onSuccess() : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifySuccess(java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.base.BaseResetBranchToRemoteAction$1.run(ProgressIndicator) : void. This method will be removed in 2020.4
    #Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyWeakError(String) invocation
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyWeakError(java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.toolbar.OpenMacheteFileAction.lambda$actionPerformed$1(Project, Throwable) : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyWeakError(java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.backgroundables.SlideInBackgroundable.waitForCreationOfLocalBranch() : void. This method will be removed in 2020.4
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyWeakError(java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.base.BaseSlideInBranchBelowAction.actionPerformed(AnActionEvent) : void. This method will be removed in 2020.4
    #Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyInfo(String) invocation
        Deprecated method com.intellij.openapi.vcs.VcsNotifier.notifyInfo(java.lang.String message) : com.intellij.notification.Notification is invoked in com.virtuslab.gitmachete.frontend.actions.base.BaseSlideInBranchBelowAction.getGitRemoteBranch(Project, GitRepository, String) : GitRemoteBranch. This method will be removed in 2020.4
    #Deprecated method com.intellij.openapi.externalSystem.settings.AbstractExternalSystemSettings.subscribe(ExternalSystemSettingsListener) is overridden
        Deprecated method com.intellij.openapi.externalSystem.settings.AbstractExternalSystemSettings.subscribe(com.intellij.openapi.externalSystem.settings.ExternalSystemSettingsListener arg0) : void is overridden in class com.virtuslab.gitmachete.frontend.externalsystem.settings.MacheteSettings
    #Deprecated method git4idea.util.LocalChangesWouldBeOverwrittenHelper.showErrorNotification(Project, VirtualFile, String, Collection) invocation
        Deprecated method git4idea.util.LocalChangesWouldBeOverwrittenHelper.showErrorNotification(com.intellij.openapi.project.Project project, com.intellij.openapi.vfs.VirtualFile root, java.lang.String operationName, java.util.Collection relativeFilePaths) : void is invoked in com.virtuslab.gitmachete.frontend.actions.backgroundables.GitCommandUpdatingCurrentBranchBackgroundable.handleResult(GitCommandResult, GitLocalChangesWouldBeOverwrittenDetector, GitUntrackedFilesOverwrittenByOperationDetector, GitRevisionNumber, Label, GitUpdatedRanges) : void. This method will be removed in 2020.4
        Deprecated method git4idea.util.LocalChangesWouldBeOverwrittenHelper.showErrorNotification(com.intellij.openapi.project.Project project, com.intellij.openapi.vfs.VirtualFile root, java.lang.String operationName, java.util.Collection relativeFilePaths) : void is invoked in com.virtuslab.gitmachete.frontend.actions.base.BaseResetBranchToRemoteAction$1.run(ProgressIndicator) : void. This method will be removed in 2020.4
    Plugin can be loaded/unloaded without IDE restart

Plugin com.virtuslab.git-machete:0.8.1-27-SNAPSHOT+git.c72f4ee-dirty against IC-202.7660.26: Compatible. 1 usage of deprecated API
Deprecated API usages (1): 
    #Deprecated method com.intellij.openapi.externalSystem.settings.AbstractExternalSystemSettings.subscribe(ExternalSystemSettingsListener) is overridden
        Deprecated method com.intellij.openapi.externalSystem.settings.AbstractExternalSystemSettings.subscribe(com.intellij.openapi.externalSystem.settings.ExternalSystemSettingsListener arg0) : void is overridden in class com.virtuslab.gitmachete.frontend.externalsystem.settings.MacheteSettings
    Plugin can be loaded/unloaded without IDE restart

Plugin com.virtuslab.git-machete:0.8.1-27-SNAPSHOT+git.c72f4ee-dirty against IC-201.8743.12: Compatible. 1 usage of deprecated API
Deprecated API usages (1): 
    #Deprecated method com.intellij.openapi.externalSystem.settings.AbstractExternalSystemSettings.subscribe(ExternalSystemSettingsListener) is overridden
        Deprecated method com.intellij.openapi.externalSystem.settings.AbstractExternalSystemSettings.subscribe(com.intellij.openapi.externalSystem.settings.ExternalSystemSettingsListener arg0) : void is overridden in class com.virtuslab.gitmachete.frontend.externalsystem.settings.MacheteSettings
    Plugin cannot be loaded/unloaded without IDE restart: Plugin cannot be loaded/unloaded without IDE restart because it declares non-dynamic extensions: `com.intellij.changesViewContent`, `com.intellij.externalIconProvider`, `com.intellij.externalSystemManager`

2020-11-05T16:12:15 [main] INFO  verification - Total time spent downloading plugins and their dependencies: 0 ms
2020-11-05T16:12:15 [main] INFO  verification - Total amount of plugins and dependencies downloaded: 0 B
2020-11-05T16:12:15 [main] INFO  verification - Total amount of space used for plugins and dependencies: 0 B


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runPluginVerifier'.
> DEPRECATED_API_USAGES

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2m 21s
84 actionable tasks: 67 executed, 17 from cache
```

**Comment by PawelLipski** [comment]
Ok, hopefully some caching issue, coz CI doesn't show the same output :thinking:

**Comment by PawelLipski** [comment]
(https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/3700/workflows/11535b73-09af-44fc-b30e-0ee1710095f3/jobs/3876)

**Comment by hsz** [comment]
> Caused by: org.gradle.api.GradleException: IDE '2020.1' cannot be downloaded. Please verify the specified IDE version against the products available for testing: https://jb.gg/intellij-platform-builds-list
