### ISSUE TITLE
"Language with ID 'PHP' is already registered" on last EAP-SNAPSHOT

### ISSUE THREAD

**Issue by negram** [JetBrains/gradle-intellij-plugin#563]
Hi there, 

Recent updates in PhpStorm 2020.3 EAP and the plugin turned all tests into a pumkin. 

One of the exceptions I get:

```
...
                java.lang.ExceptionInInitializerError
                    at com.jetbrains.php.lang.psi.PhpElementType.<init>(PhpElementType.java:22)
                    at com.jetbrains.php.lang.lexer.PhpTokenTypes.<clinit>(PhpTokenTypes.java:23)
                    at com.badoo.component.plugin.cpq.CpqEventLineMarkerProvider.<init>(CpqEventLineMarkerProvider.kt:13)
                    ... 23 more
                    Caused by:
                    com.intellij.diagnostic.ImplementationConflictException: Language with ID 'PHP' is already registered: class com.jetbrains.php.lang.PhpLanguage
                        at com.intellij.lang.Language.<init>(Language.java:84)
                        at com.intellij.lang.Language.<init>(Language.java:60)
                        at com.intellij.lang.Language.<init>(Language.java:56)
                        at com.jetbrains.php.lang.PhpLanguage.<init>(PhpLanguage.java:26)
                        at com.jetbrains.php.lang.PhpLanguage.<clinit>(PhpLanguage.java:22)
```

Unfortunately, it's really hard to extract isolated example but this particular failure can be reproduced by running
```
./gradlew test --tests CpqEventLineMarkerProviderTest
```
In the attached archive:
[untitled3.tar.gz](https://github.com/JetBrains/gradle-intellij-plugin/files/5513181/untitled3.tar.gz)

**Comment by zolotov** [comment]
should be fixed in 0.6.3 for the next IDE EAP build
