### ISSUE TITLE
`java.lang.RuntimeException: Memory leak detected` in buildSearchableOptions for 2020.3

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/gradle-intellij-plugin#576]
It doesn't crash the app, just gets logged as `ERROR`.

Output on CI: https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/3762/workflows/39b9588a-7182-4a43-84c4-578b35c81c38/jobs/3946/parallel-runs/0/steps/0-119

<details><summary>Full stack trace</summary>
<pre>
2020-12-06 13:25:13,827 [  15348]  ERROR - tellij.openapi.util.ObjectTree - Memory leak detected: 'org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab@6bf9746' of class org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab
See the cause for the corresponding Disposer.register() stacktrace: 
java.lang.RuntimeException: Memory leak detected: 'org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab@6bf9746' of class org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab
See the cause for the corresponding Disposer.register() stacktrace:
	at com.intellij.openapi.util.ObjectTree.assertIsEmpty(ObjectTree.java:223)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:156)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeContainer(ApplicationImpl.java:198)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:215)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:621)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:580)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:569)
	at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:82)
	at com.intellij.idea.ApplicationLoader$startApp$8$1$1.run(ApplicationLoader.kt:245)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.idea.ApplicationLoader$startApp$8$1.run(ApplicationLoader.kt:244)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.Throwable
	at com.intellij.openapi.util.ObjectNode.<init>(ObjectNode.java:31)
	at com.intellij.openapi.util.ObjectTree.createNodeFor(ObjectTree.java:99)
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:60)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:73)
	at com.intellij.openapi.ui.ComponentValidator.installOn(ComponentValidator.java:154)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab.createVersionValidator(KotlinCompilerConfigurableTab.java:776)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab.createUIComponents(KotlinCompilerConfigurableTab.java:751)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab.$$$setupUI$$$(KotlinCompilerConfigurableTab.java)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab.<init>(KotlinCompilerConfigurableTab.java:131)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab.<init>(KotlinCompilerConfigurableTab.java:174)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:704)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateExtensionWithPicoContainerOnlyIfNeeded(ComponentManagerImpl.kt:754)
	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:425)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:332)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createConfigurable(ConfigurableWrapper.java:45)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:119)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:171)
	at com.intellij.ide.ui.search.SearchUtil.processConfigurables(SearchUtil.java:81)
	at com.intellij.ide.ui.search.SearchUtil.processProjectConfigurables(SearchUtil.java:51)
	at com.intellij.ide.ui.search.TraverseUIStarter.startup(TraverseUIStarter.java:98)
	at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:81)
	... 32 more
2020-12-06 13:25:13,829 [  15350]  ERROR - tellij.openapi.util.ObjectTree - IntelliJ IDEA 2020.3  Build #IC-203.5981.155 
2020-12-06 13:25:13,830 [  15351]  ERROR - tellij.openapi.util.ObjectTree - JDK: 11.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-12-06 13:25:13,830 [  15351]  ERROR - tellij.openapi.util.ObjectTree - OS: Linux 
2020-12-06 13:25:13,831 [  15352]  ERROR - tellij.openapi.util.ObjectTree - Plugin to blame: Kotlin version: 203-1.4.10-release-IJ5981.133 
</pre>
</details>

**Comment by zolotov** [comment]
duplicates https://youtrack.jetbrains.com/issue/KT-42837
