### ISSUE TITLE
Failed to invoke Resolve dependency com.intellij.database in 5 attempts

### ISSUE THREAD

**Issue by izhangzhihao** [JetBrains/gradle-intellij-plugin#624]
```
> Task :runPluginVerifier
Download https://cache-redirector.jetbrains.com/download.jetbrains.com/webstorm/WebStorm-2020.3.tar.gz
Download https://cache-redirector.jetbrains.com/download.jetbrains.com/idea/ideaIC-2021.1.tar.gz
Error: Exception in thread "main" java.lang.RuntimeException: Worker 'izhangzhihao.rainbow.brackets:6.17 against IC-211.6693.111' finished with error
	at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress.waitAllFutures(ConcurrencyUtils.kt:95)
	at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress.executeTasks(ConcurrencyUtils.kt:61)
	at com.jetbrains.pluginverifier.PluginVerifierRunKt.runSeveralVerifiers(PluginVerifierRun.kt:34)
	at com.jetbrains.pluginverifier.tasks.checkPlugin.CheckPluginTask.execute(CheckPluginTask.kt:39)
	at com.jetbrains.pluginverifier.tasks.checkPlugin.CheckPluginTask.execute(CheckPluginTask.kt:23)
	at com.jetbrains.pluginverifier.PluginVerifierMain.main(PluginVerifierMain.kt:135)
Caused by: java.lang.RuntimeException: Failed to invoke Resolve dependency com.intellij.database in 5 attempts
	at com.jetbrains.pluginverifier.misc.RetryUtilKt.retry(RetryUtil.kt:30)
	at com.jetbrains.pluginverifier.misc.RetryUtilKt.retry$default(RetryUtil.kt:17)
	at com.jetbrains.pluginverifier.dependencies.resolution.RepositoryDependencyFinder.findPluginDependency(RepositoryDependencyFinder.kt:26)
	at com.jetbrains.pluginverifier.dependencies.resolution.CompositeDependencyFinder.findPluginDependency(CompositeDependencyFinder.kt:21)
	at com.jetbrains.pluginverifier.dependencies.resolution.CompositeDependencyFinder.findPluginDependency(CompositeDependencyFinder.kt:21)
	at com.jetbrains.pluginverifier.dependencies.DependenciesGraphBuilder.resolveDependency(DependenciesGraphBuilder.kt:117)
	at com.jetbrains.pluginverifier.dependencies.DependenciesGraphBuilder.addTransitiveDependencies(DependenciesGraphBuilder.kt:67)
	at com.jetbrains.pluginverifier.dependencies.DependenciesGraphBuilder.buildDependenciesGraph(DependenciesGraphBuilder.kt:34)
	at com.jetbrains.pluginverifier.resolution.DefaultClassResolverProvider.provide(DefaultClassResolverProvider.kt:33)
	at com.jetbrains.pluginverifier.PluginVerifier.verify(PluginVerifier.kt:72)
	at com.jetbrains.pluginverifier.PluginVerifier.loadPluginAndVerify(PluginVerifier.kt:64)
	at com.jetbrains.pluginverifier.PluginVerifierRunKt$runSeveralVerifiers$$inlined$map$lambda$1.call(PluginVerifierRun.kt:28)
	at com.jetbrains.pluginverifier.PluginVerifierRunKt$runSeveralVerifiers$$inlined$map$lambda$1.call(PluginVerifierRun.kt)
	at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:131)
	at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:125)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

> Task :runPluginVerifier FAILED

FAILURE: Build failed with an exception.

```

https://github.com/izhangzhihao/intellij-rainbow-brackets/runs/2303987469

**Comment by izhangzhihao** [comment]
If remove 2021.1, it works fine: https://github.com/izhangzhihao/intellij-rainbow-brackets/commit/afdf756d5658ae45cd4cd229237b34fc9b953876

**Comment by hsz** [comment]
It looks like it was an issue related to the Cloud Front caching. Now everything should work fine – I've just checked the URL, and IDE is downloaded properly.
Sorry for the inconvenience!

**Comment by izhangzhihao** [comment]
Well, but the CI is still broken, latest run still shows same error: https://github.com/izhangzhihao/intellij-rainbow-brackets/runs/2338639710?check_suite_focus=true

**Comment by izhangzhihao** [comment]
Hi @hsz @zolotov the latest run is still failed with same error: https://github.com/izhangzhihao/intellij-rainbow-brackets/runs/2367359118

**Comment by hsz** [comment]
It fails on a third IDE, which is `IIC-2021.1` – community edition, that doesn't contain a Database plugin. If you'll switch to `IU`, PV test passes.

**Comment by izhangzhihao** [comment]
> It fails on a third IDE, which is `IIC-2021.1` – community edition, that doesn't contain a Database plugin. If you'll switch to `IU`, PV test passes.

Emmm, but it works using IC 2021.1 EAP. If it works as you said, then I could not test with IC, does the WebStorm has Database plugin? if does not, why it does not show errors? https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.2/gradle.properties#L12
