### ISSUE TITLE
Please clarify Gradle compatibility: which version is the minimal?

### ISSUE THREAD

**Issue by vlsi** [JetBrains/gradle-intellij-plugin#662]
I see readme spells "This project requires Gradle 5.1 or newer", however, the tests with 6.1 fail as follows:

```
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:234)
	at com.google.common.io.Files$FileByteSource.read(Files.java:155)
	at com.google.common.io.Files.toByteArray(Files.java:237)
	at org.gradle.internal.hash.ChecksumHasher.hash(ChecksumHasher.java:35)
	at org.gradle.api.internal.changedetection.state.CachingFileHasher.snapshot(CachingFileHasher.java:87)
	at org.gradle.api.internal.changedetection.state.CachingFileHasher.snapshot(CachingFileHasher.java:74)
	at org.gradle.api.internal.changedetection.state.CachingFileHasher.hash(CachingFileHasher.java:64)
	at org.gradle.internal.hash.DefaultChecksumService.doHash(DefaultChecksumService.java:82)
	at org.gradle.internal.hash.DefaultChecksumService.sha1(DefaultChecksumService.java:50)
	at org.gradle.internal.resource.local.GroupedAndNamedUniqueFileStore.getChecksum(GroupedAndNamedUniqueFileStore.java:88)
	at org.gradle.internal.resource.local.GroupedAndNamedUniqueFileStore.move(GroupedAndNamedUniqueFileStore.java:54)
	at org.gradle.internal.resource.transfer.CacheAwareExternalResourceAccessor$DefaultResourceFileStore.moveIntoCache(CacheAwareExternalResourceAccessor.java:59)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$3.create(DefaultCacheAwareExternalResourceAccessor.java:229)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$3.create(DefaultCacheAwareExternalResourceAccessor.java:226)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:210)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:182)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:206)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultArtifactCacheLockingManager.useCache(DefaultArtifactCacheLockingManager.java:89)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.moveIntoCache(DefaultCacheAwareExternalResourceAccessor.java:226)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.copyToCache(DefaultCacheAwareExternalResourceAccessor.java:219)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.access$300(DefaultCacheAwareExternalResourceAccessor.java:56)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$1.get(DefaultCacheAwareExternalResourceAccessor.java:93)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$1.get(DefaultCacheAwareExternalResourceAccessor.java:85)
	at org.gradle.cache.internal.ProducerGuard$AdaptiveProducerGuard.guardByKey(ProducerGuard.java:97)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.getResource(DefaultCacheAwareExternalResourceAccessor.java:85)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadByCoords(DefaultExternalResourceArtifactResolver.java:139)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadStaticResource(DefaultExternalResourceArtifactResolver.java:94)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.resolveArtifact(DefaultExternalResourceArtifactResolver.java:62)
	at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver$RemoteRepositoryAccess.resolveArtifact(ExternalResourceResolver.java:511)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$ResolveAndCacheRepositoryAccess.resolveArtifact(CachingModuleComponentRepository.java:445)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.lambda$resolveArtifact$15(ErrorHandlingModuleComponentRepository.java:181)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess$$Lambda$203/0x0000000800630040.call(Unknown Source)
```

This suggests that versions below 6.1.1 are not really usable (see https://github.com/gradle/gradle/commit/43f9ae6d1d4d737f3248df3482541aa364ddafc7 )

---

Then, Gradle < 6.7 go with Kotlin 1.3.x, so I guess the plugin would fail to work in say, Gradle 6.5 unless you extensively test it in that combination (see https://github.com/gradle/gradle/issues/16781 )

I do not try to blame you or something, however, it would really help if you could include the minimal supported Gradle version to the test suite.

**Comment by YannCebron** [comment]
6.1 has a known bug mentioned here https://plugins.jetbrains.com/docs/intellij/gradle-prerequisites.html#creating-a-gradle-based-intellij-platform-plugin-with-new-project-wizard

**Comment by YannCebron** [comment]
As of 1.0 release
_This project requires Gradle 6.2 or newer_
