### ISSUE TITLE
`runIde` and `buildSearchableOptions` task emit a `ClassNotFoundException` for `ClassFileDecompilers$Light`

### ISSUE THREAD

**Issue by bric3** [JetBrains/gradle-intellij-plugin#673]
I am updating a decompiler plugin (not updated in years) to the latest intellij version, and the gradle `buildSearcheableOptions` task fails. I know I can disable `buildSearchableOptions`, but for runIde this is more problematic.

This exception is weird since the compilation work just fine.

```
    id("org.jetbrains.intellij") version("0.7.3")
```

```
intellij {
    version '2021.1'
    plugins = ['java']
    pluginName 'jd-intellij'
}
```

```
$ ./gradlew --version

------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (Amazon.com Inc. 11.0.11+9-LTS)
OS:           Mac OS X 11.4 x86_64
```

<details><summary><code>plugin.xml</code></summary>

```xml
<idea-plugin>
    <name>Java Decompiler IntelliJ Plugin</name>
    <description><![CDATA[
        JD-IntelliJ is a plug-in for the IntelliJ IDEA platform.
        It allows you to display all the Java sources during your debugging process, even if you do not have them all.
        It is based on the famous tools JD-GUI.
    ]]></description>
    <id>jd-intellij</id>
    <version>@CURRENT_VERSION@</version>
    <vendor url="https://github.com/bric3/jd-intellij">Brice Dutheil</vendor>


    <!-- please see http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html
     on how to target different products -->
    <depends>com.intellij.modules.platform</depends>

    <application-components>
        <component>
            <implementation-class>jd.ide.intellij.config.JDPluginComponent</implementation-class>
        </component>
    </application-components>

    <project-components>
    </project-components>

    <actions>
        <!-- Add your actions here -->
    </actions>

    <extensions defaultExtensionNs="com.intellij">
        <applicationService id="cachingDecompilerService"
                            serviceImplementation="jd.ide.intellij.CachingJavaDecompilerService"/>

        <applicationService id="decompilerRefreshSupportService"
                            serviceImplementation="jd.ide.intellij.JavaDecompilerRefreshSupportService"/>

        <psi.classFileDecompiler implementation="jd.ide.intellij.JavaLightClassDecompiler" order="last"/>

        <!--<iconProvider implementation="jd.ide.intellij.JavaDecompilerIconProvider"/>-->
    </extensions>
</idea-plugin>
```
</details>

<details><summary><code>:buildSearcheableOptions</code></summary>

```
> Task :buildSearchableOptions
Download https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-11_0_10-osx-x64-b1341.35.tar.gz
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.openapi.application.impl.InvocationUtil to field java.awt.event.InvocationEvent.runnable
WARNING: Please consider reporting this to the maintainers of com.intellij.openapi.application.impl.InvocationUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-05-26 11:33:18,449 [   2111]   WARN - j.internal.DebugAttachDetector - Unable to start DebugAttachDetector, please add `--add-exports java.base/jdk.internal.vm=ALL-UNNAMED` to VM options 
Starting searchable options index builder
2021-05-26 11:33:19,925 [   3587]  ERROR - nsions.impl.ExtensionPointImpl - Cannot load class jd.ide.intellij.JavaLightClassDecompiler (
  error: com/intellij/psi/compiled/ClassFileDecompilers$Light,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Java Decompiler IntelliJ Plugin, id=jd-intellij, descriptorPath=plugin.xml, path=~/opensource/jd-intellij/build/idea-sandbox/plugins/jd-intellij, version=0.8.0-SNAPSHOT, package=null), packagePrefix=null, instanceId=22, state=active)
) 
com.intellij.diagnostic.PluginException: Cannot load class jd.ide.intellij.JavaLightClassDecompiler (
  error: com/intellij/psi/compiled/ClassFileDecompilers$Light,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Java Decompiler IntelliJ Plugin, id=jd-intellij, descriptorPath=plugin.xml, path=~/opensource/jd-intellij/build/idea-sandbox/plugins/jd-intellij, version=0.8.0-SNAPSHOT, package=null), packagePrefix=null, instanceId=22, state=active)
)
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:346)
        at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:233)
        at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1090)
        at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
        at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:712)
        at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.java:25)
        at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:64)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:502)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:436)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.calcExtensionList(ExtensionPointImpl.java:253)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:247)
        at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:39)
        at com.intellij.psi.impl.compiled.ClassFileStubBuilder.getAllSubBuilders(ClassFileStubBuilder.java:32)
        at com.intellij.psi.stubs.CompositeBinaryBuilderMap.<init>(CompositeBinaryBuilderMap.java:48)
        at com.intellij.psi.stubs.StubUpdatingIndexStorage.<init>(StubUpdatingIndexStorage.java:26)
        at com.intellij.psi.stubs.StubUpdatingIndex.createIndexImplementation(StubUpdatingIndex.java:372)
        at com.intellij.util.indexing.FileBasedIndexImpl.createIndex(FileBasedIndexImpl.java:542)
        at com.intellij.util.indexing.FileBasedIndexImpl.initIndexStorage(FileBasedIndexImpl.java:479)
        at com.intellij.util.indexing.FileBasedIndexImpl.registerIndexer(FileBasedIndexImpl.java:439)
        at com.intellij.util.indexing.FileBasedIndexDataInitialization.lambda$initAssociatedDataForExtensions$0(FileBasedIndexDataInitialization.java:79)
        at com.intellij.util.indexing.IndexDataInitializer.executeTask(IndexDataInitializer.kt:75)
        at com.intellij.util.indexing.IndexDataInitializer.access$executeTask(IndexDataInitializer.kt:15)
        at com.intellij.util.indexing.IndexDataInitializer$runParallelTasks$$inlined$map$lambda$1.run(IndexDataInitializer.kt:49)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
        at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
        at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: com/intellij/psi/compiled/ClassFileDecompilers$Light
        at java.base/java.lang.ClassLoader.defineClass2(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1109)
        at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:269)
        at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:121)
        at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:55)
        at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:221)
        at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:180)
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:338)
        ... 36 more
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.compiled.ClassFileDecompilers$Light PluginClassLoader(plugin=PluginDescriptor(name=Java Decompiler IntelliJ Plugin, id=jd-intellij, descriptorPath=plugin.xml, path=~/opensource/jd-intellij/build/idea-sandbox/plugins/jd-intellij, version=0.8.0-SNAPSHOT, package=null), packagePrefix=null, instanceId=22, state=active)
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 44 more
2021-05-26 11:33:19,930 [   3592]  ERROR - nsions.impl.ExtensionPointImpl - IntelliJ IDEA 2021.1  Build #IC-211.6693.111 
2021-05-26 11:33:19,936 [   3598]  ERROR - nsions.impl.ExtensionPointImpl - JDK: 11.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-05-26 11:33:19,937 [   3599]  ERROR - nsions.impl.ExtensionPointImpl - OS: Mac OS X 
2021-05-26 11:33:19,937 [   3599]  ERROR - nsions.impl.ExtensionPointImpl - Plugin to blame: Java Decompiler IntelliJ Plugin version: 0.8.0-SNAPSHOT 
2021-05-26 11:33:19,937 [   3599]  ERROR - nsions.impl.ExtensionPointImpl - Last Action:  
2021-05-26 11:33:22,618 [   6280]   WARN - options.ex.ConfigurableWrapper - Cannot find extension point com.intellij.compilerSettingsFactory in ProjectDefault (Template) Project 
2021-05-26 11:33:29,442 [  13104]   WARN - #com.intellij.ui.jcef.JBCefApp - JCEF is manually disabled in headless env via 'ide.browser.jcef.headless.enabled=false' 
Found 209 configurables
Searchable options index builder completed
```
</details>

<details><summary><code>:runIde</code></summary>

```
> Task :runIde
WARNING: An illegal reflective access operation has occurred
WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by com.intellij.ui.JreHiDpiUtil to method sun.java2d.SunGraphicsEnvironment.isUIScaleEnabled()
WARNING: Illegal reflective access by com.intellij.ui.JreHiDpiUtil to method sun.java2d.SunGraphicsEnvironment.isUIScaleEnabled()

WARNING: Please consider reporting this to the maintainers of com.intellij.ui.JreHiDpiUtil
WARNING: Please consider reporting this to the maintainers of com.intellij.ui.JreHiDpiUtil

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release
WARNING: All illegal access operations will be denied in a future release

2021-05-26 11:41:36,230 [  21799]   WARN - i.mac.MacOSApplicationProvider - No URL bundle (CFBundleURLTypes) is defined in the main bundle.
To be able to open external links, specify protocols in the app layout section of the build file.
Example: args.urlSchemes = ["your-protocol"] will handle following links: your-protocol://open?file=file&line=line 
2021-05-26 11:41:36,874 [  22443]   WARN - j.internal.DebugAttachDetector - Unable to start DebugAttachDetector, please add `--add-exports java.base/jdk.internal.vm=ALL-UNNAMED` to VM options 
2021-05-26 11:41:38,392 [  23961]  ERROR - nsions.impl.ExtensionPointImpl - Cannot load class jd.ide.intellij.JavaLightClassDecompiler (
  error: com/intellij/psi/compiled/ClassFileDecompilers$Light,
  error: com/intellij/psi/compiled/ClassFileDecompilers$Light,

  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Java Decompiler IntelliJ Plugin, id=jd-intellij, descriptorPath=plugin.xml, path=~/opensource/jd-intellij/build/idea-sandbox/plugins/jd-intellij, version=0.8.0-SNAPSHOT, package=null), packagePrefix=null, instanceId=22, state=active)
) 
com.intellij.diagnostic.PluginException: Cannot load class jd.ide.intellij.JavaLightClassDecompiler (
  error: com/intellij/psi/compiled/ClassFileDecompilers$Light,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Java Decompiler IntelliJ Plugin, id=jd-intellij, descriptorPath=plugin.xml, path=~/opensource/jd-intellij/build/idea-sandbox/plugins/jd-intellij, version=0.8.0-SNAPSHOT, package=null), packagePrefix=null, instanceId=22, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:346)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:233)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1090)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:712)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.java:25)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:64)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:502)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:436)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.calcExtensionList(ExtensionPointImpl.java:253)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:247)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:39)
	at com.intellij.psi.impl.compiled.ClassFileStubBuilder.getAllSubBuilders(ClassFileStubBuilder.java:32)
	at com.intellij.psi.stubs.CompositeBinaryBuilderMap.<init>(CompositeBinaryBuilderMap.java:48)
	at com.intellij.psi.stubs.StubUpdatingIndexStorage.<init>(StubUpdatingIndexStorage.java:26)
	at com.intellij.psi.stubs.StubUpdatingIndex.createIndexImplementation(StubUpdatingIndex.java:372)
	at com.intellij.util.indexing.FileBasedIndexImpl.createIndex(FileBasedIndexImpl.java:542)
	at com.intellij.util.indexing.FileBasedIndexImpl.initIndexStorage(FileBasedIndexImpl.java:479)
	at com.intellij.util.indexing.FileBasedIndexImpl.registerIndexer(FileBasedIndexImpl.java:439)
	at com.intellij.util.indexing.FileBasedIndexDataInitialization.lambda$initAssociatedDataForExtensions$0(FileBasedIndexDataInitialization.java:79)
	at com.intellij.util.indexing.IndexDataInitializer.executeTask(IndexDataInitializer.kt:75)
	at com.intellij.util.indexing.IndexDataInitializer.access$executeTask(IndexDataInitializer.kt:15)
	at com.intellij.util.indexing.IndexDataInitializer$runParallelTasks$$inlined$map$lambda$1.run(IndexDataInitializer.kt:49)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: com/intellij/psi/compiled/ClassFileDecompilers$Light
Caused by: java.lang.NoClassDefFoundError: com/intellij/psi/compiled/ClassFileDecompilers$Light

	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1109)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:269)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:121)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:55)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:221)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:180)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:338)
	... 36 more
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.compiled.ClassFileDecompilers$Light PluginClassLoader(plugin=PluginDescriptor(name=Java Decompiler IntelliJ Plugin, id=jd-intellij, descriptorPath=plugin.xml, path=~/opensource/jd-intellij/build/idea-sandbox/plugins/jd-intellij, version=0.8.0-SNAPSHOT, package=null), packagePrefix=null, instanceId=22, state=active)
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.compiled.ClassFileDecompilers$Light PluginClassLoader(plugin=PluginDescriptor(name=Java Decompiler IntelliJ Plugin, id=jd-intellij, descriptorPath=plugin.xml, path=~/opensource/jd-intellij/build/idea-sandbox/plugins/jd-intellij, version=0.8.0-SNAPSHOT, package=null), packagePrefix=null, instanceId=22, state=active)

	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 44 more
```
</details>

For the `:runIde` task, I tried to tweak the :prepareSandbox` task as described in this https://github.com/JetBrains/gradle-intellij-plugin/issues/591#issuecomment-776740734

The plugin branch is here. : https://github.com/bric3/jd-intellij/tree/upgrade-jd-core
**This is a work in progress.**

**Comment by YannCebron** [comment]
Your `plugin.xml` misses `<depends>` for Java plugin https://blog.jetbrains.com/platform/2019/06/java-functionality-extracted-as-a-plugin/

**Comment by bric3** [comment]
@YannCebron oh thanks, and thank you for the quick answer !!!

Of course I only updated the build.gradle in that regard, and forgot about `plugin.xml`.

Cheers !

**Comment by bric3** [comment]
@YannCebron I wonder if as an enhancement this could be improved, ie declare the dependencies once (e.g. in the `intellij` closure of the build script), and the `gradle-intellij-plugin` generates the according `plugin.xml`.

**Comment by bric3** [comment]
OK, that's interesting !
Thanks for the link.
