### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Turbo87** [JetBrains/gradle-intellij-plugin#69]
I'm getting the following error when executing `./gradlew runIdea`:

````
Internal error. Please report to http://jb.gg/ide/critical-startup-errors

java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.util.registry.RegistryState'
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:201)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:63)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:360)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.util.registry.RegistryState'
    at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:243)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:536)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
    at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:90)
    at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:496)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:505)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:454)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:446)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    ... 16 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class kotlin.jvm.internal.Reflection
    at com.intellij.configurationStore.StateStorageManagerImpl.getStateStorage(StateStorageManagerImpl.kt:133)
    at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:256)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:90)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:516)
    ... 29 more
````

I am using Kotlin `1.0.0-beta-4584` in my plugin and I am trying to run `version = 'IU-15.0.1'` of IntelliJ. Any ideas of what is going on here?

Link to the plugin is https://github.com/Turbo87/intellij-emberjs/tree/cf727b509bce9e770491e95fde8718630e4dd52d

**Comment by zolotov** [comment]
@yole could you help please?

**Comment by AlecStrong** [comment]
Can't remember if `kotlin-runtime` includes reflection but try adding 

`compile "org.jetbrains.kotlin:kotlin-reflect:$KOTLIN_VERSION"`

to your dependencies

**Comment by Turbo87** [comment]
@AlecStrong unfortunately that doesn't seem to help. still getting the same error after adding that dependency.

I have a feeling that #57 and #60 might be involved, but I'm not quite sure what exactly is happening here that's causing these problems.

**Comment by AmailP** [comment]
Hey, I had the very same issue. It just disappeared after deleting the ~/.gradle directory, where the cached idea files are downloaded and extracted.

**Comment by Turbo87** [comment]
@AmailP that actually seems to work, but now I'm confused even more. any idea what is causing these issues?

**Comment by zolotov** [comment]
@AmailP thank you

@Turbo87 don't know either. Maybe before `0.0.39` your project were compiled against IDEA's kotlin and since `0.0.39` it's compiled against your particular kotlin dependency, so some of your classes were compiled with one kotlin version and some other classes – with other kotlin version, and maybe this leads to the problem. Anyway I'm not really want to investigate this, knowing `gradle clean` fixes it :) 
If you faced the error again please reopen this issue.

**Comment by zolotov** [comment]
Actually I misread the solution that helps (cleaning ` ~/.gradle` directory). I think I know what's going on

**Comment by Turbo87** [comment]
@zolotov Indeed, just removing that sandbox and the `build/` folder did not help. It looks like IntelliJ is actually saving *something* in the Gradle cache folder. I've only deleted `~/.gradle/caches` and not the entire folder and that seems to have been enough to fix the issue.

**Comment by zolotov** [comment]
@Turbo87 @AmailP have you seen the following notifications before the problem appears? And have you clicked on 'Update all' link?

<img width="505" alt="screenshot 2016-02-04 15 16 11" src="https://cloud.githubusercontent.com/assets/140920/12814730/584e2c3c-cb52-11e5-9c59-de6fca90b783.png">

**Comment by Turbo87** [comment]
hmm... I can't say that I haven't. I've definitely seen popups that looked roughly like this and I usually click on Update in such cases, I'm just not sure if it saw it in the `runIdea` IDE too or just in my usual work IDE.

**Comment by zolotov** [comment]
One more question. Was your usual work IDE not `15.0.1`? It looks like `Update All` action substitute kotlin-libraries in gradle IDEA distribution with the library from your usual IDE, so `runIdea` IDE cannot work normally after that.

**Comment by Turbo87** [comment]
my "usual work IDE" at the time was (and still is) `15.0.3`

**Comment by Turbo87** [comment]
although I've been experimenting with the `16 EAP` builds too... not sure if that was correlating

**Comment by zolotov** [comment]
Will be fixed in kotlin plugin: https://youtrack.jetbrains.com/issue/KT-10918

**Comment by Turbo87** [comment]
@zolotov awesome, thanks for investigating this!
