### ISSUE TITLE
Lot's of deprecation warnings when running against Gradle 7.1

### ISSUE THREAD

**Issue by DreierF** [JetBrains/gradle-intellij-plugin#700]
Hi,

There are a number of deprecation warnings since Gradle 7.1.
Most of them refer to VersionNumber, which will be removed without replacement in Gradle 8.0.
```
IntelliJPlugin.kt: (22, 24): 'VersionNumber' is deprecated. Deprecated in Java
IntelliJPlugin.kt: (84, 13): 'VersionNumber' is deprecated. Deprecated in Java
IntelliJPlugin.kt: (84, 65): 'VersionNumber' is deprecated. Deprecated in Java
IntelliJPlugin.kt: (510, 17): 'VersionNumber' is deprecated. Deprecated in Java
IntelliJPlugin.kt: (510, 66): 'VersionNumber' is deprecated. Deprecated in Java
IntelliJPlugin.kt: (544, 13): 'VersionNumber' is deprecated. Deprecated in Java
IntelliJPlugin.kt: (544, 62): 'VersionNumber' is deprecated. Deprecated in Java
IntelliJPluginExtension.kt: (14, 24): 'ConfigureUtil' is deprecated. Deprecated in Java
IntelliJPluginExtension.kt: (135, 9): 'ConfigureUtil' is deprecated. Deprecated in Java
jbr/JbrResolver.kt: (11, 24): 'VersionNumber' is deprecated. Deprecated in Java
jbr/JbrResolver.kt: (128, 35): 'VersionNumber' is deprecated. Deprecated in Java
jbr/JbrResolver.kt: (132, 79): 'VersionNumber' is deprecated. Deprecated in Java
jbr/JbrResolver.kt: (141, 39): 'VersionNumber' is deprecated. Deprecated in Java
tasks/DownloadRobotServerPluginTask.kt: (14, 24): 'VersionNumber' is deprecated. Deprecated in Java
tasks/DownloadRobotServerPluginTask.kt: (96, 9): 'VersionNumber' is deprecated. Deprecated in Java
tasks/DownloadRobotServerPluginTask.kt: (96, 40): 'VersionNumber' is deprecated. Deprecated in Java
tasks/RunIdeBase.kt: (15, 24): 'VersionNumber' is deprecated. Deprecated in Java
tasks/RunIdeBase.kt: (107, 23): 'VersionNumber' is deprecated. Deprecated in Java
tasks/RunIdeBase.kt: (108, 23): 'VersionNumber' is deprecated. Deprecated in Java
tasks/RunPluginVerifierTask.kt: (27, 24): 'VersionNumber' is deprecated. Deprecated in Java
tasks/RunPluginVerifierTask.kt: (226, 20): 'setter for main: String?' is deprecated. Deprecated in Java
tasks/RunPluginVerifierTask.kt: (554, 9): 'VersionNumber' is deprecated. Deprecated in Java
tasks/RunPluginVerifierTask.kt: (554, 41): 'VersionNumber' is deprecated. Deprecated in Java
utils.kt: (27, 31): 'JavaPluginConvention' is deprecated. Deprecated in Java
utils.kt: (50, 6): 'getter for convention: Convention!' is deprecated. Deprecated in Java
utils.kt: (50, 27): 'JavaPluginConvention' is deprecated. Deprecated in Java
```

**Comment by mvilliger** [comment]
I am also getting this one using gradle-intellij-plugin 1.0 with Gradle 7.1:

```
The JavaExec.main property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. See https://docs.gradle.org/7.1/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:main for more details.
	at org.gradle.api.tasks.JavaExec.setMain(JavaExec.java:418)
	at org.jetbrains.intellij.tasks.RunIdeTask_Decorated.setMain(Unknown Source)
	at org.jetbrains.intellij.tasks.RunIdeBase.<init>(RunIdeBase.kt:80)
	at org.jetbrains.intellij.tasks.RunIdeTask.<init>(RunIdeTask.kt:3)
```
