### ISSUE TITLE
Disable bundled official plugin

### ISSUE THREAD

**Issue by devkanro** [JetBrains/gradle-intellij-plugin#721]
# Desacription
I am building a [Protobuf Language Plugin](https://github.com/devkanro/intellij-protobuf-plugin), and JetBrains adopted [another plugin](https://github.com/jvolkman/intellij-protobuf-editor) as the official plugin in 2021.2.

I am try to upgrade my plugin based on 2021.2, and I got some errors when building and verify my plugin, like this.
```
2021-07-05 18:27:06,413 [   4146]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2021.2 EAP  Build #IU-212.4535.20 
2021-07-05 18:27:06,413 [   4146]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-07-05 18:27:06,413 [   4146]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2021-07-05 18:27:06,413 [   4146]  ERROR - llij.ide.plugins.PluginManager - Last Action:  
Starting searchable options index builder
2021-07-05 18:27:06,958 [   4691]  ERROR - nsions.impl.ExtensionPointImpl - Cannot create class com.intellij.sql.dialects.mssql.MsCodeStyleProvider (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Database Tools and SQL, id=com.intellij.database, descriptorPath=plugin.xml, path=~\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIU\212.4535-EAP-CANDIDATE-SNAPSHOT\46eb7c61c0a11e2b4bc079b417acf5039b05c882\ideaIU-212.4535-EAP-CANDIDATE-SNAPSHOT\plugins\DatabaseTools, version=212.4535.20, package=null), packagePrefix=null, instanceId=132, state=active)) 
com.intellij.diagnostic.PluginException: Cannot create class com.intellij.sql.dialects.mssql.MsCodeStyleProvider (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Database Tools and SQL, id=com.intellij.database, descriptorPath=plugin.xml, path=~\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIU\212.4535-EAP-CANDIDATE-SNAPSHOT\46eb7c61c0a11e2b4bc079b417acf5039b05c882\ideaIU-212.4535-EAP-CANDIDATE-SNAPSHOT\plugins\DatabaseTools, version=212.4535.20, package=null), packagePrefix=null, instanceId=132, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:873)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.instantiateClass(XmlExtensionAdapter.java:98)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:115)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:66)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:482)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:430)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.calcExtensionList(ExtensionPointImpl.java:244)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:238)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:39)
	at com.intellij.sql.formatter.SqlCodeStyleProviderRegistrar.<init>(SqlCodeStyleProviderRegistrar.kt:9)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:881)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:48)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:36)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.invoke(ComponentManagerImpl.kt:1058)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.run(ComponentManagerImpl.kt:58)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ExceptionInInitializerError
	at com.intellij.protobuf.ide.style.PbLanguageCodeStyleSettingsProvider.getLanguage(PbLanguageCodeStyleSettingsProvider.java:35)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettingsManager.initNonReadSettings(CommonCodeStyleSettingsManager.java:106)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettingsManager.getCommonSettingsMap(CommonCodeStyleSettingsManager.java:74)
	at com.intellij.psi.codeStyle.CommonCodeStyleSettingsManager.addLanguageSettings(CommonCodeStyleSettingsManager.java:275)
	at com.intellij.psi.codeStyle.CodeStyleSettings.registerCommonSettings(CodeStyleSettings.java:1213)
	at com.intellij.sql.dialects.mssql.formatter.MsVsSqlCodeStyleScheme.<clinit>(MsVsSqlCodeStyleScheme.kt:21)
	at com.intellij.sql.dialects.mssql.MsCodeStyleProvider.<init>(MsCodeStyleProvider.kt:14)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:829)
	... 28 more
Caused by: com.intellij.diagnostic.ImplementationConflictException: Language with ID 'protobuf' is already registered: class io.kanro.idea.plugin.protobuf.lang.ProtobufLanguage
	at com.intellij.lang.Language.<init>(Language.java:84)
	at com.intellij.protobuf.lang.PbLanguage.<init>(PbLanguage.java:25)
	at com.intellij.protobuf.lang.PbLanguage.<clinit>(PbLanguage.java:22)
	... 36 more
```

Can I disable the official protobuf plugin in my building processing?

**Comment by hsz** [comment]
Create `disabled_plugins.txt` file in the `build/idea-sandbox/config` directory (or any other if you alter sandbox location) with IDs of plugins you want to disable, like:

```
org.jetbrains.android
com.intellij.swagger
```

You can extend the `PrepareSandbox` task and create it in `doLast` to ensure it'll not vanish.

**Comment by devkanro** [comment]
Thanks, resolved with those config:
```gradle
    prepareSandbox {
        doLast {
            val file = file(buildDir.resolve("idea-sandbox/config/disabled_plugins.txt"))
            file.ensureParentDirsCreated()
            file.writeText(buildString {
                appendln("idea.plugin.protoeditor")
                appendln("com.intellij.grpc")
            })
        }
    }
```
