### ISSUE TITLE
java.lang.NoSuchMethodError: void kotlin.jvm.internal.FunctionReferenceImpl

### ISSUE THREAD

**Issue by Undin** [JetBrains/gradle-intellij-plugin#750]
## Environment
* gradle-intellij-plugin: 1.1.4
* gradle: 6.7

## Steps to reproduce
* Checkout https://github.com/JetBrains/educational-plugin/commit/17baf9d10f20a9644648f3e8610bee3f8e7ac97c
* Ensure that artifact of IDEA ultimate is not unarchived yet (see `~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/212.4746-EAP-CANDIDATE-SNAPSHOT`)
* Invoke `./gradlew testClasses` for project or just load project structure via `Reload All Gradle Project` action in IDEA

<details><summary>Stacktrace</summary>

```
Caused by: java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)'
        at org.jetbrains.intellij.utils.ArchiveUtils$extract$decompressor$1.<init>(ArchiveUtils.kt)
        at org.jetbrains.intellij.utils.ArchiveUtils.extract(ArchiveUtils.kt:46)
        at org.jetbrains.intellij.dependency.IdeaDependencyManager.unzipDependencyFile(IdeaDependencyManager.kt:132)
        at org.jetbrains.intellij.dependency.IdeaDependencyManager.extractClassesFromRemoteDependency(IdeaDependencyManager.kt:298)
        at org.jetbrains.intellij.dependency.IdeaDependencyManager.resolveRemote(IdeaDependencyManager.kt:261)
        at org.jetbrains.intellij.IntelliJPlugin.configureIntellijDependency$lambda-9(IntelliJPlugin.kt:181)
        at org.gradle.internal.ImmutableActionSet$SetWithFewActions.execute(ImmutableActionSet.java:285)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.runDependencyActions(DefaultConfiguration.java:452)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$1.call(DefaultConfiguration.java:609)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$1.call(DefaultConfiguration.java:606)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:606)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.lambda$resolveExclusively$4(DefaultConfiguration.java:586)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$CalculatedModelValueImpl.update(DefaultProjectStateRegistry.java:361)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveExclusively(DefaultConfiguration.java:583)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:570)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1800(DefaultConfiguration.java:139)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:1265)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitArtifacts(DefaultConfiguration.java:1256)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitContents(DefaultConfiguration.java:1252)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.visitContents(DefaultConfiguration.java:480)
        at org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:126)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolve(DefaultConfiguration.java:470)
        at org.jetbrains.intellij.IntelliJPluginExtension.getIdeaDependency(IntelliJPluginExtension.kt:212)
        at org.jetbrains.intellij.IntelliJPlugin.configureTestTasks(IntelliJPlugin.kt:875)
        at org.jetbrains.intellij.IntelliJPlugin.configureProjectAfterEvaluate(IntelliJPlugin.kt:164)
        at org.jetbrains.intellij.IntelliJPlugin.configureTasks$lambda-6(IntelliJPlugin.kt:151)
```

</details>

I suppose it's because of https://github.com/JetBrains/gradle-intellij-plugin/commit/19ceb4ca04dabdd2d311aa2e2a020cc8e0257c75 change where the plugin started to use 1.4 API although minimal supported version 6.6 that uses kotlin `1.3.72`
I see two possible solutions: use 1.3 as kotlin API version or make Gradle 6.8 minimal supported version that uses kotlin `1.4.20`

**Comment by alexander-shustanov** [comment]
Hello! Are there any updates?

**Comment by nocsg** [comment]
Caused by: java.lang.NoSuchMethodError: 'void org.gradle.api.internal.file.DefaultSourceDirectorySet.<init>(java.lang.String, org.gradle.api.internal.file.FileResolver)'

**Comment by hsz** [comment]
We'll switch to Kotlin API Version `1.3`
