### ISSUE TITLE
runPluginVerifier task fails if user.home directory is not writable

### ISSUE THREAD

**Issue by 20100** [JetBrains/gradle-intellij-plugin#778]
Hello,
I'm using gradle-intellij-plugin 1.1.4, and the task runPluginVerifier fails if running on a docker image without write access on user.home.
Even if I add -Dplugin.verifier.home.dir=/tmp/xxx or If I add downloadDir.set("${project.buildDir}/verifierDir") in the dsl.

Each time it try to create a directory ~/.pluginVerifier to store ides and loaded-plugins empties directories.

 Exception in thread "main" java.lang.ExceptionInInitializerError
at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:184)
at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:173)
Caused by: java.nio.file.AccessDeniedException: /.pluginVerifier
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
at java.base/java.nio.file.Files.createDirectory(Files.java:690)
at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
at java.base/java.nio.file.Files.createDirectories(Files.java:783)
at com.jetbrains.plugin.structure.base.utils.FileUtilKt.createDir(FileUtil.kt:62)
at com.jetbrains.pluginverifier.PluginVerifierMain.<clinit>(PluginVerifierMain.kt:77)

You can reproduce by creating a file named .pluginVerifier in user home directory.

**Comment by hsz** [comment]
@20100 Looking at the big picture, you're providing an incorrect path as a verifier's home directory, and the process ends up with `AccessDeniedException`.
For me, that's a clear message – there's a configuration issue, not in the plugin itself – would you agree on that?
