### ISSUE TITLE
unsupported binary file

### ISSUE THREAD

**Issue by pojozhang** [JetBrains/gradle-intellij-plugin#780]
Hi, I wrote a plugin for Goland and I found that the plugin could not be installed in some situation.

I got the following error when I tried to install it on a mac installed with OSX10.15.

![image](https://user-images.githubusercontent.com/26052846/132286999-747b55a6-6204-472f-b7fb-bdf0cd46f0d6.png)

The plugin works well on my own mac installed with MacOS 11.5.

Besides, I alse tried to debug my plugin on the mac with OSX10.15 and it works well.

**Comment by YannCebron** [comment]
Did you install the plugin distribution file manually inside the IDE using plugin manager? Could you please share the distribution ZIP file somewhere for inspection? What is the IDE version where it fails? anything in idea.log file?

**Comment by pojozhang** [comment]
> Did you install the plugin distribution file manually inside the IDE using plugin manager? Could you please share the distribution ZIP file somewhere for inspection? What is the IDE version where it fails? anything in idea.log file?

It seems that my colleague used an illegal url in custom plugin repositories on his mac.
![image](https://user-images.githubusercontent.com/26052846/132439958-ee8f06bd-9c9a-4cb8-9936-24ea39ec3cc8.png)

This url contains an illegal whitespace. I got the following stacktrace in idea.log file.

```
java.lang.RuntimeException: java.net.URISyntaxException: Illegal character in scheme name at index 0:  (url)
at com.intellij.util.Urls.toUriWithoutParameters(Urls.kt:194)
	at com.intellij.util.UrlImpl.toExternalForm(UrlImpl.java:131)
	at com.intellij.ide.plugins.RepositoryHelper.loadPlugins(RepositoryHelper.java:94)
	at com.intellij.ide.plugins.CustomPluginRepositoryService.getCustomRepositoryPluginMap(CustomPluginRepositoryService.java:41)
	at com.intellij.ide.plugins.CustomPluginRepositoryService.getCustomRepositoryPlugins(CustomPluginRepositoryService.java:73)
	at com.intellij.ide.plugins.PluginInstaller$2.compute(PluginInstaller.java:293)
	at com.intellij.ide.plugins.PluginInstaller$2.compute(PluginInstaller.java:288)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:349)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
```

I think the error message 'unsupported binary file' is quite confusing.
Thanks for help~

**Comment by YannCebron** [comment]
continuing in https://youtrack.jetbrains.com/issue/IDEA-246587
