### ISSUE TITLE
ERROR - oncurrency.BoundedTaskExecutor - com/intellij/execution/impl/DefaultJavaProgramRunner 

### ISSUE THREAD

**Issue by I-am-Anton-D** [JetBrains/gradle-intellij-plugin#797]
After update on Idea 2021.2.2,  I can start my application only in "Run Mode", but if i try start it in "Debug mode" after build in Maven  - nothing happens

Please Help

There is logs of Idea:

2021-10-06 11:35:22,976 [  80213]  ERROR - oncurrency.BoundedTaskExecutor - com/intellij/execution/impl/DefaultJavaProgramRunner 
java.lang.NoClassDefFoundError: com/intellij/execution/impl/DefaultJavaProgramRunner
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1109)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:290)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:121)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:55)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:217)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:176)
	at com.intellij.util.lang.UrlClassLoader.loadClassInsideSelf(UrlClassLoader.java:389)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:297)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:232)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.intellij.javaee.appServers.run.execution.PatchedLocalState.calcEnvParams(PatchedLocalState.java:149)
	at com.intellij.javaee.appServers.run.execution.PatchedLocalState.lambda$getEnvParams$0(PatchedLocalState.java:132)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:854)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.javaee.appServers.run.execution.PatchedLocalState.getEnvParams(PatchedLocalState.java:132)
	at com.intellij.javaee.appServers.run.execution.PatchedLocalState.startJ2EEProcess(PatchedLocalState.java:96)
	at com.intellij.javaee.appServers.run.execution.J2EEProcessHandlerWrapper.lambda$new$0(J2EEProcessHandlerWrapper.java:96)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.intellij.execution.impl.DefaultJavaProgramRunner
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:227)
	at com.intellij.util.lang.PathClassLoader.findClass(PathClassLoader.java:65)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 30 more
2021-10-06 11:35:22,981 [  80218]  ERROR - oncurrency.BoundedTaskExecutor - IntelliJ IDEA 2021.2.2  Build #IU-212.5284.40 
2021-10-06 11:35:22,981 [  80218]  ERROR - oncurrency.BoundedTaskExecutor - JDK: 11.0.12; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-10-06 11:35:22,981 [  80218]  ERROR - oncurrency.BoundedTaskExecutor - OS: Windows 10 
2021-10-06 11:35:22,984 [  80221]  ERROR - oncurrency.BoundedTaskExecutor - Last Action: Debug 
2021-10-06 11:35:25,150 [  82387]   INFO - j.ide.actions.RevealFileAction - Exit code 1 
2021-10-06 11:35:25,678 [  82915]   INFO - rationStore.ComponentStoreImpl - Saving appFileTypeManager took 14 ms 
2021-10-06 11:35:25,714 [  82951]   INFO - rationStore.ComponentStoreImpl - Saving Project(name=CScoreEE, containerState=COMPONENT_CREATED, componentStore=C:\Users\Антон\Desktop\riverdoc\CScore-EE)RunManager took 19 ms

**Comment by YannCebron** [comment]
This is _Gradle_ support, not Maven. Anyway it seem your plugin might miss setup of Java plugin https://blog.jetbrains.com/platform/2019/06/java-functionality-extracted-as-a-plugin/
