### ISSUE TITLE
Enabling "downloadSources" option leads to plugin test failures

### ISSUE THREAD

**Issue by kshchepanovskyi** [JetBrains/gradle-intellij-plugin#88]
Tests that extend `com.intellij.testFramework.fixtures.LightCodeInsightFixtureTestCase` are not working if option `downloadSources` is set to `true`. They are failing at `setUp` phase due to `java.lang.AssertionError: java.lang.ClassNotFoundException: com.intellij.lang.properties.PropertiesFileTypeFactory`.

As far as I understand, problem is caused by two things.

First, this plugin [adds IDEA sources to a module dependencies](https://github.com/JetBrains/gradle-intellij-plugin/blob/ee9484d358f32cf93ffc5f0a709b3eb8282529a8/src/main/groovy/org/jetbrains/intellij/IntelliJPlugin.groovy#L93-L93):

```groovy
LOG.info("Adding IntelliJ IDEA dependency")
project.dependencies.add(configuration.name, "com.jetbrains.intellij.idea:idea$extension.type:$extension.version")
extension.ideaDirectory = ideaDirectory(project, configuration)

if (extension.downloadSources) {
    def sourcesConfiguration = project.configurations.create(SOURCES_CONFIGURATION_NAME).setVisible(false)
            .setDescription("The IntelliJ IDEA Community Edition source artifact to be used for this project.")
    LOG.info("Adding IntelliJ IDEA sources repository")
    project.dependencies.add(sourcesConfiguration.name, "com.jetbrains.intellij.idea:ideaIC:$extension.version:sources@jar")
```

Seems that moving dependency to `sourceConfiguration` is not enough to exclude it from runtime classpath.

Second, when plugins are loaded, seems that list of plugins is simple list of all folders at some path. At [this point](https://github.com/JetBrains/intellij-community/blob/10a4c91dbfca935b4b5531003fd8c13b56e66202/platform/extensions/src/com/intellij/openapi/extensions/impl/ExtensionPointImpl.java#L111) we can put a breakpoint and find that IDEA is trying to load plugin from source jar:

![image](https://cloud.githubusercontent.com/assets/4040120/14768072/9a5c394e-0a3f-11e6-88ee-84903189dbd5.png)

Later it fails because plugin is not a part of default IDEA jar:

```
java.lang.AssertionError: java.lang.ClassNotFoundException: com.intellij.lang.properties.PropertiesFileTypeFactory

	at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:56)
	at com.intellij.testFramework.TestLogger.error(TestLogger.java:38)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:257)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:194)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:100)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:87)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:49)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:308)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.<init>(FileTypeManagerImpl.java:270)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

	...

	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.setUp(CodeInsightTestFixtureImpl.java:1351)
	at com.intellij.testFramework.fixtures.LightCodeInsightFixtureTestCase.setUp(LightCodeInsightFixtureTestCase.java:102)
	at io.protostuff.jetbrains.plugin.formatter.MessageFormatterTest.setUp(MessageFormatterTest.java:17)
```

Workarounds:

1. Add `properties` to `intellij.plugins` list, so that it will be available at runtime. Works for development, but my plugin should be compatible with JetBrains products other than IDEA, and `Properties` plugin is not bundled with other IDEs (WebStorm, for example).
2. Set `downloadSources` to `false`. Makes development less convenient.

Both workarounds are not acceptable in long term, so it would be nice to fix this issue. Unfortunately I am not enough experienced in gradle (yet :) ), so I cannot provide a patch.

**Comment by zolotov** [comment]
I cannot recreate the issue with following configuration:

```
intellij {
    version '2016.1'
 }
```

Please attach sample project to recreate it. Until this I'm closing the issue

**Comment by kshchepanovskyi** [comment]
Ok, I will prepare a branch this evening, tomorrow you can check it.
