### ISSUE TITLE
plugin.xml with doctype declaration fails

### ISSUE THREAD

**Issue by uwolfer** [JetBrains/gradle-intellij-plugin#93]
It took my some time to realize that a doctype is not accepted in plugin.xml - otherwise it fails:
```
Caused by: groovy.lang.MissingPropertyException: No such property: plugin for class: org.jetbrains.intellij.Utils
        at org.jetbrains.intellij.Utils$_pluginXmlFiles_closure1.doCall(Utils.groovy:59)
        at org.jetbrains.intellij.Utils.pluginXmlFiles(Utils.groovy:51)
        at org.jetbrains.intellij.Utils.sourcePluginXmlFiles(Utils.groovy:40)
        at org.jetbrains.intellij.Utils$sourcePluginXmlFiles$0.call(Unknown Source)
        at org.jetbrains.intellij.IntelliJPlugin$_configurePlugin_closure2.doCall(IntelliJPlugin.groovy:61)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
```
[I'm using](https://github.com/uwolfer/gerrit-intellij-plugin/blob/master/src/main/resources/META-INF/plugin.xml#L16) this doctype: `<!DOCTYPE idea-plugin PUBLIC "Plugin/DTD" "http://plugins.jetbrains.com/plugin.dtd">`

I think it would be easy to change the ctor of [`XmlParser`](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/groovy/org/jetbrains/intellij/Utils.groovy#L169) to the [one which accepts doctype declaration](http://docs.groovy-lang.org/latest/html/api/groovy/util/XmlParser.html#XmlParser(boolean,%20boolean,%20boolean)) (untested).

**Comment by zolotov** [comment]
Thanks, will be fixed in the next version
