### ISSUE TITLE
Searchable options index builder failed for lateinit property

### ISSUE THREAD

**Issue by izhangzhihao** [JetBrains/gradle-intellij-plugin#972]
It suddenly [build failed](https://github.com/izhangzhihao/intellij-rainbow-brackets/runs/6143368464?check_suite_focus=true#step:10:43) after upgrading to 1.5.3

```
Starting searchable options index builder
kotlin.UninitializedPropertyAccessException: lateinit property color1 has not been initialized
Searchable options index builder failed
	at com.github.izhangzhihao.rainbow.brackets.settings.form.RainbowOptionsPanel.<init>(RainbowOptionsPanel.kt:56)
	at com.github.izhangzhihao.rainbow.brackets.settings.RainbowColorsPageFactory.createPanel(RainbowColorsPageFactory.kt:24)
	at com.intellij.application.options.colors.ColorAndFontOptions$InnerSearchableConfigurable.createPanel(ColorAndFontOptions.java:1322)
	at com.intellij.application.options.colors.ColorAndFontOptions$InnerSearchableConfigurable.createComponent(ColorAndFontOptions.java:1353)
	at com.intellij.ide.ui.search.SearchUtil.processConfigurables(SearchUtil.java:81)
	at com.intellij.ide.ui.search.SearchUtil.processProjectConfigurables(SearchUtil.java:51)
	at com.intellij.ide.ui.search.TraverseUIStarter.startup(TraverseUIStarter.java:98)
	at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:81)
	at com.intellij.idea.ApplicationLoader$startApp$8$1$1.run(ApplicationLoader.kt:245)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.idea.ApplicationLoader$startApp$8$1.run(ApplicationLoader.kt:244)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:8[43](https://github.com/izhangzhihao/intellij-rainbow-brackets/runs/6143368464?check_suite_focus=true#step:10:43))
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:[45](https://github.com/izhangzhihao/intellij-rainbow-brackets/runs/6143368464?check_suite_focus=true#step:10:45)4)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:[50](https://github.com/izhangzhihao/intellij-rainbow-brackets/runs/6143368464?check_suite_focus=true#step:10:50)1)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

The source code is here:

https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/5c0431da164c6bee1881e2c8c23d999f06b626a4/src/main/kotlin/com/github/izhangzhihao/rainbow/brackets/settings/form/RainbowOptionsPanel.kt#L41-L45

**Comment by hsz** [comment]
Thanks for reporting, in working on the fix ATM.
Please revert to 1.5.2 for now.

**Comment by hsz** [comment]
Related to #978
